### PR TITLE
8306707: Support pluggable image loading via javax.imageio

### PR DESCRIPTION
**Pull request by mstr2**
This PR extends the image loading capabilities of JavaFX by plugging into the `javax.imageio` API, allowing applications to use third-party libraries like [TwelveMonkeys](https://github.com/haraldk/TwelveMonkeys) to load a wide variety of image formats.

The built-in JavaFX image loaders continue to be used for all supported image formats. If an image can't be loaded using one of the built-in image loaders, JavaFX will probe the ImageIO registry for image readers that can load the image instead.

This PR also adds support for variable-density images like SVG. Variable-density images will be rasterized using the screen's pixel density, ensuring they are rendered at a higher resolution on high-DPI screens.

The proposed feature works transparently across all JavaFX image APIs, including images referenced by stylesheets, and images contained in data-URIs.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8306707](https://bugs.openjdk.org/browse/JDK-8306707): Support pluggable image loading via javax.imageio (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1093/head:pull/1093` \
`$ git checkout pull/1093`

Update a local copy of the PR: \
`$ git checkout pull/1093` \
`$ git pull https://git.openjdk.org/jfx.git pull/1093/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1093`

View PR using the GUI difftool: \
`$ git pr show -t 1093`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1093.diff">https://git.openjdk.org/jfx/pull/1093.diff</a>

</details>

### CODE REVIEW

**Comment by andy-goryachev-oracle** [comment]
[objection]

Is it possible to make it as an independent library, or does it require changes in the fx core to work?

The two issues I have with this proposal are:
1. it will require an automatic dependency on java.desktop
2. it's a half-measure, the actual fix would be to actually implement this functionality in the FX core

But as a library, the decision to include javax.desktop is trivial for an application.

What do you think?

**Comment by mstr2** [comment]
> Is it possible to make it as an independent library, or does it require changes in the fx core to work?

It does require some changes to make variable-density images like SVG work correctly, and it requires adding a new `ImageLoader`, which is not API and thus cannot be done by a third-party library.

> 
> The two issues I have with this proposal are:
> 
> 1. it will require an automatic dependency on java.desktop

`javafx.graphics` already requires `java.desktop`, no change here.

> 2. it's a half-measure, the actual fix would be to actually implement this functionality in the FX core

Well, it enables application developers to use any existing Image I/O plugin out there (of which there are many). Adding a random new image format directly to JavaFX every now and then feels more like a half-measure to me, as you'll always end up missing just that exotic format that someone so desperately needs.

Short of actually creating new API, adding more image formats directly to JavaFX doesn't solve the extensibility problem. And even if we did create new API in JavaFX, it bears the question why we would need to have two different imaging APIs in the Java world, one for which a large number of plugins already exist (`javax.imageio`), and one for which this is not the case. It's a tough sell for plugin authors to recreate all of those plugins for the very narrow use case of supporting a random JavaFX application out there.

**Comment by swpalmer** [comment]
> On Apr 24, 2023, at 7:34 PM, mstr2 ***@***.***> wrote:
> 
…
> ﻿Short of actually creating new API, adding more image formats directly to JavaFX doesn't solve the extensibility problem. And even if we did create new API in JavaFX, it bears the question why we would need to have two different imaging APIs in the Java world, one for which a large number of plugins already exist (javax.imageio), and one for which this is not the case. It's a tough sell for plugin authors to recreate all of those plugins for the very narrow use case of supporting a random JavaFX application out there.

I have always thought that image loading in Java is a mess that needs a significant refactoring. 
ImageIO should be the only way images are loaded or saved (with the possible exception of splash screen support). It makes little sense to maintain multiple image loaders for the same formats. Image loading should not depend on java.desktop as image loading and saving is not exclusive to desktop applications.
Both AWT and JavaFx image losing and saving should interface with ImageIO through primitive arrays, ByteBuffers, etc. such that specific java.desktop or JavaFx classes such as BufferedImage or WriteableImage are not required by the module that contains the ImageIO implementation.
I realize this is out of scope for this proposal, but it would be great if things moved in that direction and the JavaFx dependencies on java.desktop can be reduced rather than become more ingrained. The fact that JavaFx and Swing are tied together when they should be independent is somewhat irritating when creating a reduced JRE for a bundled application.

Just my 2c. 

Scott

**Comment by mstr2** [comment]
> I realize this is out of scope for this proposal, but it would be great if things moved in that direction and the JavaFx dependencies on java.desktop can be reduced rather than become more ingrained. The fact that JavaFx and Swing are tied together when they should be independent is somewhat irritating when creating a reduced JRE for a bundled application. Just my 2c. Scott

I don't expect the modularization of Java to be significantly changed in any foreseeable future. But if it did, there would be nothing stopping us from changing the proposed implementation of this feature.

Postponing JavaFX image loading extensibility until the day comes where the JDK develops an Image I/O abstraction layer just means that JavaFX will not have that capability any time soon, maybe ever.

**Comment by yososs** [comment]
The current JavaFX IIO extension is
ImageStorage.getInstance().addImageLoaderFactory()
is possible.
Therefore, the changes to JavaFX IIO extension points are:
I think it would be better to change the module (module-info) of the ImageStorage class to public.

**Comment by mstr2** [comment]
> The current JavaFX IIO extension is ImageStorage.getInstance().addImageLoaderFactory() is possible. Therefore, the changes to JavaFX IIO extension points are: I think it would be better to change the module (module-info) of the ImageStorage class to public.

If we did that, we'd have two image loading APIs in the Java world, and lacking suitable plugins, still no support for most other image formats. On the other hand, Image I/O plugins are readily available.

> I think it would be better to focus on Vector Image support.

This PR also adds support for vector images. [TwelveMonkey's](https://github.com/haraldk/TwelveMonkeys) SVG plugin works out of the box, as you'd expect it.

**Comment by mstr2** [comment]
> **Image scaling is now also provided by ImageView.**

Image rescaling is only meaningful for fixed-density images. Vector images can be rendered at their requested resolution (taking into account screen DPI scaling) without pixel-based rescaling. This PR does exactly that.

> For Vector Image, I thought of a way to use requestWidth, requestHeight in javafx Image class constructor.
> 
> ```java
> public Image(String url,
>   double requestedWidth,
>   double requestedHeight,
>   boolean preserveRatio,
>   boolean smooth,
>   boolean backgroundLoading)
> ```

That's exactly what this PR gives you. If you load an SVG image using this constructor, you'll get an image that is rendered at exactly your requested resolution (again, taking into account DPI scaling).

> 
> Monitoring the size of the ImageView and calling setImage would probably work with the least amount of memory required.

That's out of scope for this feature proposal, and not something I would be in favor of.

**Comment by mstr2** [comment]
I've changed the implementation such that this feature does not lock JavaFX into depending on `java.desktop`. For applications that require `java.desktop` (which as of now, are _all_ JavaFX applications), the feature will be available. If we remove the `java.desktop` dependency in the future (by making it a static dependency), the feature will simply not be available.

I have prepared a small sample application that showcases how the feature can be used to load SVG images in a JavaFX application: https://github.com/mstr2/jfx-imageio-sample

I think this is the only way that we're ever going to get SVG support in JavaFX. Let's face it: the OpenJFX project will never be able to create its own SVG rasterizer, and it is very unlikely to take on such a huge dependency on a third-party implementation. Supporting the ImageIO API (which has an established ecosystem of image loader plugins) is the only way this highly-requested feature can realistically make its way into JavaFX.

Creating a new, bespoke JavaFX API for image loader plugins is a non-starter, as it is very unlikely that there is enough community interest in actually creating the plugins in the first place.

/open

**Comment by mstr2** [comment]
It seems like the bot doesn't want to reopen this PR...

**Comment by kevinrushforth** [comment]
Very odd. I'll alert the Skara folks, and reopen it manually.

**Comment by kevinrushforth** [comment]
Reopen.

**Pull request closed without merging**
