### PR TITLE
8208088: Memory Leak in ControlAcceleratorSupport

### PR DESCRIPTION
**Pull request by arapte**
The method `ControlAcceleratorSupport.doAcceleratorInstall(final List<? extends MenuItem> items, final Scene scene)` adds a `ChangeListener` on `MenuItem.acceleratorProperty()`. This listener is not removed when the MenuItem is removed from scenegraph.
Adding and removing a MenuItem results in multiple copies of the listener added to MenuItem.acceleratorProperty().

Fix is to remove the listener when MenuItem is removed.
Fix can be verified by checking the number of instances of `ControlAcceleratorSupport.lambda` using _jvisualvm_. 
Without this fix, the number of `ControlAcceleratorSupport.lambda` increase in multiple of number of MenuItems being removed and added back.
With fix, the count is always same as number of MenuItems in scenegraph.

Also there is another ListChangeListener added to a `ObservableList<MenuItem> items` in the method `ControlAcceleratorSupport.doAcceleratorInstall(final ObservableList<MenuItem> items, final Scene scene)`. There was a TODO note to remove this listener.
This listener is added on `MenuBarButton.getItems()` and not on `Menu.getItems()`.  This `MenuBarButton` is created by `MenuBarSkin` to show a `Menu`. This `MenuBarButton` gets disposed when the related `Menu` is removed from scenegraph, and so the added `ListChangeListener` gets GCed. Hence it is not required to explicitly remove the listener. 
Added a comment explaining this behavior in place of the TODO.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8208088](https://bugs.openjdk.java.net/browse/JDK-8208088): Memory Leak in ControlAcceleratorSupport

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Ajit Ghaisas](https://openjdk.java.net/census#aghaisas) (@aghaisas - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/429/head:pull/429` \
`$ git checkout pull/429`

Update a local copy of the PR: \
`$ git checkout pull/429` \
`$ git pull https://git.openjdk.java.net/jfx pull/429/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 429`

View PR using the GUI difftool: \
`$ git pr show -t 429`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/429.diff">https://git.openjdk.java.net/jfx/pull/429.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
Is there a unit test that can validate this fix?

**Comment by arapte** [comment]
> Is there a unit test that can validate this fix?

I have added a unit test using a new shim class. Test verifies size of the map that is added as part of this fix.
So the test won't compile without this PR.

**Comment by kevinrushforth** [comment]
The new unit test fails on all platforms, as you can see from the GitHub actions log:

```
2021-03-18T12:45:36.7904530Z test.javafx.scene.control.ControlAcceleratorSupportTest > sanityTestListenerMapShouldBeEmpty FAILED
2021-03-18T12:45:36.8007000Z     java.lang.AssertionError: expected:<0> but was:<22>
2021-03-18T12:45:36.8099570Z         at org.junit.Assert.fail(Assert.java:91)
2021-03-18T12:45:36.8201200Z         at org.junit.Assert.failNotEquals(Assert.java:645)
2021-03-18T12:45:36.8264450Z         at org.junit.Assert.assertEquals(Assert.java:126)
2021-03-18T12:45:36.8366120Z         at org.junit.Assert.assertEquals(Assert.java:470)
2021-03-18T12:45:36.8455230Z         at org.junit.Assert.assertEquals(Assert.java:454)
2021-03-18T12:45:36.8559230Z         at test.javafx.scene.control.ControlAcceleratorSupportTest.sanityTestListenerMapShouldBeEmpty(ControlAcceleratorSupportTest.java:43)
2021-03-18T12:45:36.8886110Z 
2021-03-18T12:45:36.8989430Z test.javafx.scene.control.ControlAcceleratorSupportTest > testNumberOfListenersByRemovingAndAddingMenuItems FAILED
2021-03-18T12:45:36.9092540Z     java.lang.AssertionError: expected:<4> but was:<26>
2021-03-18T12:45:36.9194300Z         at org.junit.Assert.fail(Assert.java:91)
2021-03-18T12:45:36.9296390Z         at org.junit.Assert.failNotEquals(Assert.java:645)
2021-03-18T12:45:36.9393550Z         at org.junit.Assert.assertEquals(Assert.java:126)
2021-03-18T12:45:36.9495860Z         at org.junit.Assert.assertEquals(Assert.java:470)
2021-03-18T12:45:36.9596430Z         at org.junit.Assert.assertEquals(Assert.java:454)
2021-03-18T12:45:36.9700420Z         at test.javafx.scene.control.ControlAcceleratorSupportTest.testNumberOfListenersByRemovingAndAddingMenuItems(ControlAcceleratorSupportTest.java:65)
```

**Comment by arapte** [comment]
> The new unit test fails on all platforms, as you can see from the GitHub actions log:

The test failed because, change listeners added by other tests get accumulated in the `changeListenerMap`. These listeners can get GCed only if the tests correctly cleanup themselves. The test passes if executed individually. 
The test needed correction that, it should not assume the Map to be empty, instead verify fix by using current size of the `changeListenerMap` as reference.
The Windows pre-submit test action has failed because _Task :graphics:compileDecoraNativeShadersWin FAILED_, and not because of the new test.
Please take a look.

**Review by kevinrushforth — APPROVED** [review]
The fix looks good.

The test looks OK as far as it goes, although I note that it is testing for the leak in an indirect way, since it looks at the `changeListenerMap` rather than checking the listeners of `menuitem.acceleratorProperty()` which is what we really care about. Is there a way to test it more directly? If not then I think this is fine.

**Comment by arapte** [comment]
> Is there a way to test it more directly?

`ControlTestUtils` provides a way to get the number of listeners added to a property. Please check the updated test. With this direct way, should we keep the indirect way of testing which uses `changeListenerMap` ?

**Comment by kevinrushforth** [comment]
The updated test looks good. I confirm that it fails without the fix and passes with the fix. In order to do that I locally deleted the newly added shim class and comment out all calls to `get_ListenerMapSize`. I'd recommend to get rid of the indirect way of testing, since it will mean you can remove the newly added `ControlAcceleratorSupportShim` class and the `ControlAcceleratorSupport ::testGetListenerMapSize` method.

**Comment by arapte** [comment]
> I'd recommend to get rid of the indirect way of testing

I have removed the indirect way, please take a look.

**Review by kevinrushforth — APPROVED** [review]

**Review by aghaisas — APPROVED** [review]

**Comment by RationalityFrontline** [comment]
After updating to jfx 17, I detected memory leak in my application (every controller that has menu items won't get garbage collected after closing its stage), with visualvm I found it was caused by class ControlAcceleratorSupport. This kind of memory leak doesn't happen on jfx 16, so I guess there is something wrong with this PR.

I've created a sample project that could reproduce and verify the memory leak: [jfx-test](https://github.com/RationalityFrontline/jfx-test/tree/ControlAcceleratorSupport) (on git branch ControlAcceleratorSupport).

Run command `gradlew run` and you should see the following ui interface:
image

Clicking button `Call GC and Print MenuItems` will call `System.gc()` and print current ungarbaged menu items to console, clicking menu `Restart Stage` will call `Stage.close()` and launch a new same Stage. 

After clicking `Restart Stage` several times, click `Call GC and Print MenuItems`, you will see lots of ungarbaged menu items. However, by changing jfx version to 16 in `build.gradle.kts`, you will always see only one menu item.

If menu items are set with action listeners, then these listeners also won't be garbage collected, typically these listeners hold references to controllers, which made all closed controllers leaked. This made jfx 17 unusable.

**Comment by Maran23** [comment]
> After updating to jfx 17, I detected memory leak in my application (every controller that has menu items won't get garbage collected after closing its stage), with visualvm I found it was caused by class ControlAcceleratorSupport. This kind of memory leak doesn't happen on jfx 16, so I guess there is something wrong with this PR.
> 
> I've created a sample project that could reproduce and verify the memory leak: [jfx-test](https://github.com/RationalityFrontline/jfx-test/tree/ControlAcceleratorSupport) (on git branch ControlAcceleratorSupport).
> 
> Run command `gradlew run` and you should see the following ui interface:
> image
> 
> Clicking button `Call GC and Print MenuItems` will call `System.gc()` and print current ungarbaged menu items to console, clicking menu `Restart Stage` will call `Stage.close()` and launch a new same Stage.
> 
> After clicking `Restart Stage` several times, click `Call GC and Print MenuItems`, you will see lots of ungarbaged menu items. However, by changing jfx version to 16 in `build.gradle.kts`, you will always see only one menu item.
> 
> If menu items are set with action listeners, then these listeners also won't be garbage collected, typically these listeners hold references to controllers, which made all closed controllers leaked. This made jfx 17 unusable.

Could you please report the bug at https://bugreport.java.com/ with a minimum reproducible example (written in Java)?

**Comment by kevinrushforth** [comment]
> Could you please report the bug at https://bugreport.java.com/ with a minimum reproducible example (written in Java)?

I was just going to mention the same thing. See the project [README](https://github.com/openjdk/jfx#readme).

**Comment by RationalityFrontline** [comment]
@Maran23 @kevinrushforth Bug reported via https://bugreport.java.com/bugreport/ with a minimum reproducible example written in Java, internal review ID : 9071415.

**Pull request closed without merging**
