### PR TITLE
8270959: Update boot JDK to 16.0.2

### PR DESCRIPTION
**Pull request by kevinrushforth**
Update boot JDK used to build JavaFX to JDK 16.0.2, which supersedes 16.0.1.

NOTE: this is targeted to `jfx17`.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8270959](https://bugs.openjdk.java.net/browse/JDK-8270959): Update boot JDK to 16.0.2

### Reviewers
 * [Ambarish Rapte](https://openjdk.java.net/census#arapte) (@arapte - **Reviewer**)
 * [Joeri Sykora](https://openjdk.java.net/census#sykora) (@tiainen - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/583/head:pull/583` \
`$ git checkout pull/583`

Update a local copy of the PR: \
`$ git checkout pull/583` \
`$ git pull https://git.openjdk.java.net/jfx pull/583/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 583`

View PR using the GUI difftool: \
`$ git pr show -t 583`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/583.diff">https://git.openjdk.java.net/jfx/pull/583.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
I'd like two reviewers given that we are in ramp-down for JavaFX 17.

/reviewers 2

**Review by arapte — COMMENTED** [review]
Looks good. to me, verified Mac and Windows build.

**Review by arapte — APPROVED** [review]

**Comment by kevinrushforth** [comment]
@johanvos or @tiainen can one of you be the second reviewer for this?

**Comment by johanvos** [comment]
We'll check on all platforms.

**Review by tiainen — APPROVED** [review]
Build succeeded on all platforms.

**Pull request closed without merging**
