### PR TITLE
8302294 : Cherry-pick WebKit 615.1 stabilization fixes

### PR DESCRIPTION
**Pull request by HimaBinduMeda**
Cherry-pick stabilisation fixes till 2.38.4.
Verified unit tests and drt. No issue observed.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8302294](https://bugs.openjdk.org/browse/JDK-8302294): Cherry-pick WebKit 615.1 stabilization fixes

### Reviewers
 * [Joeri Sykora](https://openjdk.org/census#sykora) (@tiainen - Author)
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx pull/1033/head:pull/1033` \
`$ git checkout pull/1033`

Update a local copy of the PR: \
`$ git checkout pull/1033` \
`$ git pull https://git.openjdk.org/jfx pull/1033/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1033`

View PR using the GUI difftool: \
`$ git pr show -t 1033`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1033.diff">https://git.openjdk.org/jfx/pull/1033.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
Reviewers: @kevinrushforth and @johanvos or @tiainen 

@jaybhaskar Can you also take a look?

/reviewers 2

**Review by tiainen — APPROVED** [review]
Building and testing succeeded.

**Review by kevinrushforth — APPROVED** [review]
Looks good. Tested on all three platforms.

**Pull request closed without merging**
