### PR TITLE
8236651: Simplify and update glass gtk backend

### PR DESCRIPTION
**Pull request by tsayao**
### Summary
* Simplify and update the Gtk glass backend, making Linux a first-class OpenJFX platform.

### Goals
* Make Linux a first-class OpenJFX platform (see Motivation);
* Simplify the code and reduce it's size;
* Update to gtk3 (it was originally a port from gtk2);
* Remove unused code (such as applets and web start);
* Prepare the ground for a possible future Wayland support.
### Testing
./gradlew -PEXTRA_TEST_ARGS='-Djavafx.gtk.experimental=true' -PFULL_TEST=true -PUSE_ROBOT=true :systemTests:test

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Testing

|     | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- |
| Build / test | ✔️ (1/1 passed) | ✔️ (1/1 passed) | ✔️ (1/1 passed) |

### Integration blocker
&nbsp;⚠️ The change requires a CSR request to be approved.

### Issue
 * [JDK-8236651](https://bugs.openjdk.java.net/browse/JDK-8236651): Simplify and update glass gtk backend

### Download
`$ git fetch https://git.openjdk.java.net/jfx pull/77/head:pull/77`
`$ git checkout pull/77`

### CODE REVIEW

**Comment by tsayao** [comment]
There are still some sizing issues that I am aware of.

**Comment by kevinrushforth** [comment]
> Please, mark it as WIP.

You can do this by editing the title and adding `WIP: ` as a prefix.

**Comment by kevinrushforth** [comment]
This sort of enhancement needs to be discussed on the openjfx-dev mailing list first. While the WIP PR might be used to illustrate what you have in mind to propose, it is premature to actually review the implementation without first discussing whether and it makes sense to do it, what the high-level goals are, etc.

**Comment by tsayao** [comment]
I understand. Will do that when everything is 100%.

**Comment by tsayao** [comment]
Sizing and positioning completed and fairly tested.

Will look into mouse grabbing.

**Comment by tsayao** [comment]
Performance test (on my setup, it runs slightly faster with this patch):

```
import javafx.application.Application;
import javafx.application.Platform;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.stage.Stage;

import java.time.Duration;
import java.time.Instant;
import java.util.Timer;
import java.util.TimerTask;

public class HelloFx extends Application {

    public HelloFx() {
    }

    @Override
    public void start(Stage stage) {
        Instant start = Instant.now();

        Scene mainScene = new Scene(new Label("Perfomance test"), 600, 600);
        stage.setScene(mainScene);
        stage.show();

        for (int i=0; i<1000; i++) {
            Stage stage1 = new Stage();
            Scene scene = new Scene(new Label("hi"), 200, 200);
            stage1.setScene(scene);

            stage1.setOnShown(e -> new Timer().schedule(
                    new TimerTask() {
                        @Override
                        public void run() {
                            Platform.runLater(stage1::hide);
                        }
                    },
                    100
            ));

            stage1.showAndWait();
        }

        stage.close();

        Instant end = Instant.now();

        System.out.println(Duration.between(start, end).toString()
                .substring(2)
                .replaceAll("(\\d[HMS])(?!$)", "$1 ")
                .toLowerCase());

        Platform.exit();
    }
}

```

**Comment by tsayao** [comment]
To anyone willing to test this, here is a binary test-release for linux:

https://github.com/tsayao/jfx/releases/tag/test-glass-gtk

**Comment by tsayao** [comment]
It's ready for an initial look.

If anyone has issues with Linux, I will fix it.

**Comment by tsayao** [comment]
**Code Changes**

* glass_window.cpp / glass_window.h
    * Removed WindowContextPlug and WindowContextChild (that were used for applets / web start) and moved everything to
one class named WindowContext (since inheritance was no required anymore)
    * Changed set_enabled() to use gtk_widget_set_sensitive instead of custom code;
    * Moved to gtk signals instead of gdk events (to use gtk_widget_set_sensitive and gtk_grab_add);
    * Frame Extents: Removed the code to request extents and gtk already does it by default;
    * Focus Grab: Use gtk_grab_add and gtk window group functions instead of custom code;
    * Size calculation: Reworked size calculation code. In general, X windows are content size instead
    of whole window size (considering extents - frame decorations). OpenJfx uses "whole window size" as
    window sizes, so it requires a "hack" to recalculate sizes when set_bounds() is called with window
    sizes instead of content sizes. The rework was to simplify code paths and make it more straightforward.
    * Other Size calculation changes:
        * Use gtk_window_set_default_size() for initial size which is the appropriate function; 
        * Gravity is now ignored as it is on Windows glass impl;
        * Avoid sending same sizes to Java;
        * Introduced calculate_adjustments() which is a fallback when frame extents is not present (it's optional
        to window managers to implement it);
    * Geometry: Min / Max sizes - reworked it to simplify / Concentrated geometry changes on
      apply_geometry().
    * Mouse grab: Reworked it to use to correct functions according to gtk+ version;
    * Draw: Reworked it to use the correct calls accord to gtk+ version changes;
    * Fixed JDK-8237491;
    * Moved background code to paint() as gtk3 uses styles to set the background and other functions were deprecated;
    * Reorganized function order on glass_window.cpp to match glass_window.h


* GlassCursor.cpp
    * Gtk+3 uses a name-like-css approach - so it was properly ported to gtk3 way;
    * Reworked Gtk+2 to use a function instead of manual calls to find the cursor;

* GtkWindow.java
    * Moved the extents special case to native glass;

* GlassApplication.cpp
    * Removed Gdk events where possible (it's now on glass_window as signals);
    * Removed applet/web start code;

* GlassView.cpp
    * Changes to reflect frame extents rework on glass_window

* GlassWindow.cpp
    * WindowContextTop -> WindowContext
    * Removed applet / web start code;
    * Removed frame extents (which is not called anymore due to GtkWindow.java change);

* glass_general.cpp
    * Removed functions that became unused;
    * Added is_grab_disabled() that is used on glass_window

* glass_window_ime.cpp
    * WindowContextTop -> WindowContext;
    
* glass_dnd.cpp / glass_dnd.h
    * Ported to Gtk signals;
    * Use all possible image formats (supported by GdkPixbuf / OpenJfx) - .gif is now possible (for ex.);
    * Allow COMPOUND_TEXT;
    * Do not request content while dragging;
    * Reduce overall code size.

**Comment by kevinrushforth** [comment]
This is going to need further discussion on the mailing list as indicated above, so it is still premature to review it (i.e., it should still be considered effectively a "WIP" until that discussion happens). Additionally, this is a significant and risky change, so I'd like additional eyes on it when we do get to the point of reviewing it.

**Comment by tsayao** [comment]
I have been testing this for several days on ubuntu 18.04 and it's working good. It pass system tests, runs Ensemble 8 and Scenebuilder.

Will have to do some tests on 16.04.

**Comment by tsayao** [comment]
Results with Ubuntu **16.04**

image

Will look into test.javafx.stage.DeiconifiedWithChildTest and test.robot.javafx.scene.layout.RegionBackgroundFillUITest.

I've used a VM, so might be related.

Also ran Enseble8 and the Drag and Drop test app with no apparent issues.

**Comment by tsayao** [comment]
Ubuntu 20.04 Test Results

image

**Comment by tsayao** [comment]
Test on 16.04 (without Webkit - it does not build on 16.04 anymore)

image

**Comment by tsayao** [comment]
I will keep testing it, but I think it's looking good.

**Comment by kevinrushforth** [comment]
I see a lot of work going into this.

In order for this to progress beyond the prototype or concept phase, we will need to have a discussion on the openjfx-dev mailing list in a separate email thread that is not directly tied to the PR -- meaning not a reply to the RFR thread and not a comment in the PR.

@tsayao When you are ready, please send a short email (not a reply to any existing message) to openjfx-dev@openjdk.java.net with the following:

1. A short summary of the proposed enhancement
2. The goals of the proposed enhancement
3. A description of the proposed changes (basically, the bullet items from the description of this PR)
4. A pointer to this PR for reference

I want to focus the openjfx-dev discussion on getting general agreement on the overall approach rather than on the details of the code changes. This is a big change, so getting feedback on the overall goals and approach is important; review comments in the PR aren't the best way to have that discussion.

We aren't following the formal JEP process for JavaFX features, but the JEP template in [JEP 2](https://openjdk.java.net/jeps/2) is a good format to follow for large or high-impact features to make sure that the motivation, goals, and tradeoffs are documented.

Finally, I note that this will eventually need a CSR, but that can be done once there is agreement on the approach, and when this is farther along in the review process.

**Comment by tsayao** [comment]
@kevinrushforth Ok, will do as the instructions. Thanks.

**Comment by pankaj-bansal** [comment]
I ran the systemTests on Ubuntu 18.04using gradle -PEXTRA_TEST_ARGS='-Djavafx.gtk.experimental=true' -PFULL_TEST=true -PUSE_ROBOT=true :systemTests:cleanTest :systemTests:test. Following are the results

Results_18 04

**Comment by kevinrushforth** [comment]
In case it is useful to those reviewing the code, I have created a [WIP pull request](https://github.com/kevinrushforth/jfx/pull/1) in my repo solely for the purpose of looking at the diffs between the existing gtk native code and the experimental GTK native code from *this* pull request.

**Comment by kevinrushforth** [comment]
I am running a full test using GTK 3 on Ubuntu 20.04 and will publish results. I will later do the same for Oracle Linux 7.7.

One thing to note is that this new GTK pipeline doesn't run on Ubuntu 16.04. I get the following running any program:

```
$ java -Djavafx.gtk.experimental=true -Djdk.gtk.verbose=true HelloRectangle
checking GTK version 3
trying GTK library libgtk-3.so.0
using GTK library version 3 set libgtk-3.so.0
Glass GTK library to load is glassgtk3_exp
loaded gdk_x11_display_set_window_scale
java: symbol lookup error: /localhome/kcr/javafx/jfx-tmp/jfx/rt/build/sdk/lib/libglassgtk3_exp.so: undefined symbol: gdk_display_get_n_monitors
```

**Comment by kevinrushforth** [comment]
Here are the results with Ubuntu 20.04:

Ubuntu-20 04-test-results

**Comment by tsayao** [comment]
> I am running a full test using GTK 3 on Ubuntu 20.04 and will publish results. I will later do the same for Oracle Linux 7.7.
> 
> One thing to note is that this new GTK pipeline doesn't run on Ubuntu 16.04. I get the following running any program:
> 
> ```
> $ java -Djavafx.gtk.experimental=true -Djdk.gtk.verbose=true HelloRectangle
> checking GTK version 3
> trying GTK library libgtk-3.so.0
> using GTK library version 3 set libgtk-3.so.0
> Glass GTK library to load is glassgtk3_exp
> loaded gdk_x11_display_set_window_scale
> java: symbol lookup error: /localhome/kcr/javafx/jfx-tmp/jfx/rt/build/sdk/lib/libglassgtk3_exp.so: undefined symbol: gdk_display_get_n_monitors
> ```

I have limited GTK compilation to use GTK 3.8 symbols. Will run more tests, but should fix it.

**Comment by pankaj-bansal** [comment]
I have run the test on OL82 on updated code. Following are the results. I will rerun this on Ubuntu 18.04 and get back with the results
OL82

**Comment by pankaj-bansal** [comment]
I ran the systemTests on OL8.2 using gradle -PEXTRA_TEST_ARGS='-Djavafx.gtk.experimental=true' -PFULL_TEST=true -PUSE_ROBOT=true :systemTests:cleanTest :systemTests:test. Following are the results

OL82

**Comment by pankaj-bansal** [comment]
After the latest commit on June 10, this is not building for me on my Ubuntu 18.04. I am attaching the build log for reference.
[build.log](https://github.com/openjdk/jfx/files/4770864/build.log)

**Comment by tsayao** [comment]
> After the latest commit on June 10, this is not building for me on my Ubuntu 18.04. I am attaching the build log for reference.
> [build.log](https://github.com/openjdk/jfx/files/4770864/build.log)

It's now fixed. I had used two compilation parameters to limit Gtk on 3.8 (so it would generate error if any symbol > 3.8 were used). But that does not seem to work on 18.04, so I removed it.

**Comment by kevinrushforth** [comment]
> I had used two compilation parameters to limit Gtk on 3.8 (so it would generate error if any symbol > 3.8 were used). But that does not seem to work on 18.04, so I removed it.

Good. I was going to ask you about that, so I'm happy to see it gone.

**Comment by tsayao** [comment]
I have investigated the Tab Pane Drag Test and it works manually. 

```
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Tab;
import javafx.scene.control.TabPane;
import javafx.stage.Stage;

public class Test
        extends Application {

    @Override
    public void start(Stage stage) {
        TabPane tabPane = new TabPane();
        tabPane.setTabDragPolicy(TabPane.TabDragPolicy.REORDER);
        Scene scene = new Scene(tabPane, 800, 600);
        stage.setScene(scene);
        Tab tab1 = new Tab("Tab1");
        Tab tab2 = new Tab("Tab2");

        tabPane.getTabs().addAll(tab1, tab2);


        stage.setAlwaysOnTop(true);
        stage.show();
    }

    public static class Main {
        public static void main(String[] args) {
            Application.launch(Test.class, args);
        }
    }
}
```

**Comment by pankaj-bansal** [comment]
Following are results in Ubuntu 18.04 after fix for tab pane tests.
Results_18 04

**Comment by pankaj-bansal** [comment]
This is the result on OL 82 with latest commit
OL82

**Comment by tsayao** [comment]
@pankaj-bansal Sorry for commiting again. Now the Tab Pane test works properly.

**Comment by kevinrushforth** [comment]
> If you want these commits to be preserved when you integrate, you will need to make a 'merge-style' pull request.

Please ignore this information from Skara. I don't know what caused it, but I've pinged the Skara folks about it.

**Comment by Torbuntu** [comment]
Would it be possible and related to add the gtk touch events to this PR as part of the Glass GTK3 update? Or would  follow up update PR adding that be more appropriate? 

Currently linux desktop does not have touch support because of the missing gesture/touch events from gtk3.

**Comment by tsayao** [comment]
@Torbuntu Not to this PR, I don't want to delay it too much. But can be done (I just do not own a touch device currently).

**Comment by Torbuntu** [comment]
Sounds good! I have a few devices I'd be more than excited to test on, and even help add the feature myself if I can figure it out if time is a big issue?

**Comment by tsayao** [comment]
I would starting hooking gtk event signals (https://developer.gnome.org/gtk3/stable/GtkWidget.html), specially the "touch-event" to JavaFx events (probably need to add through JNI). Should be simple. Contact me at thiago.sayao (gmail).

**Comment by Torbuntu** [comment]
> I would starting hooking gtk event signals (https://developer.gnome.org/gtk3/stable/GtkWidget.html), specially the "touch-event" to JavaFx events (probably need to add through JNI). Should be simple. Contact me at thiago.sayao (gmail).

Would it be safe you think to branch from your PR to have the updated gtk backend? It would be much easier to work with.

**Comment by tsayao** [comment]
Rebased onto "master" and squashed commits.

**Comment by tsayao** [comment]
Tested on Ubuntu 20.04

756 tests completed, 6 failed, 110 skipped

Failed:
```
test.robot.javafx.scene.ColorPickerTest > testColorPickerSceneChange FAILED
    java.lang.AssertionError: Timeout: Failed to receive onAction callback.
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.assertTrue(Assert.java:43)
        at test.robot.javafx.scene.ColorPickerTest.waitForLatch(ColorPickerTest.java:203)
        at test.robot.javafx.scene.ColorPickerTest.clickColorPickerPalette(ColorPickerTest.java:88)
        at test.robot.javafx.scene.ColorPickerTest.testColorPickerSceneChange(ColorPickerTest.java:119)

test.robot.javafx.scene.RobotTest > testKeyPress FAILED
    org.junit.ComparisonFailure: letter 'a' should be pressed by Robot expected:<[a]> but was:<[]>
        at org.junit.Assert.assertEquals(Assert.java:123)
        at test.robot.javafx.scene.RobotTest.testKeyboard(RobotTest.java:193)
        at test.robot.javafx.scene.RobotTest.testKeyPress(RobotTest.java:144)

test.robot.javafx.scene.tableview.TableViewResizeColumnToFitContentTest > resizeColumnToFitContentTest FAILED
    java.lang.AssertionError: resizeColumnToFitContent failed
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.assertTrue(Assert.java:43)
        at test.robot.javafx.scene.tableview.TableViewResizeColumnToFitContentTest.resizeColumnToFitContentTest(TableViewResizeColumnToFitContentTest.java:96)

test.robot.javafx.stage.IconifyTest > canIconifyDecoratedStage FAILED
    junit.framework.AssertionFailedError: expected:rgba(255,0,0,255) but was:rgba(62,62,62,255)
        at test.robot.testharness.VisualTestBase.assertColorEquals(VisualTestBase.java:179)
        at test.robot.javafx.stage.IconifyTest.lambda$canIconifyStage$4(IconifyTest.java:97)

test.robot.javafx.stage.IconifyTest > canIconifyTransparentStage FAILED
    junit.framework.AssertionFailedError: expected:rgba(0,255,0,255) but was:rgba(88,88,88,255)
        at test.robot.testharness.VisualTestBase.assertColorEquals(VisualTestBase.java:179)
        at test.robot.javafx.stage.IconifyTest.lambda$canIconifyStage$6(IconifyTest.java:108)

test.robot.javafx.stage.IconifyTest > canIconifyNonResizableStage FAILED
    junit.framework.AssertionFailedError: expected:rgba(255,0,0,255) but was:rgba(44,44,44,255)
        at test.robot.testharness.VisualTestBase.assertColorEquals(VisualTestBase.java:179)
        at test.robot.javafx.stage.IconifyTest.lambda$canIconifyStage$4(IconifyTest.java:97)

```

For some reason the html report is not being generated.

**Comment by ebresie** [comment]
Assume GTK4 support would come after this right?

**Comment by tsayao** [comment]
I would prefer this approach:
https://github.com/openjdk/jfx/pull/367

**Comment by kevinrushforth** [comment]
Given the alternate approach that you propose to pursue (which I agree is a better option), this PR should either be closed or moved to Draft.

**Comment by tsayao** [comment]
Closing it in favor of #367

**Pull request closed without merging**
