### PR TITLE
8321434: Update Gradle to 8.5

### PR DESCRIPTION
**Pull request by arapte**
Gradle 8.5.0 released on Nov 29, 2023, supports JDK 21.
We need to update Gradle to 8.5 in order to update the boot JDK.
There are not API level changes in Gradle that we need to work on, hence the change is only Gradle version update.

Also, merging the PR with boot jdk update to 21.0.1 b12

/issue add JDK-8321435

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issues
 * [JDK-8321434](https://bugs.openjdk.org/browse/JDK-8321434): Update Gradle to 8.5 (**Bug** - P3)
 * [JDK-8321435](https://bugs.openjdk.org/browse/JDK-8321435): Update boot JDK to 21.0.1 (**Bug** - P3)

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Joeri Sykora](https://openjdk.org/census#sykora) (@tiainen - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1300/head:pull/1300` \
`$ git checkout pull/1300`

Update a local copy of the PR: \
`$ git checkout pull/1300` \
`$ git pull https://git.openjdk.org/jfx.git pull/1300/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1300`

View PR using the GUI difftool: \
`$ git pr show -t 1300`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1300.diff">https://git.openjdk.org/jfx/pull/1300.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1300#issuecomment-1846337313)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
Note to reviewers: this does _not_ change the minimum version of the JDK needed to build or run JavaFX, which remains at JDK 17. Nor does it change the minimum version of gradle. However, if you do use JDK 21.x to build (which will be used by GHA and our production builds after this is integrated), then you will need gradle 8.5.

/reviewers 2

**Comment by kevinrushforth** [comment]
Reviewers: @kevinrushforth and either @johanvos or @tiainen

**Comment by johanvos** [comment]
> I just ran a build with this setup. The build succeeded (I didn't build Webkit). Is there anything else to test?

We typically do a full build, with SDK's and JMOD's and Javadoc etc, on the supported platforms. Given the large amount of platform-specific code in our gradle files, this is something that needs to be tested on different platforms.
(We're running tests currently as well).

**Pull request closed without merging**
