### PR TITLE
JDK-8322795 CSS performance regression up to 10x

### PR DESCRIPTION
**Pull request by hjohn**
The regression is caused by the `Collections.unmodifiableSet` wrapper not being recognized by `BitSet`, and a fall back is done to a less optimized version of `containsAll`.

As this is a regression fix, I've kept the fix as small as reasonable.  I'll provide a further optimized version as part of https://bugs.openjdk.org/browse/JDK-8322964 which eliminates the need for `BitSet` and `StyleClass` in the hot code paths which should result in a further CSS performance improvement.

I've tested this solution with the JFXCentral application locally and the regression seems resolved.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8322795](https://bugs.openjdk.org/browse/JDK-8322795): CSS performance regression up to 10x (**Bug** - P3)

### Reviewers
 * [Michael Strauß](https://openjdk.org/census#mstrauss) (@mstr2 - Committer)
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1314/head:pull/1314` \
`$ git checkout pull/1314`

Update a local copy of the PR: \
`$ git checkout pull/1314` \
`$ git pull https://git.openjdk.org/jfx.git pull/1314/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1314`

View PR using the GUI difftool: \
`$ git pr show -t 1314`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1314.diff">https://git.openjdk.org/jfx/pull/1314.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1314#issuecomment-1875727310)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
> As this is a regression fix, I've kept the fix as small as reasonable

Thanks. That seems like the best solution.

**Review by mstr2 — APPROVED** [review]
LGTM

**Review by kevinrushforth — APPROVED** [review]
This looks like a safe and effective performance fix.

**Comment by hjohn** [comment]
@kevinrushforth should this perhaps be backported to 21?

**Comment by johanvos** [comment]
that's a good candidate indeed.

**Pull request closed without merging**
