### PR TITLE
8254836: Cherry pick GTK WebKit 2.30.3 changes 

### PR DESCRIPTION
**Pull request by arun-Joseph**
Update to GTK WebKit 2.30.3
https://webkitgtk.org/2020/11/20/webkitgtk2.30.3-released.html

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8254836](https://bugs.openjdk.java.net/browse/JDK-8254836): Cherry pick GTK WebKit 2.30.3 changes

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Johan Vos](https://openjdk.java.net/census#jvos) (@johanvos - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jfx pull/392/head:pull/392`
`$ git checkout pull/392`

### CODE REVIEW

**Comment by kevinrushforth** [comment]
@johanvos @tiainen can you test this in your environment?

**Review by kevinrushforth — APPROVED** [review]
Looks good.

**Comment by johanvos** [comment]
We're creating test-builds in our CI for this now.

**Review by johanvos — APPROVED** [review]
sanity checks pass

**Pull request closed without merging**
