### PR TITLE
8282093: LineChart path incorrect when outside lower bound

### PR DESCRIPTION
**Pull request by abhinayagarwal**
This regression was caused in PR #667 in which I didn't take into account the lower bounds. I have added more tests and one manual test along with the fix. The manual test can be used to identify any future issues with paths outside lower and upper bounds easily.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8282093](https://bugs.openjdk.java.net/browse/JDK-8282093): LineChart path incorrect when outside lower bound

### Reviewers
 * [Ajit Ghaisas](https://openjdk.java.net/census#aghaisas) (@aghaisas - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/744/head:pull/744` \
`$ git checkout pull/744`

Update a local copy of the PR: \
`$ git checkout pull/744` \
`$ git pull https://git.openjdk.java.net/jfx pull/744/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 744`

View PR using the GUI difftool: \
`$ git pr show -t 744`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/744.diff">https://git.openjdk.java.net/jfx/pull/744.diff</a>

</details>

### CODE REVIEW

**Review by aghaisas — APPROVED** [review]
Thanks for fixing this regression. Changes look good.

**Comment by kevinrushforth** [comment]
This doesn't need a second reviewer.

**Pull request closed without merging**
