### PR TITLE
8260528: Clean glass-gtk sizing and positioning code

### PR DESCRIPTION
**Pull request by tsayao**
This is a new approach to rewrite parts of gtk glass backend to be more clean.

I will provide small "manageable" PR to incrementally make the backend better.

This PR adresses cleanup of the Size and Positioning code. It makes code more "straightforward" and easier to maintain.

Current status (Ubuntu 20.04):
image

(*) Some of the iconify tests are also failing on the main branch. 

`gradlew -PFULL_TEST=true -PUSE_ROBOT=true :systemTests:test --tests test.robot.javafx.stage.IconifyTest` on a second run produces 4 tests, 2 failures.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8260528](https://bugs.openjdk.org/browse/JDK-8260528): Clean glass-gtk sizing and positioning code

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx pull/367/head:pull/367` \
`$ git checkout pull/367`

Update a local copy of the PR: \
`$ git checkout pull/367` \
`$ git pull https://git.openjdk.org/jfx pull/367/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 367`

View PR using the GUI difftool: \
`$ git pr show -t 367`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/367.diff">https://git.openjdk.org/jfx/pull/367.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
This does look like a much more manageable approach.

One thing to be aware of from a bookkeeping point of view is that a JBS issues is resolved by a single PR. Once a PR has been integrated for a given JBS bug ID, that bug ID cannot be reused.

This means that each separate PR will need it's own JBS issue to be filed, even if those enhancements taken together are part of a larger set of improvements. Incremental improvements are fine (and in this case a good way to proceed), but you might give some thought to the title of each such improvement. I wouldn't want to see 5 fixes go in each with the same title of `Simplify and update glass gtk backend`.

**Comment by tsayao** [comment]
It's been pointed out about this
https://stackoverflow.com/questions/49512491/javafx-getting-single-resize-events

My tests point out that this PR causes less sizing events that the current master branch, but I also think this could be improved further.

But, by the nature of X and window managers, window sizes does not account decoration frames, but javafx does (probably mimicking windows behavior). Given this information I probably could reduce further the sizing events, but not make it equivalent to windows.

**Comment by tsayao** [comment]
Changed to WIP to reduce sizing events.

**Comment by tsayao** [comment]
Current Status:

image

**Comment by tsayao** [comment]
Ready to be reviewed.

**Comment by tsayao** [comment]
Changed to WIP while we run some more tests to make sure latest changes are ok.
I'm fixing some residual "extra resize" issues (these issues exists on the current versions, so this makes it better, hopefully).

**Comment by tsayao** [comment]
Looks good now.

**Comment by tsayao** [comment]
Testing:

**master**
master

**tsayao:glass_gtk_new_position_and_size**
branch

`--tests test.robot.javafx.scene.RobotTest` causes some intermittent error but eventually all passes.

**Comment by pankaj-bansal** [comment]
I ran the full test on Ubuntu 20.10 and the results look fine. I do not see any new failure.

**Comment by pankaj-bansal** [comment]
I ran the full test on OL 8.2 and the results look fine.

**Comment by johanvos** [comment]
@tsayao The work in this PR looks really good. If you want to continue with this, I will review it. There are some conflicts but those can easily be solved.

**Comment by tsayao** [comment]
@johanvos I think I can rework it better now.

**Comment by johanvos** [comment]
> @johanvos I think I can rework it better now.

Do you mean you want to close this PR and create a new one? That's fine -- let me know if you need some help or a first review even before it's ready.

**Comment by tsayao** [comment]
@johanvos Yes, I have started working on it at
https://github.com/tsayao/jfx/tree/clean_glass_gtk

**Comment by tsayao** [comment]
Closed in favor of #915

**Pull request closed without merging**
