### PR TITLE
8314484: Update Gradle to 8.4

### PR DESCRIPTION
**Pull request by arapte**
Upgrade gradle to version 8.4.
It also includes a change for adding task dependency for windows platform that was missed in [JDK-8314486](https://bugs.openjdk.org/browse/JDK-8314486)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8314484](https://bugs.openjdk.org/browse/JDK-8314484): Update Gradle to 8.4 (**Bug** - P3)

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Johan Vos](https://openjdk.org/census#jvos) (@johanvos - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1257/head:pull/1257` \
`$ git checkout pull/1257`

Update a local copy of the PR: \
`$ git checkout pull/1257` \
`$ git pull https://git.openjdk.org/jfx.git pull/1257/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1257`

View PR using the GUI difftool: \
`$ git pr show -t 1257`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1257.diff">https://git.openjdk.org/jfx/pull/1257.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1257#issuecomment-1755972189)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
@johanvos or @tiainen can one of you be the second reviewer?

/reviewers 2

**Review by kevinrushforth — APPROVED** [review]
Looks good. I tested on Windows and confirm that it produces the same artifacts as the current build.

**Review by johanvos — APPROVED** [review]
tested on Ubuntu 22.04: all good.

**Pull request closed without merging**
