### PR TITLE
8212088: Missing copyright notices for property files

### PR DESCRIPTION
**Pull request by kevinrushforth**
This PR adds missing copyright header blocks for several properties files, script files, and textual data files (e.g., fxml, css) that do not have them. Where feasible, all non-trivial textual files in the repo should have a proper copyright header.

## Notes to Reviewers

* This PR is targeted to the `jfx17` branch.
* There are two commits that can be reviewed separately, if you  prefer. The first covers most of the files, and adds a copyright header with a GPL v2 + classpath license. The second is for the `apps/samples` only, which adds a copyright header with a BSD-style license.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8212088](https://bugs.openjdk.java.net/browse/JDK-8212088): Missing copyright notices for property files

### Reviewers
 * [Johan Vos](https://openjdk.java.net/census#jvos) (@johanvos - **Reviewer**)
 * [Ambarish Rapte](https://openjdk.java.net/census#arapte) (@arapte - **Reviewer**)
 * [Ajit Ghaisas](https://openjdk.java.net/census#aghaisas) (@aghaisas - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/591/head:pull/591` \
`$ git checkout pull/591`

Update a local copy of the PR: \
`$ git checkout pull/591` \
`$ git pull https://git.openjdk.java.net/jfx pull/591/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 591`

View PR using the GUI difftool: \
`$ git pr show -t 591`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/591.diff">https://git.openjdk.java.net/jfx/pull/591.diff</a>

</details>

### CODE REVIEW

**Comment by johanvos** [comment]
Is there a reason why the samples have a BSD license while the others have GPL + CPE? (not that I'm against BSD, just wondering)

**Comment by kevinrushforth** [comment]
Yes. All of JavaFX is licensed under GPL except for the sample applications under `apps/samples`, which are licensed under BSD (`apps/scenebuilder` was similarly licensed under BSD before it was removed from the repo).

**Comment by kevinrushforth** [comment]
I should add, that the JDK samples are similarly licensed under BSD, so JavaFX followed suit (the JavaFX samples are bundled with the JDK samples in JDK 8).

**Review by johanvos — APPROVED** [review]

**Review by arapte — APPROVED** [review]
Looks good to me.

**Review by aghaisas — APPROVED** [review]

**Pull request closed without merging**
