### PR TITLE
8245284: Update to 610.1 version of WebKit

### PR DESCRIPTION
**Pull request by arun-Joseph**
Update JavaFX WebKit to GTK WebKit 2.28 (610.1)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8245284](https://bugs.openjdk.java.net/browse/JDK-8245284): Update to 610.1 version of WebKit

### Reviewers
 * Kevin Rushforth ([kcr](@kevinrushforth) - **Reviewer**)
 * Bhawesh Choudhary ([bchoudhary](@bhaweshkc) - Author)
 * Joeri Sykora ([sykora](@tiainen) - Author)

### Contributors
 * Guru Hb `<ghb@openjdk.org>`
 * Bhawesh Choudhary `<bchoudhary@openjdk.org>`

### Download
`$ git fetch https://git.openjdk.java.net/jfx pull/263/head:pull/263`
`$ git checkout pull/263`

### CODE REVIEW

**Comment by kevinrushforth** [comment]
@bhaweshkc @johanvos can you also review this?

**Comment by arun-Joseph** [comment]
/contributor add Bhawesh Choudhary <bhawesh.choudhary@oracle.com>

**Comment by arun-Joseph** [comment]
/contributor remove Bhawesh Choudhary <bhawesh.choudhary@oracle.com>

**Comment by bhaweshkc** [comment]
Checked with various websites on all three platform. Looks good.

**Pull request closed without merging**
