### PR TITLE
8283786: Update to Visual Studio 2022 version 17.1.0 on Windows

### PR DESCRIPTION
**Pull request by kevinrushforth**
This patch updates the compiler to Visual Studio 2022 version 17.1.0 on Windows, in order to match JDK 19 -- see [JDK-8283723](https://bugs.openjdk.java.net/browse/JDK-8283723).

I ran a full build and test, including media and WebKit.

/reviewers 2

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8283786](https://bugs.openjdk.java.net/browse/JDK-8283786): Update to Visual Studio 2022 version 17.1.0 on Windows

### Reviewers
 * [Ambarish Rapte](https://openjdk.java.net/census#arapte) (@arapte - **Reviewer**)
 * [Joeri Sykora](https://openjdk.java.net/census#sykora) (@tiainen - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/766/head:pull/766` \
`$ git checkout pull/766`

Update a local copy of the PR: \
`$ git checkout pull/766` \
`$ git pull https://git.openjdk.java.net/jfx pull/766/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 766`

View PR using the GUI difftool: \
`$ git pr show -t 766`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/766.diff">https://git.openjdk.java.net/jfx/pull/766.diff</a>

</details>

### CODE REVIEW

**Comment by tiainen** [comment]
@kevinrushforth Which versions were chosen for the build tools, redistributables and the CRT? Do we still use the same ones as with Visual Studio 2019?

**Comment by kevinrushforth** [comment]
> Which versions were chosen for the build tools, redistributables and the CRT? Do we still use the same ones as with Visual Studio 2019?

Each version of Visual Studio has its own set of compilers and redistributables. Visual Studio 2022 version 17.1.0 corresponds to VC version `14.31.31103`. The redistributables should be in `redist/x64/Microsoft.VC143.CRT`.

**Review by arapte — APPROVED** [review]
lgtm. Verified build and sanity test.

**Review by tiainen — APPROVED** [review]
Successfully managed to run a build and test with VS 2022 17.1.0.

**Pull request closed without merging**
