### PR TITLE
8338307 : Additional WebKit 619.1 fixes from WebKitGTK 2.44.3

### PR DESCRIPTION
**Pull request by HimaBinduMeda**
Updated additonal fixes from webkit-2.44.3. Verified build on all platforms. No issue seen.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8338307](https://bugs.openjdk.org/browse/JDK-8338307): Additional WebKit 619.1 fixes from WebKitGTK 2.44.3 (**Bug** - P2)

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Joeri Sykora](https://openjdk.org/census#sykora) (@tiainen - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1541/head:pull/1541` \
`$ git checkout pull/1541`

Update a local copy of the PR: \
`$ git checkout pull/1541` \
`$ git pull https://git.openjdk.org/jfx.git pull/1541/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1541`

View PR using the GUI difftool: \
`$ git pr show -t 1541`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1541.diff">https://git.openjdk.org/jfx/pull/1541.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1541#issuecomment-2304823547)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
Reviewers: @kevinrushforth @tiainen 

/reviewers 2

**Review by kevinrushforth — APPROVED** [review]
Looks good. The code changes match those in the upstream `webkitgtk-2.44.3` tag. I did a build and sanity test. All good.

**Review by tiainen — APPROVED** [review]
Builds and tests were successful on our infrastructure.

**Pull request closed without merging**
