### PR TITLE
8331748: Update libxml2 to 2.12.6

### PR DESCRIPTION
**Pull request by HimaBinduMeda**
Updated libxml to v2.12.6. Verified build and sanity testing on all platforms. No issue seen

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8331748](https://bugs.openjdk.org/browse/JDK-8331748): Update libxml2 to 2.12.6 (**Bug** - P2)

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Joeri Sykora](https://openjdk.org/census#sykora) (@tiainen - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1453/head:pull/1453` \
`$ git checkout pull/1453`

Update a local copy of the PR: \
`$ git checkout pull/1453` \
`$ git pull https://git.openjdk.org/jfx.git pull/1453/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1453`

View PR using the GUI difftool: \
`$ git pr show -t 1453`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1453.diff">https://git.openjdk.org/jfx/pull/1453.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1453#issuecomment-2109316470)

### CODE REVIEW

**Comment by johanvos** [comment]
@tiainen can you do a build/review?

**Comment by kevinrushforth** [comment]
Reviewers: @tiainen @kevinrushforth 

/reviewers 2

**Review by tiainen — APPROVED** [review]
All tests are green here too.

**Pull request closed without merging**
