### PR TITLE
8325075: Enable -Werror for javadoc to fail on any warnings

### PR DESCRIPTION
**Pull request by kevinrushforth**
Now that the last of the javadoc warnings are fixed or suppressed, it is time to enable `-Werror` so that new javadoc warnings don't creep into our code base. The GHA run was successful.

You can see the `-Werror` doing its job in the following GHA workflow run on my [bad-8325075-javadoc-werror](https://github.com/kevinrushforth/jfx/tree/bad-8325075-javadoc-werror) branch, which has the patch from this PR applied on a base without Andy's fix for the last of the javadoc warnings:

https://github.com/kevinrushforth/jfx/actions/runs/8159524643/job/22304043414

That build fails with the expected error:

```
2024-03-05T16:23:29.6264357Z /home/runner/work/jfx/jfx/jfx/modules/javafx.web/src/main/java/javafx/scene/web/WebErrorEvent.java:125: warning: no comment
2024-03-05T16:23:29.6265947Z     private final String message;
2024-03-05T16:23:29.6266448Z                          ^
2024-03-05T16:23:29.6267675Z /home/runner/work/jfx/jfx/jfx/modules/javafx.web/src/main/java/javafx/scene/web/WebEvent.java:80: warning: no comment
2024-03-05T16:23:29.6269004Z     private final T data;
2024-03-05T16:23:29.6269667Z                     ^
2024-03-05T16:23:31.7938955Z error: warnings found and -Werror specified
2024-03-05T16:23:31.7939652Z Problems generating Javadoc.
2024-03-05T16:23:31.7940244Z 1 error
2024-03-05T16:23:31.7940590Z 91 warnings
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8325075](https://bugs.openjdk.org/browse/JDK-8325075): Enable -Werror for javadoc to fail on any warnings (**Bug** - P4)

### Reviewers
 * [Andy Goryachev](https://openjdk.org/census#angorya) (@andy-goryachev-oracle - **Reviewer**)
 * [Johan Vos](https://openjdk.org/census#jvos) (@johanvos - **Reviewer**) 🔄 Re-review required (review applies to [42a329dd](https://git.openjdk.org/jfx/pull/1390/files/42a329ddcbe1eeb3722b06998856fc6934b317cd))

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1390/head:pull/1390` \
`$ git checkout pull/1390`

Update a local copy of the PR: \
`$ git checkout pull/1390` \
`$ git pull https://git.openjdk.org/jfx.git pull/1390/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1390`

View PR using the GUI difftool: \
`$ git pr show -t 1390`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1390.diff">https://git.openjdk.org/jfx/pull/1390.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1390#issuecomment-1979212496)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
Reviewer: @andy-goryachev-oracle 

Others are welcome to review as well. I'll wait until tomorrow to integrate it.

**Review by johanvos — APPROVED** [review]
This is major progress. Building works perfect, and with the patch applied to an older state of the repository it fails as expected.
This will enforce us to keep the JavaDoc clean (at least from a syntax point), good work.

**Comment by andy-goryachev-oracle** [comment]
> turn off a single without turning off all errors (which is easy)

yes, this is the exact scenario.  I wouldn't expect this will be a frequent operation - but imagine javadoc team adds a new check that generates a lot of warnings, for example.

**Comment by andy-goryachev-oracle** [comment]
Also worth noting that unfortunately, javadoc in Eclipse seems to work differently, resulting in 137 warnings:

(see JDK-8324783)

```
Description	Resource	Type	Path	Location
Javadoc: Description expected after @return	AudioClip.java	Java Problem	/media/src/main/java/com/sun/media/jfxmedia	line 313
Javadoc: Description expected after @return	D3DContext.java	Java Problem	/graphics/src/main/java/com/sun/prism/d3d	line 76
Javadoc: Description expected after @return	DefaultCancelButtonTestBase.java	Java Problem	/controls/src/test/java/test/javafx/scene/control	line 93
Javadoc: Description expected after @return	DefaultCancelButtonTestBase.java	Java Problem	/controls/src/test/java/test/javafx/scene/control	line 152
Javadoc: Description expected after @return	Direction.java	Java Problem	/graphics/src/main/java/com/sun/javafx/scene/traversal	line 56
Javadoc: Description expected after @return	EmbeddedScene.java	Java Problem	/graphics/src/main/java/com/sun/javafx/tk/quantum	line 225
Javadoc: Description expected after @return	FilterEffect.java	Java Problem	/graphics/src/main/java/com/sun/scenario/effect	line 155
Javadoc: Description expected after @return	GeneralTransform3D.java	Java Problem	/graphics/src/main/java/com/sun/javafx/geom/transform	line 136
Javadoc: Description expected after @return	InputMap.java	Java Problem	/controls/src/main/java/com/sun/javafx/scene/control/inputmap	line 308
Javadoc: Description expected after @return	InputMap.java	Java Problem	/controls/src/main/java/com/sun/javafx/scene/control/inputmap	line 678
Javadoc: Description expected after @return	Logging.java	Java Problem	/base/src/main/java/com/sun/javafx/binding	line 44
Javadoc: Description expected after @return	PickRay.java	Java Problem	/graphics/src/main/java/com/sun/javafx/geom	line 240
Javadoc: Description expected after @return	PluginListener.java	Java Problem	/web/src/main/java/com/sun/webkit/plugin	line 49
Javadoc: Description expected after @return	PropertyReference.java	Java Problem	/base/src/main/java/com/sun/javafx/property	line 96
Javadoc: Description expected after @return	QuantumClipboard.java	Java Problem	/graphics/src/main/java/com/sun/javafx/tk/quantum	line 148
Javadoc: Description expected after @return	QuantumClipboard.java	Java Problem	/graphics/src/main/java/com/sun/javafx/tk/quantum	line 172
Javadoc: Description expected after @return	SkinStub.java	Java Problem	/controls/src/test/java/test/javafx/scene/control	line 81
Javadoc: Description expected after @return	StyleManager.java	Java Problem	/graphics/src/main/java/com/sun/javafx/css	line 1933
Javadoc: Description expected after @return	StyleManager.java	Java Problem	/graphics/src/main/java/com/sun/javafx/css	line 1948
Javadoc: Description expected after @return	TableSkinShim.java	Java Problem	/controls/src/shims/java/javafx/scene/control/skin	line 67
Javadoc: Description expected after @return	TableSkinShim.java	Java Problem	/controls/src/shims/java/javafx/scene/control/skin	line 79
Javadoc: Description expected after @return	TraversalEngine.java	Java Problem	/graphics/src/main/java/com/sun/javafx/scene/traversal	line 136
Javadoc: Invalid param tag name	LinearGradientContext.java	Java Problem	/graphics/src/main/java/com/sun/prism/impl/paint	line 105
Javadoc: Invalid param tag name	RadialGradientContext.java	Java Problem	/graphics/src/main/java/com/sun/prism/impl/paint	line 151
Javadoc: Invalid param tag name	RadialGradientPaintContext.java	Java Problem	/graphics/src/main/java/com/sun/prism/j2d/paint	line 171
Javadoc: Invalid reference	AndroidFontFinder.java	Java Problem	/graphics/src/main/java/com/sun/javafx/font	line 52
Javadoc: Invalid reference	package-info.java	Java Problem	/base/src/main/java/javafx/beans/binding	line 27
Javadoc: Invalid tag	TableViewTest.java	Java Problem	/controls/src/test/java/test/javafx/scene/control	line 868
Javadoc: Invalid tag	TableViewTest.java	Java Problem	/controls/src/test/java/test/javafx/scene/control	line 2055
Javadoc: Malformed reference (missing end space separator)	GradientColorMap.java	Java Problem	/graphics/src/main/java/com/sun/pisces	line 33
Javadoc: Missing #: "applies(Styleable)} method except it also returns"	Selector.java	Java Problem	/graphics/src/main/java/javafx/css	line 119
Javadoc: Missing #: "close()"	PickResultChooser.java	Java Problem	/graphics/src/main/java/com/sun/javafx/scene/input	line 108
Javadoc: Missing #: "Effect.filter()} operation and it is queried for"	RenderState.java	Java Problem	/graphics/src/main/java/com/sun/scenario/effect/impl/state	line 34
Javadoc: Missing #: "getSourceRegion(Rectangle, Rectangle, Rectangle)} method."	EffectPeer.java	Java Problem	/graphics/src/main/java/com/sun/scenario/effect/impl	line 205
Javadoc: Missing #: "getTextureCoordinates(float[],float,float,float,float,Rectangle,BaseTransform)}."	EffectPeer.java	Java Problem	/graphics/src/main/java/com/sun/scenario/effect/impl	line 277
Javadoc: Missing #: "managed()} method and support for sharing"	BaseResourcePool.java	Java Problem	/graphics/src/main/java/com/sun/prism/impl	line 32
Javadoc: Missing #: "managed()} method will only indicate the amount of the resource"	ResourcePool.java	Java Problem	/graphics/src/main/java/com/sun/prism/impl	line 37
Javadoc: Missing #: "max()}"	ResourcePool.java	Java Problem	/graphics/src/main/java/com/sun/prism/impl	line 34
Javadoc: Missing #: "max()} method, larger than the amount"	ResourcePool.java	Java Problem	/graphics/src/main/java/com/sun/prism/impl	line 131
Javadoc: Missing #: "max()} method, larger than the amount returned by the"	ResourcePool.java	Java Problem	/graphics/src/main/java/com/sun/prism/impl	line 110
Javadoc: Missing #: "max()} method."	ResourcePool.java	Java Problem	/graphics/src/main/java/com/sun/prism/impl	line 121
Javadoc: Missing #: "origTarget()} method, and may change over time."	ResourcePool.java	Java Problem	/graphics/src/main/java/com/sun/prism/impl	line 111
Javadoc: Missing #: "origTarget()} method."	ResourcePool.java	Java Problem	/graphics/src/main/java/com/sun/prism/impl	line 132
Javadoc: Missing #: "Path2D(Shape, BaseTransform) Path2D}"	Path2D.java	Java Problem	/graphics/src/main/java/com/sun/javafx/geom	line 1995
Javadoc: Missing #: "Platform.exit()}."	Util.java	Java Problem	/systemTests-test/java/test/util	line 381
Javadoc: Missing #: "setCompositeRule(int), PiscesRenderer.setComposite(int, float)"	RendererBase.java	Java Problem	/graphics/src/main/java/com/sun/pisces	line 57
Javadoc: Missing #: "setCompositeRule(int), setComposite(int, float)"	RendererBase.java	Java Problem	/graphics/src/main/java/com/sun/pisces	line 44
Javadoc: Missing #: "setCompositeRule(int), setComposite(int, float)"	RendererBase.java	Java Problem	/graphics/src/main/java/com/sun/pisces	line 50
Javadoc: Missing #: "target()} method will return"	ResourcePool.java	Java Problem	/graphics/src/main/java/com/sun/prism/impl	line 38
Javadoc: Missing #: "used()}"	ResourcePool.java	Java Problem	/graphics/src/main/java/com/sun/prism/impl	line 92
Javadoc: Missing #: "used()} and {@link max()}"	ResourcePool.java	Java Problem	/graphics/src/main/java/com/sun/prism/impl	line 34
Javadoc: Missing closing brace for inline tag	GlassRobot.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui	line 168
Javadoc: Missing closing brace for inline tag	GlassRobot.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui	line 168
Javadoc: Missing closing brace for inline tag	ListView.java	Java Problem	/controls/src/main/java/javafx/scene/control	line 165
Javadoc: Missing closing brace for inline tag	Path2D.java	Java Problem	/graphics/src/main/java/com/sun/javafx/geom	line 811
Javadoc: Missing closing brace for inline tag	Path2D.java	Java Problem	/graphics/src/main/java/com/sun/javafx/geom	line 913
Javadoc: Missing closing brace for inline tag	PhongMaterial.java	Java Problem	/graphics/src/main/java/javafx/scene/paint	line 405
Javadoc: Missing closing brace for inline tag	TableView.java	Java Problem	/controls/src/main/java/javafx/scene/control	line 275
Javadoc: Missing closing brace for inline tag	TreeTableView.java	Java Problem	/controls/src/main/java/javafx/scene/control	line 302
Javadoc: Missing closing brace for inline tag	TreeView.java	Java Problem	/controls/src/main/java/javafx/scene/control	line 146
Javadoc: Unexpected tag	Arc2D.java	Java Problem	/graphics/src/main/java/com/sun/javafx/geom	line 202
Javadoc: Unexpected tag	BackgroundPositionConverter.java	Java Problem	/graphics/src/main/java/com/sun/javafx/scene/layout/region	line 86
Javadoc: Unexpected tag	BackgroundSizeConverter.java	Java Problem	/graphics/src/main/java/com/sun/javafx/scene/layout/region	line 83
Javadoc: Unexpected tag	BorderConverter.java	Java Problem	/graphics/src/main/java/javafx/scene/layout	line 196
Javadoc: Unexpected tag	BorderImageSliceConverter.java	Java Problem	/graphics/src/main/java/com/sun/javafx/scene/layout/region	line 76
Javadoc: Unexpected tag	BorderStyleConverter.java	Java Problem	/graphics/src/main/java/com/sun/javafx/scene/layout/region	line 159
Javadoc: Unexpected tag	ClipShapeTest.java	Java Problem	/systemTests-test/java/test/com/sun/marlin	line 91
Javadoc: Unexpected tag	DashedRectTest.java	Java Problem	/systemTests-test/java/test/com/sun/marlin	line 58
Javadoc: Unexpected tag	FXCanvas.java	Java Problem	/swt/src/main/java/javafx/embed/swt	line 275
Javadoc: Unexpected tag	FXCanvas.java	Java Problem	/swt/src/main/java/javafx/embed/swt	line 275
Javadoc: Unexpected tag	HugePolygonClipTest.java	Java Problem	/systemTests-test/java/test/com/sun/marlin	line 68
Javadoc: Unexpected tag	IosApplication.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 51
Javadoc: Unexpected tag	IosApplication.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 61
Javadoc: Unexpected tag	IosApplication.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 75
Javadoc: Unexpected tag	IosApplication.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 83
Javadoc: Unexpected tag	IosApplication.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 91
Javadoc: Unexpected tag	IosApplication.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 99
Javadoc: Unexpected tag	IosApplication.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 116
Javadoc: Unexpected tag	IosApplication.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 129
Javadoc: Unexpected tag	IosApplication.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 147
Javadoc: Unexpected tag	IosApplication.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 161
Javadoc: Unexpected tag	IosClipboardDelegate.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 33
Javadoc: Unexpected tag	IosImageLoader.java	Java Problem	/graphics/src/main/java/com/sun/javafx/iio/ios	line 206
Javadoc: Unexpected tag	IosImageLoader.java	Java Problem	/graphics/src/main/java/com/sun/javafx/iio/ios	line 218
Javadoc: Unexpected tag	IosImageLoaderFactory.java	Java Problem	/graphics/src/main/java/com/sun/javafx/iio/ios	line 57
Javadoc: Unexpected tag	IosImageLoaderFactory.java	Java Problem	/graphics/src/main/java/com/sun/javafx/iio/ios	line 65
Javadoc: Unexpected tag	IosMenuBarDelegate.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 39
Javadoc: Unexpected tag	IosMenuBarDelegate.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 48
Javadoc: Unexpected tag	IosMenuBarDelegate.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 57
Javadoc: Unexpected tag	IosMenuBarDelegate.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 66
Javadoc: Unexpected tag	IosMenuDelegate.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 40
Javadoc: Unexpected tag	IosMenuDelegate.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 49
Javadoc: Unexpected tag	IosMenuDelegate.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 58
Javadoc: Unexpected tag	IosMenuDelegate.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 67
Javadoc: Unexpected tag	IosMenuDelegate.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 76
Javadoc: Unexpected tag	IosMenuDelegate.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 85
Javadoc: Unexpected tag	IosMenuDelegate.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 94
Javadoc: Unexpected tag	IosMenuDelegate.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 103
Javadoc: Unexpected tag	IosMenuDelegate.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 112
Javadoc: Unexpected tag	IosMenuDelegate.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 121
Javadoc: Unexpected tag	IosMenuDelegate.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 130
Javadoc: Unexpected tag	IosMenuDelegate.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 139
Javadoc: Unexpected tag	IosPlatformFactory.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 37
Javadoc: Unexpected tag	IosPlatformFactory.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 45
Javadoc: Unexpected tag	IosPlatformFactory.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 53
Javadoc: Unexpected tag	IosPlatformFactory.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 61
Javadoc: Unexpected tag	IosPlatformFactory.java	Java Problem	/graphics/src/main/java/com/sun/glass/ui/ios	line 69
Javadoc: Unexpected tag	Line2D.java	Java Problem	/graphics/src/main/java/com/sun/javafx/geom	line 133
Javadoc: Unexpected tag	Line2D.java	Java Problem	/graphics/src/main/java/com/sun/javafx/geom	line 139
Javadoc: Unexpected tag	Line2D.java	Java Problem	/graphics/src/main/java/com/sun/javafx/geom	line 145
Javadoc: Unexpected tag	Line2D.java	Java Problem	/graphics/src/main/java/com/sun/javafx/geom	line 151
Javadoc: Unexpected tag	ListViewSkin.java	Java Problem	/controls/src/main/java/javafx/scene/control/skin	line 451
Javadoc: Unexpected tag	LocalStorageAccessTest.java	Java Problem	/systemTests-test/java/test/com/sun/webkit	line 40
Javadoc: Unexpected tag	MainThreadTest.java	Java Problem	/systemTests-test/java/test/com/sun/webkit	line 37
Javadoc: Unexpected tag	PNTMeshVertexBufferLengthTest.java	Java Problem	/systemTests-test/java/test/com/sun/prism/impl	line 62
Javadoc: Unexpected tag	Path2D.java	Java Problem	/graphics/src/main/java/com/sun/javafx/geom	line 1432
Javadoc: Unexpected tag	Path2D.java	Java Problem	/graphics/src/main/java/com/sun/javafx/geom	line 1473
Javadoc: Unexpected tag	Path2DGrowTest.java	Java Problem	/graphics/src/test/java/test/com/sun/javafx/geom	line 34
Javadoc: Unexpected tag	Platform.java	Java Problem	/graphics/src/main/java/javafx/application	line 108
Javadoc: Unexpected tag	PseudoClassImpl.java	Java Problem	/graphics/src/main/java/com/sun/javafx/css	line 39
Javadoc: Unexpected tag	PulseReceiver.java	Java Problem	/graphics/src/main/java/com/sun/scenario/animation/shared	line 42
Javadoc: Unexpected tag	QPathTest.java	Java Problem	/systemTests-test/java/test/com/sun/marlin	line 62
Javadoc: Unexpected tag	QuadCurve2D.java	Java Problem	/graphics/src/main/java/com/sun/javafx/geom	line 138
Javadoc: Unexpected tag	Rectangle.java	Java Problem	/3DViewer/src/main/java/com/javafx/experiments/utils3d/geom	line 661
Javadoc: Unexpected tag	Rectangle.java	Java Problem	/graphics/src/main/java/com/sun/javafx/geom	line 639
Javadoc: Unexpected tag	RepeatStructConverter.java	Java Problem	/graphics/src/main/java/com/sun/javafx/scene/layout/region	line 66
Javadoc: Unexpected tag	ScaleX0Test.java	Java Problem	/systemTests-test/java/test/com/sun/marlin	line 63
Javadoc: Unexpected tag	Shape.java	Java Problem	/graphics/src/main/java/com/sun/javafx/geom	line 982
Javadoc: Unexpected tag	ShapeCacheTest.java	Java Problem	/systemTests-test/java/test/com/sun/prism/impl/ps	line 58
Javadoc: Unexpected tag	TableViewSkin.java	Java Problem	/controls/src/main/java/javafx/scene/control/skin	line 205
Javadoc: Unexpected tag	TestNodeBase.java	Java Problem	/graphics/src/test/java/test/com/sun/javafx/css	line 253
Javadoc: Unexpected tag	TreeTableViewSkin.java	Java Problem	/controls/src/main/java/javafx/scene/control/skin	line 256
Javadoc: Unexpected tag	TriangleMesh.java	Java Problem	/graphics/src/main/java/javafx/scene/shape	line 854
Javadoc: Unexpected tag	Window.java	Java Problem	/graphics/src/main/java/javafx/stage	line 821
Javadoc: Unexpected text	Node.java	Java Problem	/graphics/src/main/java/javafx/scene	line 1175
Javadoc: Unexpected text	Node.java	Java Problem	/graphics/src/main/java/javafx/scene	line 1235
Javadoc: Unexpected text	Node.java	Java Problem	/graphics/src/main/java/javafx/scene	line 1275
```

**Comment by kevinrushforth** [comment]
> Also worth noting that unfortunately, javadoc in Eclipse seems to work differently, resulting in 137 warnings:

Odd. Most of these are due to the fact that Eclipse is running javadoc on all public classes, not just the ones that we export as public API. But filtering out all of the com.sun.* classes, Eclipse is still complaining about a few things in the publicly exported classes. I'd guess this to be an Eclipse problem, but we can discuss that in JDK-8324783. It's unrelated to this PR.

**Comment by kevinrushforth** [comment]
> > turn off a single without turning off all errors (which is easy)
> 
> yes, this is the exact scenario. I wouldn't expect this will be a frequent operation - but imagine javadoc team adds a new check that generates a lot of warnings, for example.

For this case, I think seeing the warnings, but locally disabling the `-Werror` would be ideal, but I'll still check.

**Comment by kevinrushforth** [comment]
I added a gradle property to suppress `javadoc -Werror`. To do this:

```
gradle -PDOC_WERROR=false javadoc
```

**Review by andy-goryachev-oracle — APPROVED** [review]
works as designed on macOS, with and without -PDOC_WERROR=false, with a simple `gradle javadoc` command as well as the full build

```
(rm -rf ./build ; gradle clean sdk apps javadoc 2>&1) | tee ~/`date +"build-%Y-%m%d-%H%M%S"`.log
```

**Pull request closed without merging**
