### PR TITLE
8301022: Video distortion is observed while playing youtube video

### PR DESCRIPTION
**Pull request by jaybhaskar**
Issue: current update is breaking the rendering of media controls on youtube video playback
           For the Webkit Gtk platform, the layout class name is returned as AdwaitaLayoutTraits
           which is incompatible with the JAVA platform.
Solution: Use mediaControlsAdwaitaJavaScript and mediaControlsAdwaitaUserAgentStyleSheet
                which is compatible with RenderThemeJava. 
Test: After the fix, open youtube.com and play any video, mouse hover on the video area, control should come up.
         Without the fix, open youtube.com and play any video, mouse hover on the video area, and the control 
          should come up overlapping with each other.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8301022](https://bugs.openjdk.org/browse/JDK-8301022): Video distortion is observed while playing youtube video

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Hima Bindu Meda](https://openjdk.org/census#hmeda) (@HimaBinduMeda - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx pull/1045/head:pull/1045` \
`$ git checkout pull/1045`

Update a local copy of the PR: \
`$ git checkout pull/1045` \
`$ git pull https://git.openjdk.org/jfx pull/1045/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1045`

View PR using the GUI difftool: \
`$ git pr show -t 1045`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1045.diff">https://git.openjdk.org/jfx/pull/1045.diff</a>

</details>

### CODE REVIEW

**Review by kevinrushforth — APPROVED** [review]
Looks good. I tested on Windows and the media controls show up again.

Have you tested on both Mac and Linux?

**Comment by jaybhaskar** [comment]
tested on all platforms window/linux/mac

**Comment by HimaBinduMeda** [comment]
Looks good. Tested on mac and linux. The controls are rendered properly

**Review by HimaBinduMeda — APPROVED** [review]

**Pull request closed without merging**
