### PR TITLE
8263761: Update boot JDK to 16.0.1

### PR DESCRIPTION
**Pull request by kevinrushforth**
This PR updates the boot JDK for JavaFX builds to use JDK 16.0.1. The minimum version of the JDK remains unchanged at JDK 11.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8263761](https://bugs.openjdk.java.net/browse/JDK-8263761): Update boot JDK to 16.0.1

### Reviewers
 * [Ambarish Rapte](https://openjdk.java.net/census#arapte) (@arapte - **Reviewer**)
 * [Joeri Sykora](https://openjdk.java.net/census#sykora) (@tiainen - Author)
 * [Johan Vos](https://openjdk.java.net/census#jvos) (@johanvos - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/507/head:pull/507` \
`$ git checkout pull/507`

Update a local copy of the PR: \
`$ git checkout pull/507` \
`$ git pull https://git.openjdk.java.net/jfx pull/507/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 507`

View PR using the GUI difftool: \
`$ git pr show -t 507`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/507.diff">https://git.openjdk.java.net/jfx/pull/507.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
It looks like we are still seeing occasional failures in `HonorDeveloperSettingsTest` on Linux. I filed [JDK-8267425](https://bugs.openjdk.java.net/browse/JDK-8267425) to track this.

**Comment by arapte** [comment]
Linux build failure is not related to this change, 
failed test: test.javafx.css.HonorDeveloperSettingsTest > testOpacityWithManuallyChangedValueAndInlineStyleIsSetToInlineStyle FAILED
Looks like the fix of #496 is not sufficient.

**Review by arapte — APPROVED** [review]

**Review by tiainen — APPROVED** [review]
Build and test ran successfully on windows, mac and linux.

**Review by johanvos — APPROVED** [review]
+1

**Pull request closed without merging**
