### PR TITLE
8276174: JavaFX build fails on macOS aarch64

### PR DESCRIPTION
**Pull request by andreas-heger**
By changing the value for the clang -arch parameter to "arm64", the jfx project compiles on an apple silicon system. Are there any side effects which I might be missing in this simple solution?

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8276174](https://bugs.openjdk.java.net/browse/JDK-8276174): JavaFX build fails on macOS aarch64

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Johan Vos](https://openjdk.java.net/census#jvos) (@johanvos - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/666/head:pull/666` \
`$ git checkout pull/666`

Update a local copy of the PR: \
`$ git checkout pull/666` \
`$ git pull https://git.openjdk.java.net/jfx pull/666/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 666`

View PR using the GUI difftool: \
`$ git pr show -t 666`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/666.diff">https://git.openjdk.java.net/jfx/pull/666.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
Did you build WebKit and media with this fix? This might be an OK stop gap, but a more permanent solution would probably be to automatically set `TARGET_ARCH` to `arm64` when `OS_ARCH` is set to `aarch64`. 

/reviewers 2

**Comment by andreas-heger** [comment]
@kevinrushforth 
> Did you build WebKit and media with this fix? This might be an OK stop gap, but a more permanent solution would probably be to automatically set `TARGET_ARCH` to `arm64` when `OS_ARCH` is set to `aarch64`.
You are right, WebKit and media did not build with the original fix, so I now changed the build.gradle file to set the `TARGET_ARCH`to `arm64`on Macs with `OS_ARCH`== `aarch64`. All modules can be build now.

**Comment by kevinrushforth** [comment]
Thanks for the confirmation. I'll test it, and either @johanvos or @tiainen will need to do so as well. It will be great to not have to manually set `TARGET_ARCH`.

**Comment by kevinrushforth** [comment]
Btw, I changed the title of the JBS issue to `JavaFX build fails on macOS aarch64`. Can you change the PR title to match?

**Comment by kevinrushforth** [comment]
With this patch I am able to build without setting `TARGET_ARCH`. Everything looks like it is working except that the architecture is still coming up as "x86_64" for the WebKit binaries. This looks like a preexisting problem that might have something to do with my development environment.

@johanvos Do you need to use any special flags today when you build WebKit on M1?

**Comment by johanvos** [comment]
We also pass -PTARGET_ARCH=arm64 when invoking gradlew.
We don't have specific flags that we pass to build webkit, so having the TARGET_ARCH set to arm64 in one way or another should be sufficient.
I'm not sure about the best place for this. When this was done in OpenJDK, the arch-information would be supplied to `configure.sh` and the makefiles would be generated with the correct flags. The build files don't have to be touched.

In our case, we have the configuration + build logic in one file (build.gradle) which is imho a bit more confusing. Therefore, rather than doing configuration-related processing in the build.gradle file, I personally prefer to keep the configuration separately. We also have platform-specific gradle files, but they are used for a mix of configuration and build logic either, so that won't help.

I'm not really against putting this in the build.gradle file though, if that makes building easier for others. But it doesn't improve the readability of that file.

**Comment by kevinrushforth** [comment]
Given the current build structure, it seems better to have this in `build.gradle`. For all other cases, the processor arch of the boot JDK is used as the default target architecture. For macOS it tries to do the same thing, but we need to do a mapping on macOS from aarch64 --> arm64 when passing the flag to the clang compiler since there is otherwise a mismatch.

**Review by kevinrushforth — APPROVED** [review]

**Comment by kevinrushforth** [comment]
> We don't have specific flags that we pass to build webkit, so having the TARGET_ARCH set to arm64 in one way or another should be sufficient.

I'll check my build environment and file a follow-up issue if needed.

**Comment by johanvos** [comment]
I had a look how it is done in the JDK (flags.m4)
```
  if test "x$OPENJDK_TARGET_OS" = xmacosx; then
    if test "x$OPENJDK_TARGET_CPU" = xaarch64; then
      MACHINE_FLAG="$MACHINE_FLAG -arch arm64"
```
The TARGET_CPU is never changed, and the MACHINE_FLAG is the one being passed to the compiler. That looks cleaner to me. 
I would prefer to have a single value of TARGET_CPU that is the same for Linux/AArch64, macOS/AArch64 and win/AArch64, but since we already semantic overloading in build.gradle, I won't object the current change.

**Review by johanvos — APPROVED** [review]
Approved with the comment that I don't think the TARGET_ARCH should be modified in a build script, but since this is the current setup, it is probably the most pragmatic approach.

**Comment by kevinrushforth** [comment]
> The TARGET_CPU is never changed, and the MACHINE_FLAG is the one being passed to the compiler.

This does seem a cleaner approach. I'll file a follow-on issue to track this (which wouldn't just be limited to macOS).

**Comment by kevinrushforth** [comment]
I filed the follow-up issue:

[JDK-8277479](https://bugs.openjdk.java.net/browse/JDK-8277479): JavaFX build should define a new flag and not override TARGET_ARCH

**Comment by kevinrushforth** [comment]
@andreas-heger Once you fix the title of this PR to match the updated JBS title, you can `/integrate` this. Either Johan or I will sponsor it.

**Pull request closed without merging**
