### PR TITLE
8265399: Update to Visual Studio 2019 version 16.9.3

### PR DESCRIPTION
**Pull request by kevinrushforth**
This patch updates the compiler to Visual Studio 2019 version 16.9.3 on Windows, in order to match JDK 17 -- see [JDK-8265371](https://bugs.openjdk.java.net/browse/JDK-8265371).

I ran a full build and test, including media and WebKit.

NOTE: I also have PR #481 out for review to update the Linux gcc compiler. I intend to integrate that one first, at which time I will need to merge `master` into this branch to resolve a trivial merge conflict (the changes are on adjacent lines).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8265399](https://bugs.openjdk.java.net/browse/JDK-8265399): Update to Visual Studio 2019 version 16.9.3

### Reviewers
 * [Ambarish Rapte](https://openjdk.java.net/census#arapte) (@arapte - **Reviewer**)
 * [Joeri Sykora](https://openjdk.java.net/census#sykora) (@tiainen - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/482/head:pull/482` \
`$ git checkout pull/482`

Update a local copy of the PR: \
`$ git checkout pull/482` \
`$ git pull https://git.openjdk.java.net/jfx pull/482/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 482`

View PR using the GUI difftool: \
`$ git pr show -t 482`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/482.diff">https://git.openjdk.java.net/jfx/pull/482.diff</a>

</details>

### CODE REVIEW

**Review by arapte — APPROVED** [review]
Builds successfully on windows.

**Review by arapte — APPROVED** [review]

**Comment by kevinrushforth** [comment]
Pending review from @johanvos or @tiainen

**Review by tiainen — APPROVED** [review]
The build and tests ran fine.

**Pull request closed without merging**
