### PR TITLE
8341164: Update boot JDK to 23

### PR DESCRIPTION
**Pull request by arapte**
Update the boot JDK to version 23. 

Since Gradle 8.9 does not support JDK 23, it is necessary to upgrade Gradle to the latest release, version 8.10.2, which supports JDK 23.
It is advised to upgrade directly to Gradle 8.10.2 rather than 8.10. refer to [the release notes](https://docs.gradle.org/8.10.2/release-notes.html)

No modifications to the Gradle build script are required for upgrading the Gradle version.

/issue add JDK-8341167

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issues
 * [JDK-8341164](https://bugs.openjdk.org/browse/JDK-8341164): Update boot JDK to 23 (**Bug** - P3)
 * [JDK-8341167](https://bugs.openjdk.org/browse/JDK-8341167): Update Gradle to 8.10.2 (**Bug** - P3)

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Joeri Sykora](https://openjdk.org/census#sykora) (@tiainen - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1589/head:pull/1589` \
`$ git checkout pull/1589`

Update a local copy of the PR: \
`$ git checkout pull/1589` \
`$ git pull https://git.openjdk.org/jfx.git pull/1589/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1589`

View PR using the GUI difftool: \
`$ git pr show -t 1589`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1589.diff">https://git.openjdk.org/jfx/pull/1589.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1589#issuecomment-2389196977)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
Reviewers: @kevinrushforth and @tiainen or @johanvos 

/reviewers 2

**Review by kevinrushforth — APPROVED** [review]
Looks good. All tests (including the CI tests you ran) passed.

**Comment by mstr2** [comment]
Gradle should be upgraded with the `wrapper` task (see [Upgrading your build from Gradle 8.x to the latest](https://docs.gradle.org/current/userguide/upgrading_version_8.html)):
```
gradle wrapper --gradle-version 8.10.2
```

Doing this will ensure that `gradlew` and `gradlew.bat` are up-to-date with the latest version, which is not the case for this PR.

**Comment by kevinrushforth** [comment]
> Gradle should be upgraded with the `wrapper` task (see [Upgrading your build from Gradle 8.x to the latest](https://docs.gradle.org/current/userguide/upgrading_version_8.html)):
> 
> ```
> gradle wrapper --gradle-version 8.10.2
> ```

That's generally safest, and is what we do for updating to a major version.

> Doing this will ensure that `gradlew` and `gradlew.bat` are up-to-date with the latest version, which is not the case for this PR.

@arapte Can you check to see if there are any substantive differences this time? I wouldn't expect any for a dot release, but you never know.

**Comment by arapte** [comment]
> Doing this will ensure that gradlew and gradlew.bat are up-to-date with the latest version, which is not the case for this PR.

On a Mac machine, I had executed the command: `sh gradlew wrapper --gradle-version 8.10.2`
It makes two changes to wrapper files, that we don't take.
1. Changes mode for file `gradlew` to 755, but we use 644
2. Changes line endings in `gradlew.bat` file to windows style, but we need unix style

Both these changes had to be reverted.
Please share if you see any other difference.

**Comment by mstr2** [comment]
Running `gradle wrapper --gradle-version 8.10.2 --gradle-distribution-sha256-sum 31c55713e40233a8303827ceb42ca48a47267a0ad4bab9177123121e71524c26` on my Windows machine changes `gradlew` and `gradlew.bat` as follows:

```diff
diff --git a/gradlew b/gradlew
--- a/gradlew	(revision d5432c3e14b06445bc45e34e4aa63ec415c03595)
+++ b/gradlew	(date 1727936286998)
@@ -15,8 +15,6 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #
-# SPDX-License-Identifier: Apache-2.0
-#
 
 ##############################################################################
 #
@@ -57,7 +55,7 @@
 #       Darwin, MinGW, and NonStop.
 #
 #   (3) This script is generated from the Groovy template
-#       https://github.com/gradle/gradle/blob/HEAD/platforms/jvm/plugins-application/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
+#       https://github.com/gradle/gradle/blob/HEAD/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
 #       within the Gradle project.
 #
 #       You can find Gradle at https://github.com/gradle/gradle/.
@@ -86,8 +84,7 @@
 # shellcheck disable=SC2034
 APP_BASE_NAME=${0##*/}
 # Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
-APP_HOME=$( cd -P "${APP_HOME:-./}" > /dev/null && printf '%s
-' "$PWD" ) || exit
+APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit
 
 # Use the maximum available, or set MAX_FD != -1 to use that value.
 MAX_FD=maximum
```

```diff
diff --git a/gradlew.bat b/gradlew.bat
--- a/gradlew.bat	(revision d5432c3e14b06445bc45e34e4aa63ec415c03595)
+++ b/gradlew.bat	(date 1727936287168)
@@ -13,8 +13,6 @@
 @rem See the License for the specific language governing permissions and
 @rem limitations under the License.
 @rem
-@rem SPDX-License-Identifier: Apache-2.0
-@rem
 
 @if "%DEBUG%"=="" @echo off
 @rem ##########################################################################
```

**Review by tiainen — APPROVED** [review]
Builds and tests all ran successfully.

**Comment by arapte** [comment]
> Running `gradle wrapper --gradle-version 8.10.2 --gradle-distribution-sha256-sum 31c55713e40233a8303827ceb42ca48a47267a0ad4bab9177123121e71524c26` on my Windows machine changes `gradlew` and `gradlew.bat` as follows:

This is not occurring on my Windows machine either, wondering about the cause of this difference. May be due to different Gradle version being used. I'm have Gradle 8.9, but unsure of the cause.

**Comment by kevinrushforth** [comment]
I see the same behavior as @arapte (I ran it on macOS). I don't know why @mstr2 is seeing something different, but the difference seems unimportant in any case.

**Pull request closed without merging**
