### PR TITLE
8282099: Cherry-pick WebKit 613.1 stabilization fixes (2)

### PR DESCRIPTION
**Pull request by arapte**
Include additional stabilization fixes of WebKit 613.1
Sanity testing did not show any concerns.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8282099](https://bugs.openjdk.java.net/browse/JDK-8282099): Cherry-pick WebKit 613.1 stabilization fixes (2)

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Johan Vos](https://openjdk.java.net/census#jvos) (@johanvos - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/740/head:pull/740` \
`$ git checkout pull/740`

Update a local copy of the PR: \
`$ git checkout pull/740` \
`$ git pull https://git.openjdk.java.net/jfx pull/740/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 740`

View PR using the GUI difftool: \
`$ git pr show -t 740`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/740.diff">https://git.openjdk.java.net/jfx/pull/740.diff</a>

</details>

### CODE REVIEW

**Review by kevinrushforth — APPROVED** [review]

**Comment by johanvos** [comment]
I notice changes specific to AArch64 and Linux, so I did a testbuild on Linux AArch64 which was successful. Will test the mac/linux/windows regular builds soon.

**Review by johanvos — APPROVED** [review]
Ok on mac/linux/win x86_64 and on linux aarch64

**Pull request closed without merging**
