### PR TITLE
8339508: RenderPerf Test Application

### PR DESCRIPTION
**Pull request by lukostyra**
This PR migrates RenderPerf performance test application from jfx-sandbox metal branch: https://github.com/openjdk/jfx-sandbox/tree/metal/tests/performance/animation/RenderPerfTest/src/renderperf

RenderPerf is a performance test application which draws provided number of "particles" (JFX nodes) on the screen and animates them. After some time (default 10 seconds of testing + warmup) the test automatically closes and reports FPS values. Test was developed as part of Metal backend for performance testing and we decided to integrate it with mainline for any potential further development and fixes.

Command line options for the test:
- `-n` - number of particles to draw, defaults to 1000
- `-t` - name of test to run, defaults to running all tests in random order. Can provide multiple tests, ex. `-t Rectangle Image`
- `-d` - test duration in seconds, defaults to 10. Can be set to 0, which means the test will run infinitely long and end only when user manually closes the stage, mostly useful for stability testing.

Some tests use `duke.png` image provided with this PR. This is an openly available Duke Wave image taken from https://wiki.openjdk.org/display/duke/Gallery and rescaled for test purposes.

PR consists of two commits:
- Base version of RenderPerfTest developed by @karthikpandelu 
- My commit adding `-d` flag and implementing plenty of other fixes as part of [JDK-8331570](https://bugs.openjdk.org/browse/JDK-8331570)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Warning
&nbsp;⚠️ Patch contains a binary file (tests/performance/animation/RenderPerfTest/src/renderperf/duke.png)

### Issues
 * [JDK-8339508](https://bugs.openjdk.org/browse/JDK-8339508): RenderPerf Test Application (**Enhancement** - P4)
 * [JDK-8331570](https://bugs.openjdk.org/browse/JDK-8331570): RenderPerf test: Add infinite test mode for stress-testing scenarios (**Enhancement** - P4)

### Reviewers
 * [Ambarish Rapte](https://openjdk.org/census#arapte) (@arapte - **Reviewer**)
 * [Jayathirth D V](https://openjdk.org/census#jdv) (@jayathirthrao - Author)

### Contributors
 * Karthik P K `<kpk@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1568/head:pull/1568` \
`$ git checkout pull/1568`

Update a local copy of the PR: \
`$ git checkout pull/1568` \
`$ git pull https://git.openjdk.org/jfx.git pull/1568/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1568`

View PR using the GUI difftool: \
`$ git pr show -t 1568`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1568.diff">https://git.openjdk.org/jfx/pull/1568.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1568#issuecomment-2352394959)

### CODE REVIEW

**Comment by lukostyra** [comment]
Since this PR both migrates the base version (JDK-8339508) and adds test duration flag (JDK-8331570) I will link the latter issue as well.

/issue add JDK-8331570

**Comment by kevinrushforth** [comment]
@lukostyra Can you do a `/contributor add @karthikpandelu`?

Also, can you change the fix version of the secondary bug to tbd to address the following warning:

> [JDK-8331570](https://bugs.openjdk.org/browse/JDK-8331570): RenderPerf test: Add infinite test mode for stress-testing scenarios (Bug - P4)(⚠️ The fixVersion in this issue is [internal] but the fixVersion in .jcheck/conf is jfx24, a new backport will be created when this pr is integrated.)

Reviewers: @arapte @jayathirthrao

**Review by arapte — APPROVED** [review]
LGTM

**Review by jayathirthrao — APPROVED** [review]
I did basic testing with different options and everything works fine.
Its good that we are open-sourcing this rendering performance test.
LGTM.

**Pull request closed without merging**
