### PR TITLE
8223375: Remove Netbeans specific files from the source code repository

### PR DESCRIPTION
**Pull request by kevinrushforth**
As discussed in [this message](https://mail.openjdk.java.net/pipermail/openjfx-dev/2020-July/027049.html) on openjfx-dev I propose to remove the old netbeans-specific files from the source repository. They were originally done for NetBeans 8 / FX 8,. They sort of worked (but not well) with FX 9 (still using NB 8), but no longer work at all. The gradle support in the latest Apache NetBeans 12 is already pretty good, with a couple bugs that they need to fix. There is no longer a reason to host these old netbeans project files in our repo.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8223375](https://bugs.openjdk.java.net/browse/JDK-8223375): Remove Netbeans specific files from the source code repository

### Reviewers
 * [Ambarish Rapte](https://openjdk.java.net/census#arapte) (@arapte - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jfx pull/302/head:pull/302`
`$ git checkout pull/302`

### CODE REVIEW

**Comment by kevinrushforth** [comment]
I'll leave this for a few days even if someone approves it sooner, in case there are any concerns raised.

**Comment by kevinrushforth** [comment]
Is there any NetBeans user who wants to review or comment on this?

If not, I'll ask @arapte to review it later this week so I can integrate it.

**Review by arapte — APPROVED** [review]
Looks good to me.

**Pull request closed without merging**
