### PR TITLE
8252192: Update to Visual Studio 2019 version 16.7.2

### PR DESCRIPTION
**Pull request by kevinrushforth**
This patch updates the compiler to Visual Studio 2019 version 16.7.2 on Windows, in order to match JDK 16 -- see [JDK-8253615](https://bugs.openjdk.java.net/browse/JDK-8253615).

I ran a full build and test, including media and WebKit.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8252192](https://bugs.openjdk.java.net/browse/JDK-8252192): Update to Visual Studio 2019 version 16.7.2

### Reviewers
 * [Ambarish Rapte](https://openjdk.java.net/census#arapte) (@arapte - **Reviewer**)
 * [Joeri Sykora](https://openjdk.java.net/census#sykora) (@tiainen - Author)
 * [Johan Vos](https://openjdk.java.net/census#jvos) (@johanvos - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jfx pull/312/head:pull/312`
`$ git checkout pull/312`

### CODE REVIEW

**Review by arapte — APPROVED** [review]
Build and sanity test looks good on my machine(Edit: Win10).

**Comment by kevinrushforth** [comment]
I just merged `master` in order to fix a trivial (and expected) merge conflict following the integration of the gcc 10.2 update.

**Comment by johanvos** [comment]
@tiainen can you build this on our farm?

**Comment by tiainen** [comment]
Yes, I'll run a build against an updated Visual Studio 2019.

**Review by tiainen — APPROVED** [review]
Build and sanity test completed successfully.

**Review by johanvos — APPROVED** [review]

**Review by arapte — APPROVED** [review]

**Comment by ebresie** [comment]
Does the [documentation](https://wiki.openjdk.java.net/display/OpenJFX/Building+OpenJFX) need updating to reflect the change?

**Comment by kevinrushforth** [comment]
Not directly as a result of this PR, since we don't list the particular version of VS 2019 in our docs. However, it does remind me that the [Building OpenJFX](https://wiki.openjdk.java.net/display/OpenJFX/Building+OpenJFX) Wiki page needs updating -- it's out of date since it still mentions VS 2017. I'll fix that.

**Pull request closed without merging**
