### PR TITLE
8225571: Port DND source to use GTK instead of GDK

### PR DESCRIPTION
**Pull request by tsayao**
https://bugs.openjdk.java.net/browse/JDK-8225571

To run tests (on the root of the source tree):
./gradlew apps
java @build/run.args -cp apps/toys/DragDrop/dist/DragDrop.jar dragdrop.DragDropWithControls
java @build/run.args -cp apps/toys/DragDrop/dist/DragDrop.jar dragdrop.DragDropColor

java -Djdk.gtk.version=2 @build/run.args -cp apps/toys/DragDrop/dist/DragDrop.jar dragdrop.DragDropWithControls
java -Djdk.gtk.version=2 @build/run.args -cp apps/toys/DragDrop/dist/DragDrop.jar dragdrop.DragDropColor

## Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

## Issue
[JDK-8225571](https://bugs.openjdk.java.net/browse/JDK-8225571): Port Linux glass drag source (DND) to use gtk instead of gdk

## Approvers
 * Kevin Rushforth ([kcr](@kevinrushforth) - **Reviewer**)
 * pankaj-bansal (no known github.com user name / role)

### CODE REVIEW

**Comment by tsayao** [comment]
I have an OCA.
/covered

**Comment by kevinrushforth** [comment]
@tsayao In your case `/covered` isn't what's needed. You have an OpenJDK ID so should do this instead:

> If you already are an OpenJDK [Author](https://openjdk.java.net/bylaws#author), [Committer](https://openjdk.java.net/bylaws#committer) or [Reviewer](https://openjdk.java.net/bylaws#reviewer), please click [here](https://bugs.openjdk.java.net/secure/CreateIssue.jspa?pid=11300&issuetype=1) to open a new issue so that we can record that fact. Please use "Add GitHub user tsayao" as summary for the issue.

**Comment by tsayao** [comment]
Yes, noticed that while reading the comment again. I have opened an issue. Thanks.

**Comment by kevinrushforth** [comment]
@pankaj-bansal can you review this as well?

**Comment by kevinrushforth** [comment]
Preliminary review was here: [javafxports/openjdk-jfx/pull/490](https://github.com/javafxports/openjdk-jfx/pull/490)

**Comment by tsayao** [comment]
Just a reminder to take a look when time allows.

**Comment by kevinrushforth** [comment]
I'm starting to look at this. I see at least one behavioral difference that will need to be addressed. With the existing implementation, if I drag / drop onto a target that set up to receive the drop, the transfer completes with a transfer mode of `null`. With your patch, the transfer never completes -- the `DRAG_DONE` event is never sent.

This can be most easily seen by running the `DragDropWithControls` app and doing one of the following two things:

1.  Drag from the source rectangle and drop somewhere _other than_ the target rectangle, for example, in the status text box at the bottom.
2. Change the source data format to `HTML` (uncheck `PLAINTEXT`), leaving the target at `PLAINTEXT`, then drag from the source rectangle and drop onto the target rectangle

In addition to the drop not happening, I get the following assertion error on Ubuntu 16.04:

```
(java:22328): Gdk-CRITICAL **: gdk_frame_clock_get_frame_time: assertion 'GDK_IS_FRAME_CLOCK (frame_clock)' failed
```

I'm using the default GTK 3 library.

**Comment by tsayao** [comment]
@kevinrushforth I changed that behaviour. Since the drag does not complete i find it counter-intuitive to send the DRAG_DONE event.

Does it send the event on other platforms? I can test on Windows.

Will look into the assertion error - it does not happen on 18.04.

**Comment by kevinrushforth** [comment]
> Does it send the event on other platforms? I can test on Windows.

Yes, it always sends the `DRAG_DONE` event on all platforms today (I tested it on Mac, Windows, and Linux).

> Will look into the assertion error - it does not happen on 18.04.

It doesn't happen on 19.10 either. Only 16.04 as far as I have tested. I'll also test on Oracle Linux 7.x.

**Comment by kevinrushforth** [comment]
I don't get an assertion error on Oracle Linux 7.7 -- so far only on Ubuntu 16.04. I will resume reviewing once you restore the `DRAG_DONE` behavior.

**Comment by kevinrushforth** [comment]
With your latest patch, which reverts the changes to `GtkDnDClipboard.java`, I now get the DRAG_DONE event, but the following warning printed to the console in the case of a `DRAG_DONE` event with a null transfer mode:

```
GOT A dragExit when dndGesture is null!
```

This is coming from [Scene.java#L2925](https://github.com/openjdk/jfx/blob/master/modules/javafx.graphics/src/main/java/javafx/scene/Scene.java#L2925).

**Comment by tsayao** [comment]
My mistake. I saw that and thought it was from the test app.

Will fix.

**Comment by kevinrushforth** [comment]
All my testing looks good now. I tried both of the programs you listed in the description, as well as `tests/manual/dnd/DndTest.java`, on Ubuntu 16.04, Ubuntu 19.04, and Oracle Linux 7.7. I ran with the default gtk-3 implementation as well as gtk-2.

I'll do a final code review, probably early next week.

This will need a second reviewer.

@pankaj-bansal can you also review this.

**Comment by kevinrushforth** [comment]
@tsayao this is ready for you to integrate. I note that it will only show one reviewer in the commit message; Pankaj did review it, but still needs to associate his GitHub ID with his OpenJDK ID before it will show up (so it will miss being recorded in the commit for this fix).

**Pull request closed without merging**
