### PR TITLE
JDK-8299977 : Update WebKit to 615.1

### PR DESCRIPTION
**Pull request by HimaBinduMeda**
Update JavaFX WebKit to GTK WebKit 2.38 (615.1).

Verified the updated version build, sanity tests and stability.
This does not cause any issues except one unit test failure.
Also, there are some artifacts observed while playing youtube

The above issues are recorded and ignored using below bugs:
[JDK-8300954](https://bugs.openjdk.org/browse/JDK-8300954)
[JDK-8301022](https://bugs.openjdk.org/browse/JDK-8301022)

/contributor add jbhaskar

Note to reviewers:
     The comment in ImageBufferBackend.h is not removed intentionally. This log should not be seen during the testing.Will remove this log before integration.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8299977](https://bugs.openjdk.org/browse/JDK-8299977): Update WebKit to 615.1

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Joeri Sykora](https://openjdk.org/census#sykora) (@tiainen - Author)

### Contributors
 * Jay Bhaskar `<jbhaskar@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx pull/1011/head:pull/1011` \
`$ git checkout pull/1011`

Update a local copy of the PR: \
`$ git checkout pull/1011` \
`$ git pull https://git.openjdk.org/jfx pull/1011/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1011`

View PR using the GUI difftool: \
`$ git pr show -t 1011`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1011.diff">https://git.openjdk.org/jfx/pull/1011.diff</a>

</details>

### CODE REVIEW

**Review by kevinrushforth — APPROVED** [review]
Looks good. I'll re-approve once you remove the comment and print statement from `ImageBufferBackend.h` that you mentioned in the description.

**Review by tiainen — APPROVED** [review]
Building and testing succeeded on linux, mac and windows x86_64.

**Review by kevinrushforth — APPROVED** [review]

**Comment by kevinrushforth** [comment]
@tiainen Can you re-review following Hima's removal of the print statement?

**Review by tiainen — APPROVED** [review]

**Pull request closed without merging**
