### PR TITLE
8267059: Gradle :clean and :apps tasks fail on Windows if ANT_HOME contains spaces

### PR DESCRIPTION
**Pull request by mstr2**
This PR fixes an issue when building OpenJFX on Windows and command-line arguments contain paths with spaces.

The problem is that on Windows, `ant` is invoked via `cmd`, which leads to quotes being interpreted twice. This can be fixed with the option `cmd /s`, which prevents interpreting quotes on the rest of the command line. The result is as if the rest of the command line had been typed verbatim at the command prompt.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8267059](https://bugs.openjdk.java.net/browse/JDK-8267059): Gradle :clean and :apps tasks fail on Windows if ANT_HOME contains spaces

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)
 * @drmarmac (no known github.com user name / role)
 * [Joeri Sykora](https://openjdk.java.net/census#sykora) (@tiainen - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/499/head:pull/499` \
`$ git checkout pull/499`

Update a local copy of the PR: \
`$ git checkout pull/499` \
`$ git pull https://git.openjdk.java.net/jfx pull/499/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 499`

View PR using the GUI difftool: \
`$ git pr show -t 499`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/499.diff">https://git.openjdk.java.net/jfx/pull/499.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
This will need careful testing.

/reviewers 2

**Comment by mstr2** [comment]
I've tested the `:clean` and `:apps` tasks on Windows, Linux, and macOS:

On Windows 10 20H2, `:clean` and `:apps` fail before and succeed after the fix.
On macOS 10.15.1, `:clean` and `:apps` succeed before and after the fix.
On Ubuntu 20.04, `:clean` succeeds before and after the fix. The `:apps` task fails before and after the fix:
```
[javac] Compiling 143 source files to /home/ubuntu/jfx/apps/samples/3DViewer/build/classes
[javac] error: invalid flag: @/home/ubuntu/jfx/build/compile.args
[javac] Usage: javac <options> <source files>
[javac] use --help for a list of possible options
```

**Review by kevinrushforth — APPROVED** [review]
Looks fine. I tested it on Windows with / without spaces in `ANT_HOME` and it does what I would expect. I sanity tested it on Linux.

**Comment by kevinrushforth** [comment]
> On Ubuntu 20.04 ... The :apps task fails before and after the fix

Maybe something with the version of Java you are using? It runs fine my system, and the GitHub actions build is fine.

**Comment by mstr2** [comment]
> > On Ubuntu 20.04 ... The :apps task fails before and after the fix
> 
> Maybe something with the version of Java you are using? It runs fine my system, and the GitHub actions build is fine.

It turns out that I encountered the same issue that was [discussed on the mailing list](https://mail.openjdk.java.net/pipermail/openjfx-dev/2021-August/031470.html).

**Review by drmarmac — APPROVED** [review]
Hi @drmarmac, thanks for making a comment in an OpenJDK project!

All comments and discussions in the OpenJDK Community must be made available under the OpenJDK [Terms of Use](https://openjdk.java.net/legal/tou/). If you already are an OpenJDK [Author](https://openjdk.java.net/bylaws#author), [Committer](https://openjdk.java.net/bylaws#committer) or [Reviewer](https://openjdk.java.net/bylaws#reviewer), please click [here](https://bugs.openjdk.java.net/secure/CreateIssue.jspa?pid=11300&issuetype=1) to open a new issue so that we can record that fact. Please Use "Add GitHub user drmarmac for the summary.

If you are not an OpenJDK Author, Committer or Reviewer, simply check the box below to accept the OpenJDK Terms of Use for your comments.

 - [ ]  I agree to the [OpenJDK Terms of Use](https://openjdk.java.net/legal/tou/) for all comments I make in a project in the [OpenJDK GitHub organization](https://github.com/openjdk).

Your comment will be automatically restored once you have accepted the OpenJDK [Terms of Use](https://openjdk.java.net/legal/tou/).

**Comment by erikj79** [comment]
@drmarmac The issue with accepting the TOU should now have been fixed, so if you click the agree box again, your review comment should be restored.

**Comment by drmarmac** [comment]
@erikj79 thanks, doesn't seem to have worked though.

**Comment by mstr2** [comment]
@kevinrushforth
I think this is a very useful fix that has been tested by three people in the last months (of which only your review counts for Skara). Can you lower the number of required reviews to 1 in order for this PR to move forward to integration?

**Comment by kevinrushforth** [comment]
@johanvos or @tiainen can you comment as to whether you have any concerns with this? It seems a safe fix to me.

**Comment by tiainen** [comment]
I've tested these changes and I can confirm that it works as expected.

**Review by tiainen — APPROVED** [review]

**Pull request closed without merging**
