### PR TITLE
8308307: Update to gcc 12.2.0 on Linux

### PR DESCRIPTION
**Pull request by kevinrushforth**
Update the compiler on Linux to gcc 12.2. This provides the needed C++20 support for the next WebKit update.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8308307](https://bugs.openjdk.org/browse/JDK-8308307): Update to gcc 12.2.0 on Linux

### Reviewers
 * [Ambarish Rapte](https://openjdk.org/census#arapte) (@arapte - **Reviewer**)
 * [Joeri Sykora](https://openjdk.org/census#sykora) (@tiainen - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1141/head:pull/1141` \
`$ git checkout pull/1141`

Update a local copy of the PR: \
`$ git checkout pull/1141` \
`$ git pull https://git.openjdk.org/jfx.git pull/1141/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1141`

View PR using the GUI difftool: \
`$ git pr show -t 1141`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1141.diff">https://git.openjdk.org/jfx/pull/1141.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1141#issuecomment-1559660145)

### CODE REVIEW

**Review by arapte — APPROVED** [review]

**Comment by johanvos** [comment]
I noticed that the devkit files in the OpenJDK project do not support gcc 12.2 yet?
https://github.com/openjdk/jdk/blob/master/make/devkit/Tools.gmk

It would be good if we could use the same devkit tools as the JDK.

**Comment by kevinrushforth** [comment]
Probably this is because the JDK decided to defer the update until JDK 22, but I'll check and let you know what I find.

**Review by tiainen — APPROVED** [review]

**Pull request closed without merging**
