### PR TITLE
8273138: BidirectionalBinding fails to observe changes of invalid properties

### PR DESCRIPTION
**Pull request by mstr2**
This PR fixes a bug that was introduced in #454.

Since this fix might impact the performance considerations in the original PR, I ran a performance benchmark against the previous `ChangeListener`-based implementation, which still shows better performance for the new implementation:

```java
@State(Scope.Benchmark)
public class BindingBenchmark {
    DoubleProperty property1 = new SimpleDoubleProperty();
    DoubleProperty property2 = new SimpleDoubleProperty();

    public BindingBenchmark() {
        property2.bindBidirectional(property1);
    }

    @Benchmark
    public void benchmark() {
        for (int i = 0; i < 10000000; ++i) {
            property1.set((i % 2 == 0) ? 12345.0 : 54321.0);
        }
    }
}
```

| Benchmark | Mode | Cnt | Score | Error | Units |
|-----------|------|-----|-------|-------|--------|
| ChangeListener | thrpt | 5 | 7.463 | 0.040 | ops/s |
| InvalidationListener (fixed) | thrpt | 5 | 15.095 | 0.092 | ops/s |

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8273138](https://bugs.openjdk.java.net/browse/JDK-8273138): BidirectionalBinding fails to observe changes of invalid properties

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Ambarish Rapte](https://openjdk.java.net/census#arapte) (@arapte - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/614/head:pull/614` \
`$ git checkout pull/614`

Update a local copy of the PR: \
`$ git checkout pull/614` \
`$ git pull https://git.openjdk.java.net/jfx pull/614/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 614`

View PR using the GUI difftool: \
`$ git pr show -t 614`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/614.diff">https://git.openjdk.java.net/jfx/pull/614.diff</a>

</details>

### CODE REVIEW

**Comment by mstr2** [comment]
@kevinrushforth Should this be a new JBS ticket, or should we re-open [8264770](https://bugs.openjdk.java.net/browse/JDK-8264770) and associate this PR with it?

**Comment by hjohn** [comment]
This change looks good to me.

**Comment by kevinrushforth** [comment]
> Should this be a new JBS ticket, or should we re-open 8264770 and associate this PR with it?

The latter. We never reopen a bug that was resolved/fixed by a commit in the repo.

**Review by kevinrushforth — APPROVED** [review]
The explanation makes sense, and both the fix and the test look good. I can confirm that the new test fails without the fix and passes with the fix.

**Comment by fthevenet** [comment]
Am I correct in assuming that, as is, this PR is going to be merged into the openJFX 18 only?
If so, because it addresses a regression introduced in jfx 17, we'll want probably want to have this one in 17 as well on day one, if its not too late.

**Comment by mstr2** [comment]
[It seems to be too late.](https://bugs.openjdk.java.net/browse/JDK-8273138?focusedCommentId=14445309&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14445309)

**Comment by fthevenet** [comment]
I see. This is unfortunate though, as this will definitely break some applications in ways potentially difficult to diagnose.

Maybe this won't be too bad if the window until 17.0.1 is small, but still, I'm afraid third party developers not following these discussions might be in for some head scratching.

**Comment by kevinrushforth** [comment]
Yes, it is far too late for 17 (code freeze was more than two weeks ago; GA is tomorrow).

17.0.1 should be out in about 6 weeks, and this is a candidate for backporting.

**Comment by fthevenet** [comment]
OK I see. I didn't realize GA is due for tomorrow already.
I had September 14 in mind as a release date, but realize now that this is the date for OpenJDK.

**Comment by nlisker** [comment]
There's an ongoing discussion about the eager evaluation of invalidation listeners in the [mailing list](http://mail.openjdk.java.net/pipermail/openjfx-dev/2021-September/031801.html). Its conclusion might affect this patch, I didn't look at this one closely.

**Comment by mstr2** [comment]
> There's an ongoing discussion about the eager evaluation of invalidation listeners in the [mailing list](http://mail.openjdk.java.net/pipermail/openjfx-dev/2021-September/031801.html). Its conclusion might affect this patch, I didn't look at this one closely.

The discussion is about whether adding a listener should validate the property. With this fix, both properties are validated in all relevant code paths, so it doesn't matter whether or not any of the properties is validated by adding an invalidation listener.

**Comment by kevinrushforth** [comment]
I think that restoring the existing behavior to fix this regression is important, and needs to be done regardless of what we might do in the future.

**Comment by mstr2** [comment]
> I think that restoring the existing behavior to fix this regression is important, and needs to be done regardless of what we might do in the future.

This PR does that.

**Comment by kevinrushforth** [comment]
> > I think that restoring the existing behavior to fix this regression is important, and needs to be done regardless of what we might do in the future.
> 
> This PR does that.

Indeed it does. My comment was meant in reply to the point @nlisker raised. Sorry for not making that clear.

**Review by arapte — APPROVED** [review]
looks good to me too.

**Pull request closed without merging**
