### PR TITLE
8308306: Update to Xcode 14.3 on macOS

### PR DESCRIPTION
**Pull request by kevinrushforth**
Update the compiler on macOS to Xcode 14.3. In addition to providing the needed C++20 support for the next WebKit update, initial testing by the JDK team shows that this fixes a reproducible builds problem, so it might help address [JDK-8306886](https://bugs.openjdk.org/browse/JDK-8306886).

Xcode 14.3 requires macOS 13 Ventura to build (although it is known to build on macOS 12 Monterey, which might be useful for developer builds). The generated JavaFX code will run on older versions of macOS.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8308306](https://bugs.openjdk.org/browse/JDK-8308306): Update to Xcode 14.3 on macOS

### Reviewers
 * [Ambarish Rapte](https://openjdk.org/census#arapte) (@arapte - **Reviewer**)
 * [Joeri Sykora](https://openjdk.org/census#sykora) (@tiainen - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1140/head:pull/1140` \
`$ git checkout pull/1140`

Update a local copy of the PR: \
`$ git checkout pull/1140` \
`$ git pull https://git.openjdk.org/jfx.git pull/1140/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1140`

View PR using the GUI difftool: \
`$ git pr show -t 1140`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1140.diff">https://git.openjdk.org/jfx/pull/1140.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1140#issuecomment-1559660960)

### CODE REVIEW

**Review by arapte — APPROVED** [review]

**Comment by tiainen** [comment]
Just for clarity, the preferred macos SDK will remain at 11.1: https://github.com/openjdk/jfx/blob/master/buildSrc/mac.gradle#L53?

**Comment by kevinrushforth** [comment]
Thanks for noticing this. Since I always build with the devkit, I forgot to update the preferred SDK property. Xcode 14.3 comes with SDK 13.3, so the default should be updated to that. I do some additional testing and then update this PR.

**Review by arapte — APPROVED** [review]

**Review by tiainen — APPROVED** [review]

**Pull request closed without merging**
