### PR TITLE
8340829: Generated API docs should clearly identify EA builds

### PR DESCRIPTION
**Pull request by kevinrushforth**
This PR modifies the header and footer of the javadoc-generated API docs to add "DRAFT $VER-ea+$BLD" to clearly identify an ea build of the docs, and also to make it clear which build number the docs refer to. This matches was the JDK does. For GA builds, there will be no change to what we generate today. Since I had to add logic to filter the javadoc properties defined in `build.javadoc` to add the DRAFT message if not a GA build, I also changed the properties to not hard-code the major version of JavaFX, thus reducing the duplication.

I ran three builds to test this, an ordinary developer build, an EA build, and a GA build as follows:

#### Developer build

Command line:
```
gradle javadoc
```

Generated docs: https://cr.openjdk.org/~kcr/8340829/javadoc-internal/

#### EA build

Command line:
```
gradle -PPROMOTED_BUILD_NUMBER=98 -PHUDSON_BUILD_NUMBER=1234 -PHUDSON_JOB_NAME=jfx-dev javadoc
```

Generated docs: https://cr.openjdk.org/~kcr/8340829/javadoc-ea/

#### GA build

Command line:
```
gradle -PMILESTONE_FCS=true -PPROMOTED_BUILD_NUMBER=99 -PHUDSON_BUILD_NUMBER=4321 -PHUDSON_JOB_NAME=jfx-dev javadoc
```

Generated docs: https://cr.openjdk.org/~kcr/8340829/javadoc-fcs/

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8340829](https://bugs.openjdk.org/browse/JDK-8340829): Generated API docs should clearly identify EA builds (**Bug** - P3)

### Reviewers
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - no project role)
 * [Ambarish Rapte](https://openjdk.org/census#arapte) (@arapte - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1583/head:pull/1583` \
`$ git checkout pull/1583`

Update a local copy of the PR: \
`$ git checkout pull/1583` \
`$ git pull https://git.openjdk.org/jfx.git pull/1583/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1583`

View PR using the GUI difftool: \
`$ git pr show -t 1583`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1583.diff">https://git.openjdk.org/jfx/pull/1583.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1583#issuecomment-2377984471)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
Reviewers: @arapte @irisclark

**Review by irisclark — APPROVED** [review]
Thanks for aligning the javadoc footer/banner with the generated jdk javadoc.  I'm particularly happy to see the html comment in the footer.

Agree that vertical centering can be investigated later.

**Review by arapte — APPROVED** [review]

**Comment by kevinrushforth** [comment]
I filed [JDK-8341401](https://bugs.openjdk.org/browse/JDK-8341401) to track the vertical centering of the version number in the header.

**Pull request closed without merging**
