### PR TITLE
8324232: KeyEvent.getCode() is null inside JFXPanel

### PR DESCRIPTION
**Pull request by beldenfox**
JavaFX uses a table to map from an AWT integer key code to a JavaFX KeyCode. If AWT provides a code that's not in the table JavaFX attempts to use a KeyCode of null when constructing the KeyEvent which raises an exception.  This PR just checks for null and changes it to KeyCode.UNDEFINED.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8324232](https://bugs.openjdk.org/browse/JDK-8324232): KeyEvent.getCode() is null inside JFXPanel (**Bug** - P4)

### Reviewers
 * [Andy Goryachev](https://openjdk.org/census#angorya) (@andy-goryachev-oracle - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1470/head:pull/1470` \
`$ git checkout pull/1470`

Update a local copy of the PR: \
`$ git checkout pull/1470` \
`$ git pull https://git.openjdk.org/jfx.git pull/1470/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1470`

View PR using the GUI difftool: \
`$ git pr show -t 1470`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1470.diff">https://git.openjdk.org/jfx/pull/1470.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1470#issuecomment-2143539035)

### CODE REVIEW

**Comment by hjohn** [comment]
Which key is it that causes this?  There is a ticket https://bugs.openjdk.org/browse/JDK-8090319 that suggests completing the missing key codes is also an option.

**Comment by beldenfox** [comment]
> Which key is it that causes this? There is a ticket https://bugs.openjdk.org/browse/JDK-8090319 that suggests completing the missing key codes is also an option.

The original bug report was for letter keys on layouts that don't generate Latin characters like Russian or Greek. On Windows AWT handles these keys by assigning a Latin key code (so shortcuts like Ctrl-A continue to work) and separately providing an extended key code based on the Unicode value. On Mac AWT is dropping the ball by not providing a Latin key code.

**Comment by kevinrushforth** [comment]
@andy-goryachev-oracle Can you review this? It looks like a straight-forward fix.

**Comment by andy-goryachev-oracle** [comment]
will do

**Review by andy-goryachev-oracle — APPROVED** [review]
Looks good on macOS 14.5 M1.

**Comment by kevinrushforth** [comment]
@beldenfox I think this is ready for you to integrate; it is a simple enough change that a single reviewer is enough.

**Pull request closed without merging**
