### PR TITLE
8324233: Update JPEG Image Decoding Software to 9f

### PR DESCRIPTION
**Pull request by jayathirthrao**
IJG has released latest version of libjpeg 9f and we need to update our version also match 9f changes.
IJG reference : https://www.ijg.org/

With updated changes both headless and headful tests are green on all platforms.

Also while updating to 9f noticed that many files don't have latest copyright year and comments from previous version updates like 9e, so updated that part also to match 9f version.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8324233](https://bugs.openjdk.org/browse/JDK-8324233): Update JPEG Image Decoding Software to 9f (**Bug** - P3)

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Ambarish Rapte](https://openjdk.org/census#arapte) (@arapte - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1372/head:pull/1372` \
`$ git checkout pull/1372`

Update a local copy of the PR: \
`$ git checkout pull/1372` \
`$ git pull https://git.openjdk.org/jfx.git pull/1372/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1372`

View PR using the GUI difftool: \
`$ git pr show -t 1372`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1372.diff">https://git.openjdk.org/jfx/pull/1372.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1372#issuecomment-1953579205)

### CODE REVIEW

**Review by kevinrushforth — APPROVED** [review]
Looks good. All testing is green.

**Review by arapte — APPROVED** [review]

**Review by kevinrushforth — APPROVED** [review]

**Pull request closed without merging**
