### PR TITLE
8270839: Remove deprecated implementation methods from Scene

### PR DESCRIPTION
**Pull request by kevinrushforth**
This removes following implementation methods in Scene by making them package-scope. They were previously deprecated for removal by [JDK-8270246](https://bugs.openjdk.java.net/browse/JDK-8270246):

```
    public void disposePeer()
    public void enableInputMethodEvents(boolean enable)
    public void processKeyEvent(KeyEvent e) 
```

One of the test harness classes was calling `Scene::processKeyEvent` directly, so I changed it to call it via `SceneHelper`.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8270839](https://bugs.openjdk.java.net/browse/JDK-8270839): Remove deprecated implementation methods from Scene

### Reviewers
 * [Ambarish Rapte](https://openjdk.java.net/census#arapte) (@arapte - **Reviewer**)
 * [Ajit Ghaisas](https://openjdk.java.net/census#aghaisas) (@aghaisas - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/579/head:pull/579` \
`$ git checkout pull/579`

Update a local copy of the PR: \
`$ git checkout pull/579` \
`$ git pull https://git.openjdk.java.net/jfx pull/579/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 579`

View PR using the GUI difftool: \
`$ git pr show -t 579`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/579.diff">https://git.openjdk.java.net/jfx/pull/579.diff</a>

</details>

### CODE REVIEW

**Comment by arapte** [comment]
With this change, two system tests are failing with java.lang.IllegalAccessError that SceneHelper class is not accessible.

test.javafx.scene.web.HTMLEditorTest.checkFontSizeOnSelectAll_ctrl_A
test.javafx.scene.web.HTMLEditorTest.checkFontSizeOnSelectAll_Shift_LeftArrowKey

**Comment by kevinrushforth** [comment]
Good catch. I must not have run the system tests, but only compiled them (that is, ran `gradle test` without the `-PFULL_TEST=true` flag), which is not sufficient in this case. It's a simple one-line addition to the `addExports` file in the system tests project.

**Review by arapte — APPROVED** [review]
Looks good to me.

**Review by aghaisas — APPROVED** [review]

**Pull request closed without merging**
