### PR TITLE
8306328: Update libFFI to 3.4.4

### PR DESCRIPTION
**Pull request by sashamatveev**
- libFFI updated to 3.4.4.
- No additional changes are done to the code.
- Tested on Linux, Windows x64 and macOS x64/aarch64.
- Windows x86 config files are updated, but no build/testing was done for 32-bit.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8306328](https://bugs.openjdk.org/browse/JDK-8306328): Update libFFI to 3.4.4

### Reviewers
 * [Johan Vos](https://openjdk.org/census#jvos) (@johanvos - **Reviewer**)
 * [Ambarish Rapte](https://openjdk.org/census#arapte) (@arapte - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1131/head:pull/1131` \
`$ git checkout pull/1131`

Update a local copy of the PR: \
`$ git checkout pull/1131` \
`$ git pull https://git.openjdk.org/jfx.git pull/1131/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1131`

View PR using the GUI difftool: \
`$ git pr show -t 1131`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1131.diff">https://git.openjdk.org/jfx/pull/1131.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1131#issuecomment-1542887705)

### CODE REVIEW

**Comment by sashamatveev** [comment]
8306328: Update libFFI to 3.4.4 [v2]
- Fixed whitespace issues.

**Comment by sashamatveev** [comment]
8306328: Update libFFI to 3.4.4 [v3]
- Updated libffi.md.

**Comment by johanvos** [comment]
I did some random comparisons between the original changes in libffi and the ones in this PR and all seem to match.
I did a test build and run on MacOS x64, all good.
I believe this code is only used on mac builds?

**Comment by sashamatveev** [comment]
No, this code is used on macOS and Windows.

**Review by johanvos — APPROVED** [review]
I didn't test this on windows, but the changes look good. (tested on mac).
Would be good if another reviewer would test on windows to make sure it works fine there as well.

**Review by arapte — APPROVED** [review]
LGTM, tested on windows-x64.

**Pull request closed without merging**
