### PR TITLE
8345937: Update JUnit to 5.11.3

### PR DESCRIPTION
**Pull request by Maran23**
The JUnit Platform got some updates over the last years, so it is a good idea to update it to the newest version.

That is from `5.8.1` to `5.11.3`.
Affected dependencies:
- `junit.jupiter`
- `junit.platform`
- `opentest4j`

Release notes: https://junit.org/junit5/docs/5.11.3/release-notes/

Note:
I did a handful of CI runs and got a test failure once in `ServiceLifecycleTest`. Not sure yet if related to the update or not.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8345937](https://bugs.openjdk.org/browse/JDK-8345937): Update JUnit to 5.11.3 (**Enhancement** - P4)

### Reviewers
 * [Michael Strauß](https://openjdk.org/census#mstrauss) (@mstr2 - **Reviewer**)
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1662/head:pull/1662` \
`$ git checkout pull/1662`

Update a local copy of the PR: \
`$ git checkout pull/1662` \
`$ git pull https://git.openjdk.org/jfx.git pull/1662/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1662`

View PR using the GUI difftool: \
`$ git pr show -t 1662`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1662.diff">https://git.openjdk.org/jfx/pull/1662.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1662#issuecomment-2532507120)
</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
Because this has third-party and build implications, I need to review it. Since it is a test-only usage (we don't distribute anything from it), we don't need to get new approval as long as the license is unchanged (I'll double-check).

Reviewers: @kevinrushforth @arapte 

/reviewers 2

**Comment by kevinrushforth** [comment]
> got a test failure once in ServiceLifecycleTest. Not sure yet if related to the update or not.

I doubt it. There is at least one test there that is prone to intermittent failures on some (usually slower) systems.

**Review by mstr2 — APPROVED** [review]
Work as expected.

**Comment by kevinrushforth** [comment]
> Because this has third-party and build implications, I need to review it. Since it is a test-only usage (we don't distribute anything from it), we don't need to get new approval as long as the license is unchanged (I'll double-check).

All looks good so far. I fired off a CI test job. Once finished, I'll approve and you can integrate.

**Comment by kevinrushforth** [comment]
The following test consistently fails on macOS and Linux (I haven't tried it on Windows) with JUnit 5.13.1 in our CI and on my local macOS system:

```
$ gradle -PTEST_ONLY=true -PFULL_TEST=true -PUSE_ROBOT=true :systemTests:test --tests SwingNodePlatformExitCrashTest
...
SwingNodePlatformExitCrashTest > executionError FAILED
    org.opentest4j.AssertionFailedError: Exceeded timeout limit of 10000 msec
        at app//test.util.Util.runAndWait(Util.java:168)
        at app//test.util.Util.runAndWait(Util.java:139)
        at app//test.util.Util.shutdown(Util.java:316)
        at app//test.robot.javafx.embed.swing.SwingNodeBase.teardownOnce(SwingNodeBase.java:81)
        at java.base@23/java.lang.reflect.Method.invoke(Method.java:580)
        at java.base@23/java.util.ArrayList.forEach(ArrayList.java:1597)
        at java.base@23/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1117)
        at java.base@23/java.util.ArrayList.forEach(ArrayList.java:1597)
```

**Comment by kevinrushforth** [comment]
Update: I think this is a test bug.

@Maran23 Can you confirm a theory I have? We have a situation where an abstract base class of a test has a static `tearDownOnce` method, annotated with `@AfterAll`. A concrete test class extends the base class and attempts to "override" the static method in the base calss with an `@AfterAll` annotation on a static method of the same name in the subclass. My suspicion is that this used to accidentally work by hiding the method in the parent class in JUnit 5.8 and no longer does.

**Comment by kevinrushforth** [comment]
I'm almost sure that this is the case, given this:

>        at app//test.util.Util.shutdown(Util.java:316)
>        at app//test.robot.javafx.embed.swing.SwingNodeBase.teardownOnce(SwingNodeBase.java:81)

For the test in question, the `Utils::shutDown` method called by `SwingNodeBase.teardownOnce` must be skipped.

It will be an easy test fix. I'll file a follow-up bug for it.

**Comment by kevinrushforth** [comment]
I confirmed my theory about why that test is now failing, and filed a new bug, [JDK-8346222](https://bugs.openjdk.org/browse/JDK-8346222), to track this. PR #1664 is out for review.

I have a CI build out with the patches from both PRs. Once that completes, I'll approve this. It would probably be best to wait until Monday, unless I'm able to integrate PR #1664 is integrated sooner than that (as a simple testbug I will integrate that one without waiting 24 hours if it is approved sooner).

One more thing: I updated the title of the JBS bug to match our usual pattern for third-party updates. Please update the title of your PR to match.

**Review by kevinrushforth — APPROVED** [review]
All good. The combined patch from this PR and #1664 passes in our CI.

**Comment by kevinrushforth** [comment]
As an FYI, the behavior change that exposed the bug in our test was a deliberate change in JUnit 5.11.

https://github.com/junit-team/junit5/issues/3553

Indeed it was the case that before 5.11, a static method annotated with `@BeforeAll` or `@AfterAll` in a subclass would hide the same named method in the superclass, and starting in 5.11, it no longer does.

**Comment by kevinrushforth** [comment]
@Maran23 I integrated the fix for #1664 so you can integrate this now.

**Pull request closed without merging**
