### PR TITLE
8338478: [macos] Crash in CoreText with certain strings using JDK 22 or later

### PR DESCRIPTION
**Pull request by prrace**
The test in the bug report crashes reliably with JDK 22 on retina.
It coincides with an update to the macOS compilers which seem likely to eagerly invalidate the target of a CFRelease on the native CTFontRef.
Adding a ReachabilityFence to prevent the GC from collecting CTFontStrike until after the method has finished using the native fontRef from the strike fixes it.
The same pattern is observed in 3 other methods (although no crash)  and a fence is added there too.

There is an existing test, which is how this problem was found.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8338478](https://bugs.openjdk.org/browse/JDK-8338478): [macos] Crash in CoreText with certain strings using JDK 22 or later (**Bug** - P2)

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Ambarish Rapte](https://openjdk.org/census#arapte) (@arapte - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1537/head:pull/1537` \
`$ git checkout pull/1537`

Update a local copy of the PR: \
`$ git checkout pull/1537` \
`$ git pull https://git.openjdk.org/jfx.git pull/1537/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1537`

View PR using the GUI difftool: \
`$ git pr show -t 1537`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1537.diff">https://git.openjdk.org/jfx/pull/1537.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1537#issuecomment-2294986063)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
Reviewers: @kevinrushforth @arapte 

/reviewers 2

**Review by kevinrushforth — APPROVED** [review]
The code changes look good.

All my testing is as expected: PangoTest fails (crashes) without the fix and passes with the fix on my M1 running macOS 14.5. The CoreTextCrash program attached to the JBS bug crashes without the fix and passes with the fix on both my M1 and on my Intel Mac running macOS 13.6.9.

**Review by arapte — APPROVED** [review]
Fix looks good. The test fails without this change and passes with the fix, tested with intel Mac, Sonoma 14.5

**Pull request closed without merging**
