### PR TITLE
8270107: Open source FXMediaPlayer test app

### PR DESCRIPTION
**Pull request by sashamatveev**
- Added FXMediaPlayer test application.
 - This app uses all media APIs and very handy in verifying media builds during development.
 - It can be compiled and run by running "ant" and "ant run" in tests/manual/media/FXMediaPlayer.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8270107](https://bugs.openjdk.java.net/browse/JDK-8270107): Open source FXMediaPlayer test app

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Johan Vos](https://openjdk.java.net/census#jvos) (@johanvos - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/613/head:pull/613` \
`$ git checkout pull/613`

Update a local copy of the PR: \
`$ git checkout pull/613` \
`$ git pull https://git.openjdk.java.net/jfx pull/613/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 613`

View PR using the GUI difftool: \
`$ git pr show -t 613`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/613.diff">https://git.openjdk.java.net/jfx/pull/613.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
By way of background this is a lightly cleaned up version of a closed-source test program that we are open sourcing in order to facilitate testing various media features.

Even though it is a test program, I'd like a second pair of eyes on it.

/reviewers 2

**Comment by johanvos** [comment]
That's great. I agree a global media sample would be an excellent improvement for testing (regression on) media.
 
I notice there are a number of netbeans-impl files, which is ok for me, unless we want to avoid ide-specific impl files?
It would be nice if this sample can leverage openjfx-global properties, i.e. I see it now has java source level set to 1.9.

Rather than requesting many changes (e.g. bump java version) before it is in the repository, I think it would be good to do some sanity tests on the different platforms and then include it. I plan to do that later this weekend.

**Comment by kevinrushforth** [comment]
I agree with getting it in now (after testing) and then improving it after it is in the repo.

Btw, the `nbproject/` files were derived from those in the `apps/toys/` directory, for example, [apps/toys/Hello/nbproject/](https://github.com/openjdk/jfx/tree/68db44a2c80f420c967c64bb85988178a3cf6d9c/apps/toys/Hello/nbproject), and similarly are used to build using `ant`. So they aren't really IDE files any longer, even though that's where they originated back in the FX 2 time frame.

A good cleanup effort would be to rewrite them to remove the NetBeans project structure, but that would be a larger effort than just this one manual test program.

**Comment by swpalmer** [comment]
> On Aug 28, 2021, at 11:51 AM, Kevin Rushforth ***@***.***> wrote:
> 
> 
> I agree with getting it in now (after testing) and then improving it after it is in the repo.
> 
> Btw, the nbproject/ files were derived from those in the apps/toys/ directory, for example, apps/toys/Hello/nbproject/ <https://github.com/openjdk/jfx/tree/68db44a2c80f420c967c64bb85988178a3cf6d9c/apps/toys/Hello/nbproject>, and similarly are used to build using ant. So they aren't really IDE files any longer, even though that's where they originated back in the FX 2 time frame.
> 
> A good cleanup effort would be to rewrite them to remove the NetBeans project structure, but that would be a larger effort than just this one manual test program.
> 


Would be nice to have part of the cleanup convert projects to Gradle to be consistent with the rest of the project.

Scott

**Review by kevinrushforth — APPROVED** [review]
Looks good. Tested on all three platforms.

**Comment by kevinrushforth** [comment]
@aghaisas or @johanvos can one of you be the second reviewer on this?

**Comment by johanvos** [comment]
I partially tested it, will do the remainder now.

**Review by johanvos — APPROVED** [review]
tested on linux and mac, works great.
Good addition!

**Pull request closed without merging**
