### PR TITLE
8252107: Media pipeline initialization can crash if audio or video bin state change fails

### PR DESCRIPTION
**Pull request by sashamatveev**
https://bugs.openjdk.java.net/browse/JDK-8252107

- Fixed by checking return value of audio/video bin state change and stopping pipeline initialization if error occurred.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8252107](https://bugs.openjdk.java.net/browse/JDK-8252107): Media pipeline initialization can crash if audio or video bin state change fails

### Reviewers
 * Kevin Rushforth ([kcr](@kevinrushforth) - **Reviewer**)
 * Ambarish Rapte ([arapte](@arapte) - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jfx pull/285/head:pull/285`
`$ git checkout pull/285`

### CODE REVIEW

**Comment by kevinrushforth** [comment]
I built and tested it on Linux and it looks good. Have you done a build / test on Mac and Windows as well?

**Comment by kevinrushforth** [comment]
The PR title doesn't match the JBS title. Can you fix it?

**Comment by sashamatveev** [comment]
> I built and tested it on Linux and it looks good. Have you done a build / test on Mac and Windows as well?

Yes, Mac and Windows was tested with all formats.

**Comment by sashamatveev** [comment]
> The PR title doesn't match the JBS title. Can you fix it?

Fixed. It looks like github auto truncate long titles.

**Review by arapte — APPROVED** [review]
Built and tested on Linux.

**Pull request closed without merging**
