### PR TITLE
8274107: Cherry pick GTK WebKit 2.32.4 changes

### PR DESCRIPTION
**Pull request by arapte**
Cherry pick the GTK webkit 2.32.4 changes
https://webkitgtk.org/2021/09/17/webkitgtk2.32.4-released.html

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8274107](https://bugs.openjdk.java.net/browse/JDK-8274107): Cherry pick GTK WebKit 2.32.4 changes

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Johan Vos](https://openjdk.java.net/census#jvos) (@johanvos - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/631/head:pull/631` \
`$ git checkout pull/631`

Update a local copy of the PR: \
`$ git checkout pull/631` \
`$ git pull https://git.openjdk.java.net/jfx pull/631/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 631`

View PR using the GUI difftool: \
`$ git pr show -t 631`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/631.diff">https://git.openjdk.java.net/jfx/pull/631.diff</a>

</details>

### CODE REVIEW

**Review by kevinrushforth — APPROVED** [review]
Looks good. I built and tested it on all platforms.

**Review by johanvos — APPROVED** [review]
build & tests ok on mac(x86_64 and aarch64)/linux/win

**Pull request closed without merging**
