### PR TITLE
8269147: Update GStreamer to version 1.18.4

### PR DESCRIPTION
**Pull request by sashamatveev**
- GStreamer updated to 1.18.4.
 - Tested on all platforms with all formats.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8269147](https://bugs.openjdk.java.net/browse/JDK-8269147): Update GStreamer to version 1.18.4

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Joeri Sykora](https://openjdk.java.net/census#sykora) (@tiainen - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/541/head:pull/541` \
`$ git checkout pull/541`

Update a local copy of the PR: \
`$ git checkout pull/541` \
`$ git pull https://git.openjdk.java.net/jfx pull/541/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 541`

View PR using the GUI difftool: \
`$ git pr show -t 541`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/541.diff">https://git.openjdk.java.net/jfx/pull/541.diff</a>

</details>

### CODE REVIEW

**Comment by johanvos** [comment]
Those changes look reasonable. It seems that mainly windows is impacted. @tiainen can you double-check the static windows builds are ok with those changes?

**Review by kevinrushforth — APPROVED** [review]
The code changes look good. I tested it on all three platforms. No problems.

@tiainen can be the second reviewer on this.

**Review by tiainen — APPROVED** [review]
We've also tested the changes on our build infrastructure and it all worked fine.

**Pull request closed without merging**
