### PR TITLE
8293368: GitHub Workflows security hardening

### PR DESCRIPTION
**Pull request by sashashura**
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or action) is restricted.
It is recommended to have [most strict permissions on the top level](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions) and grant write permissions on [job level](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) case by case.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8293368](https://bugs.openjdk.org/browse/JDK-8293368): GitHub Workflows security hardening

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Ambarish Rapte](https://openjdk.org/census#arapte) (@arapte - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx pull/889/head:pull/889` \
`$ git checkout pull/889`

Update a local copy of the PR: \
`$ git checkout pull/889` \
`$ git pull https://git.openjdk.org/jfx pull/889/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 889`

View PR using the GUI difftool: \
`$ git pr show -t 889`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/889.diff">https://git.openjdk.org/jfx/pull/889.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
This seems worth evaluating. Given that we don't enable workflows in any of the repos of the openjdk organization, the impact of not doing this is limited (the workflow only runs in the context of the user pushing to their own branch), but as long as it doesn't preclude doing anything legitimate, it might be a good idea. I filed a new JBS issue -- [JDK-8293368](https://bugs.openjdk.org/browse/JDK-8293368) -- for this.

@sashashura Please change the title of this PR to:

```
8293368: GitHub Workflows security hardening
```

/reviewers 2

**Review by kevinrushforth — CHANGES_REQUESTED** [review]
@sashashura You need to enable running GHA workflows in your personal fork of the `jfx` repo. Given that you are changing the GHA workflow, we will need to see the results from your run in this PR.

**Comment by sashashura** [comment]
> @sashashura You need to enable running GHA workflows in your personal fork of the `jfx` repo. Given that you are changing the GHA workflow, we will need to see the results from your run in this PR.

https://github.com/sashashura/jfx/actions/runs/2995229526

**Comment by kevinrushforth** [comment]
Your GHA tests look good. Can you merge (_not_ rebase) the current upstream master into your branch? A recent commit that is not currently in your branch also touches `submit.yml` and I'd like to see a run with both fixes (also, since that patch touches adjacent lines, it will be helpful to see the results of the merge before integration).

**Review by kevinrushforth — APPROVED** [review]
Looks good.

**Review by arapte — APPROVED** [review]

**Comment by kevinrushforth** [comment]
@sashashura this is ready for you to `/integrate`

**Comment by sashashura** [comment]
Thanks, I missed that the ball in on my side.

**Pull request closed without merging**
