### PR TITLE
JDK-8236526 : Java does not render Myanmar script correctly

### PR DESCRIPTION
**Pull request by lmkhant**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Errors
&nbsp;⚠️ OCA signatory status must be verified
&nbsp;⚠️ The pull request body must not be empty.

### Download
`$ git fetch https://git.openjdk.java.net/jfx pull/168/head:pull/168`
`$ git checkout pull/168`

### CODE REVIEW

**Comment by kevinrushforth** [comment]
Please read the [CONTRIBUTING](https://github.com/openjdk/jfx/blob/master/CONTRIBUTING.md) guidelines for this project, specifically the [Before submitting a pull request](https://github.com/openjdk/jfx/blob/master/CONTRIBUTING.md#before-submitting-a-pull-request) section.

If you are interested in pursuing this, you will need to file a new bug (you cannot reuse an existing JBS bug ID) and sign the OCA as indicated in the CONTRIBUTING guidelines referred above.

**Comment by MikOfClassX** [comment]
We're not committers but the suggested change from Imkhant is fixing the Myanmar text rendering issue perfectly (tested) and re-aligns JavaFX to the following fix:
https://bugs.openjdk.java.net/browse/JDK-8223558
https://github.com/openjdk/jdk14/blob/master/src/java.desktop/share/classes/sun/font/FontUtilities.java

**Comment by MikOfClassX** [comment]
Here's the relevant bug-id: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8252099

**Comment by kevinrushforth** [comment]
And here is the direct path to the bug in JBS (the above is just a read-only mirror of the bug) -- https://bugs.openjdk.java.net/browse/JDK-8252099

**Comment by MikOfClassX** [comment]
Thanks Kevin!

**Pull request closed without merging**
