### PR TITLE
8251862: Wrong position of Popup windows at the intersection of 2 screens

### PR DESCRIPTION
**Pull request by kevinrushforth**
On Windows platforms with more than one screen, a PopupWindow created for a Stage that straddles two windows will be drawn with an incorrect position and screen scale if the majority of the Stage is on one screen, and the popup is positioned on the other screen. In this case, the Stage is drawn using the screen scale of the screen that most of the window is on, while the popup is drawn using the scale of the screen that it is (typically entirely) on.

The most common way this can happen is when you have two screens of a different scale with the secondary screen on the left or above the primary screen. If you position the Stage such that most of it is still on the primary screen (thus the Stage is drawn using the scale of the primary screen), with a menu, a control with a context menu, or a control with a Tooltip now on the secondary screen, the popup window for the menu or Tooltip will be drawn using the screen scale of the secondary window and thus won't be positioned or sized correctly relative to the menu bar, or control in the main window.

The fix implemented by this PR is to always use the screen of the owner window, including the screen scales, when rendering a popup window. This matches the behavior of native Windows apps, such as Notepad.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8251862](https://bugs.openjdk.org/browse/JDK-8251862): Wrong position of Popup windows at the intersection of 2 screens

### Reviewers
 * [Ajit Ghaisas](https://openjdk.org/census#aghaisas) (@aghaisas - **Reviewer**)
 * [Ambarish Rapte](https://openjdk.org/census#arapte) (@arapte - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx pull/971/head:pull/971` \
`$ git checkout pull/971`

Update a local copy of the PR: \
`$ git checkout pull/971` \
`$ git pull https://git.openjdk.org/jfx pull/971/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 971`

View PR using the GUI difftool: \
`$ git pr show -t 971`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/971.diff">https://git.openjdk.org/jfx/pull/971.diff</a>

</details>

### CODE REVIEW

**Comment by andy-goryachev-oracle** [comment]
Tried PopupControlTest with two monitors on Mac; the secondary non-retina monitor is above the primary (retina).  Most of the window is on top (secondary).  Curiously, the window is shown on both monitors which seems to be a new functionality on Mac (mine is Monterey 12.5.1) - previously it would always show a clipped window on one monitor.

Invoking the content menu popup by right-clicking on the last visible text line on the top monitor, actually expecting the popup to be visible on the top monitor.  It does, however, appear on the primary screen, sharp, while the underlying portion of the application is rendered a bit fuzzy, see the screenshot.

Questions:
- isn't the popup expected to be shown on top where the right click happened?
- should the bottom portion of the application be rendered using retina quality?
- 
Screen Shot 2022-12-07 at 13 52 33

**Comment by kevinrushforth** [comment]
This particular bug and PR is Windows-specific, although it would be helpful to know what happens on Mac.

I tried macOS 12.5.1 and macOS 12.6.1, and by default, windows only show on one screen or the other, so it doesn't look like a new setting. I checked to see whether there is an option to enable windows to span two displays, and there is (uncheck "Displays have separate spaces" in the "Mission Control" panel), but we don't have any special code on macOS to handle this. Anything we do for Mac would be a separate issue.

**Comment by kevinrushforth** [comment]
As a note for reviewers: While testing this I found a few cases where it clamps the position of a popup drawn on the second monitor near the edges to something closer to the middle of the screen. This might be a separate issue (my guess is that it probably is), but be on the look out for anything odd in your testing.

**Comment by arapte** [comment]
I noticed some wrong position of menu popup when tested with 2 external monitors.
I have a monitors configured in portrait mode as:
Screenshot 2022-12-09 145806

Screenshots of some observations:
1. 
Screenshot 2022-12-09 144504
2.
Screenshot 2022-12-09 144624
3.
Screenshot 2022-12-09 145645
4.
Screenshot 2022-12-09 144722

Similar behavior can also be observed if monitors are in landscape mode:
Screenshot 2022-12-09 150231

**Comment by kevinrushforth** [comment]
@arapte Thanks for the additional testing and screenshots. This is similar to what I see, but it is helpful to have the additional configuration to confirm this.

To summarize, this PR fixes the Windows-specific screen scale bug reported in [JDK-8251862](https://bugs.openjdk.org/browse/JDK-8251862) by always taking the screen scales for popups windows from their owner window. This fixes most, but not all of the multi-screen problems when the screen scales are different.

The remaining issues seen in testing are in the code that adjusts the position of the popup to keep it on the same screen as the anchor. It is a separate issue, even though it presents in a similar manner. It is not platform-specific, so we need to test any changes in this code on other platforms.

As a note, I pushed some debugging changes to a new [`test-8251862-multi-screen-popup`](https://github.com/kevinrushforth/jfx/tree/test-8251862-multi-screen-popup) branch. This temporarily adds a system property, `com.sun.javafx.popup.autofix`, to override the autofix logic, which is responsible for keeping popup controls on the same screen. With this set to `false`, popups appear in the correct location, which supports the theory that the remaining problem is in the repositioning code. One exception to this is that the first time a context menu is opened from a TextArea, it is still positioned incorrectly, even when running with `-Dcom.sun.javafx.popup.autofix=false`, so there must be some other code that does a position adjustment besides the two places I modified.

The root cause of this new problem is that the coordinates of the anchor to be adjusted are scaled using the screen that most of the parent window is on (i.e., the "first" screen), while the bounds of the "second" screen that the anchor is on are relative to the scale of that screen. A likely fix for this problem is to adjust the bounds of the screen by the ratio of the two screen scales before comparing the coordinates with the screen bounds, but this might be somewhat tricky.

**Comment by kevinrushforth** [comment]
I filed [JDK-8301386](https://bugs.openjdk.org/browse/JDK-8301386) to track the additional problem in the code that adjusts the position of the popup to keep it on the same screen as the anchor.

**Review by aghaisas — APPROVED** [review]
I confirm that this fixes the reported issue.

**Review by arapte — APPROVED** [review]
LGTM

**Pull request closed without merging**
