### PR TITLE
8325258: Additional WebKit 617.1 fixes from WebKitGTK 2.42.5

### PR DESCRIPTION
**Pull request by HimaBinduMeda**
Ported changes related to webkit-2.42.5. Verified build on all platforms. Sanity testing looks fine.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8325258](https://bugs.openjdk.org/browse/JDK-8325258): Additional WebKit 617.1 fixes from WebKitGTK 2.42.5 (**Bug** - P2)

### Reviewers
 * [Joeri Sykora](https://openjdk.org/census#sykora) (@tiainen - Author)
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1362/head:pull/1362` \
`$ git checkout pull/1362`

Update a local copy of the PR: \
`$ git checkout pull/1362` \
`$ git pull https://git.openjdk.org/jfx.git pull/1362/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1362`

View PR using the GUI difftool: \
`$ git pr show -t 1362`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1362.diff">https://git.openjdk.org/jfx/pull/1362.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1362#issuecomment-1936288894)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
Reviewers: @kevinrushforth and @johanvos or @tiainen 

/reviewers 2

**Review by tiainen — APPROVED** [review]
Builds and tests ran succesfully.

**Review by kevinrushforth — APPROVED** [review]
Looks good. Testing is green.

**Pull request closed without merging**
