### PR TITLE
8316423: [linux] Secondary Stage does not respect Scene's dimensions when shown

### PR DESCRIPTION
**Pull request by tsayao**
The bug on the title happens because `gtk_widget_realize()` was called on the constructor. It creates the internal underlying window  `GdkWindow` and `XWindow` messing the Gtk expected order. It's probably a Mutter change rather than Gtk. But makes sense to not realize it before expected on the gtk/mutter flow.

I moved the code to get the `GdkWindow` to the realize event.

Had to change the background function because it's called before realize.

The initial **Maximized** and **FullScreen** situations are probably a bug on Mutter [filed here](https://gitlab.gnome.org/GNOME/mutter/-/issues/3092).

I could work-around it on this situation, but it would still happen on later focus request.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8316423](https://bugs.openjdk.org/browse/JDK-8316423): [linux] Secondary Stage does not respect Scene's dimensions when shown (**Bug** - P4)

### Reviewers
 * [Lukasz Kostyra](https://openjdk.org/census#lkostyra) (@lukostyra - Committer)
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1249/head:pull/1249` \
`$ git checkout pull/1249`

Update a local copy of the PR: \
`$ git checkout pull/1249` \
`$ git pull https://git.openjdk.org/jfx.git pull/1249/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1249`

View PR using the GUI difftool: \
`$ git pr show -t 1249`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1249.diff">https://git.openjdk.org/jfx/pull/1249.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1249#issuecomment-1738284349)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
@lukostyra Can you also review?

/reviewers 2

**Comment by kevinrushforth** [comment]
> This also fixes [JDK-8316425](https://bugs.openjdk.org/browse/JDK-8316425)

@tsayao Can you add that issue to this PR using the `/issue add 8316425` command?

Also, since both JDK-8316423 and JDK-8316425 are addressed by this bug, please reenable the tests in [StageAttributesTest.java](https://github.com/openjdk/jfx/blob/7b9001dd3dec25b76cca57978db2dd4c4cf2a1b9/tests/system/src/test/java/test/robot/javafx/stage/StageAttributesTest.java) that are skipped on Linux, for example, [this test](https://github.com/openjdk/jfx/blob/7b9001dd3dec25b76cca57978db2dd4c4cf2a1b9/tests/system/src/test/java/test/robot/javafx/stage/StageAttributesTest.java#L251-L254).

**Comment by tsayao** [comment]
It seems just enabling the tests results in failure, but testing manually with the samples provided on the issues work. I will have to take a look.

/issue add 8316425

**Comment by tsayao** [comment]
It seems it does not fix 8316425 yet.
`testIconifiedStageBeforeShow` still fails. Strangely some event is coming to the TOP stage "saying" it's not iconified - but it actually is. If I comment out the bottom stage, the event does not come.

**Comment by tsayao** [comment]
I strongly suspect of what is happening:

`WindowContextTop` constructor calls `glass_gtk_configure_transparency_and_realize` which calls `gtk_widget_realize`.

This is probably creating the underlying gdk window before gtk expects and is messing things up.

**Comment by tsayao** [comment]
Filed a bug on Mutter [here](https://gitlab.gnome.org/GNOME/mutter/-/issues/3092).

**Comment by tsayao** [comment]
Updated the original description.

**Comment by tsayao** [comment]
This pure gtk program also reports:

```
Window is now iconified (minimized).
Window is now de-iconified (unminimized).
Window is now iconified (minimized).
```



```C
#include <gtk/gtk.h>

// Callback function for handling window state changes
void on_window_state_event(GtkWidget *window, GdkEventWindowState *event, gpointer user_data) {
    if (event->changed_mask & GDK_WINDOW_STATE_ICONIFIED) {
        if (event->new_window_state & GDK_WINDOW_STATE_ICONIFIED) {
            g_print("Window is now iconified (minimized).\n");
        } else {
            g_print("Window is now de-iconified (unminimized).\n");
        }
    }
}

int main(int argc, char *argv[]) {
    GtkWidget *window;

    gtk_init(&argc, &argv);

    window = gtk_window_new(GTK_WINDOW_TOPLEVEL);
    gtk_window_set_title(GTK_WINDOW(window), "Iconified Window");
    gtk_window_set_default_size(GTK_WINDOW(window), 400, 300);
    g_signal_connect(G_OBJECT(window), "destroy", G_CALLBACK(gtk_main_quit), NULL);

    // Connect the callback to the window state event
    g_signal_connect(G_OBJECT(window), "window-state-event", G_CALLBACK(on_window_state_event), NULL);

    // Start the window iconified (minimized)
    gtk_window_iconify(GTK_WINDOW(window));

    gtk_widget_show_all(window);

    gtk_main();

    return 0;
}

```

`gcc -o testiconified testiconified.c $(pkg-config --cflags --libs gtk+-3.0)`

I would guess it's some X11 requirement to get window properties or something like that.

**Comment by tsayao** [comment]
Long story short, it fixes [8316423](https://bugs.openjdk.org/browse/JDK-8316423), iconified fails on the test but actually works and the initial maximize and fullscreen not sticking on recent ubuntu versions is probably a bug [filed here](https://gitlab.gnome.org/GNOME/mutter/-/issues/3092).

**Comment by kevinrushforth** [comment]
@lukostyra  Can you also review this?

**Review by lukostyra — APPROVED** [review]
Fix looks good. Tests still fail as expected so they should stay ignored (due to other Linux-related issues) but the issue-attached test app works as intended now and shows proper dimensions.

**Review by kevinrushforth — APPROVED** [review]
Looks good.

**Pull request closed without merging**
