### PR TITLE
8326618 : Replace usage of deprecated method getId() in Thread

### PR DESCRIPTION
**Pull request by AnirvanSarkar**
Replace Thread.currentThread().getId() with Thread.currentThread().threadId()

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8326618](https://bugs.openjdk.org/browse/JDK-8326618): Replace usage of deprecated method getId() in Thread (**Bug** - P4)

### Reviewers
 * [John Hendrikx](https://openjdk.org/census#jhendrikx) (@hjohn - Committer)
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1383/head:pull/1383` \
`$ git checkout pull/1383`

Update a local copy of the PR: \
`$ git checkout pull/1383` \
`$ git pull https://git.openjdk.org/jfx.git pull/1383/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1383`

View PR using the GUI difftool: \
`$ git pr show -t 1383`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1383.diff">https://git.openjdk.org/jfx/pull/1383.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1383#issuecomment-1967310504)

### CODE REVIEW

**Review by hjohn — APPROVED** [review]
Looks okay.  `threadId` was added in JDK 19, but since we're on 21 now that should be fine.

**Comment by kevinrushforth** [comment]
> Looks okay. `threadId` was added in JDK 19, but since we're on 21 now that should be fine.

Exactly. And as I noted in the JBS issue, this fix must not be backported to earlier versions of JavaFX (it would fail to compile anyway, since we use `--release 17` for JavaFX 21 and 22).

**Review by kevinrushforth — APPROVED** [review]

**Pull request closed without merging**
