### PR TITLE
8233747: JVM crash in com.sun.webkit.dom.DocumentImpl.createAttribute

### PR DESCRIPTION
**Pull request by arun-Joseph**
Issue: Native part of WebView throws a DOMException and then, continues executing the rest of the function assuming that value is present. This causes the JVM to crash when retrieving the value.

Fix: Return from the function if exception was raised (code is similar to exception handling in [WebKitLegacy/java/DOM/JavaTreeWalker.cpp](https://github.com/openjdk/jfx/blob/master/modules/javafx.web/src/main/native/Source/WebKitLegacy/java/DOM/JavaTreeWalker.cpp))

This fix also needs to be applied to all function calls in [WebKitLegacy/java/DOM](https://github.com/openjdk/jfx/tree/master/modules/javafx.web/src/main/native/Source/WebKitLegacy/java/DOM) functions which raises DOMError similar to createAttributeImpl().

## Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

## Issue
[JDK-8233747](https://bugs.openjdk.java.net/browse/JDK-8233747): JVM crash in com.sun.webkit.dom.DocumentImpl.createAttribute

## Approvers
 * Kevin Rushforth ([kcr](@kevinrushforth) - **Reviewer**) **Note!** Review applies to 7f6ed5bf7d81f4fc554a2eaa35264f52c2883024
 * Guru Hb ([ghb](@guruhb) - **Reviewer**)

### CODE REVIEW

**Comment by arun-Joseph** [comment]
For calls to `raiseOnDOMError()` with argument of type `ExceptionOr<Ref<T>>`, the returned value is again passed through `WTF::getPtr()`. This doesn't modify the value returned, but removing it will require changing about 40 function calls.

**Comment by arun-Joseph** [comment]
In `createAttributeImpl` function in [JavaDocument.cpp](https://github.com/openjdk/jfx/blob/master/modules/javafx.web/src/main/native/Source/WebKitLegacy/java/DOM/JavaDocument.cpp), the value returned from `raiseOnDOMError` is passed to `WTF::getPtr` function. Now there are two calls to `WTF::getPtr`, one from `raiseOnDOMError` in the return statement and another in `createAttributeImpl`, instead of just one. So, this approach has an unnecessary call to `WTF::getPtr` which, if needed, has to removed at the `createAttributeImpl` end. This doesn't modify the `Attr` object returned because `WTF::getPtr` returns the same pointer when called multiple times.

**Comment by kevinrushforth** [comment]
Thanks for the explanation. It seems fine the way it is, but if you want to file a follow-up issue, that would be fine, too.

**Pull request closed without merging**
