### PR TITLE
8274967: KeyCharacterCombinations for punctuation and symbols fail on non-US keyboards

### PR DESCRIPTION
**Pull request by beldenfox**
After finding the Window virtual key code for a character getKeyCodeForChar was using a mapping table that only works correctly for U.S. English to retrieve the Java key code. This caused getKeyCodeForChar to encode keys differently than the original key event handling machinery.

With this fix the Robot, getKeyCodeForChar, and the code that handles platform key events all agree on how Windows VK codes should map to Java codes.

The manual KeyboardTest app can be used to test this (tests/manual/events). Run the tests by selecting "without keypad combinations" in the second dropdown. This will use a Robot to test KeyCharacterCombinations excluding the numeric keypad (which is a separate issue).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8274967](https://bugs.openjdk.org/browse/JDK-8274967): KeyCharacterCombinations for punctuation and symbols fail on non-US keyboards (**Bug** - P4)

### Reviewers
 * [Andy Goryachev](https://openjdk.org/census#angorya) (@andy-goryachev-oracle - **Reviewer**)
 * [Jose Pereda](https://openjdk.org/census#jpereda) (@jperedadnr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1264/head:pull/1264` \
`$ git checkout pull/1264`

Update a local copy of the PR: \
`$ git checkout pull/1264` \
`$ git pull https://git.openjdk.org/jfx.git pull/1264/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1264`

View PR using the GUI difftool: \
`$ git pr show -t 1264`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1264.diff">https://git.openjdk.org/jfx/pull/1264.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1264#issuecomment-1767122301)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
@andy-goryachev-oracle Can you be the primary reviewer?

/reviewers 2

**Comment by andy-goryachev-oracle** [comment]
Typing \ and Shift-\  on French keyboard, getting

```
KeyEvent{type=KEY_PRESSED, character=, text=*, code=ASTERISK}
KeyEvent{type=KEY_TYPED, character=*, text=, code=UNDEFINED}
KeyEvent{type=KEY_RELEASED, character=, text=*, code=ASTERISK}

KeyEvent{type=KEY_PRESSED, character=, text=, code=SHIFT, shift}
KeyEvent{type=KEY_PRESSED, character=, text=*, code=ASTERISK, shift}
KeyEvent{type=KEY_TYPED, character=µ, text=, code=UNDEFINED, shift}
KeyEvent{type=KEY_RELEASED, character=, text=*, code=ASTERISK, shift}
KeyEvent{type=KEY_RELEASED, character=, text=, code=SHIFT}
```

is this expected?
(I am using Tools -> Keyboard Event Viewer in the Monkey Tester https://github.com/andy-goryachev-oracle/MonkeyTest )

**Comment by beldenfox** [comment]
Yes, that's expected. The \ key on the U.S. layout is in the same position as the * key on the French layout (on Windows).

Mac and Linux both have nice little keyboard viewing tools that you can pull up so you can see how all the keys change as you switch between layouts. I haven't found such a utility for Windows and it gets confusing.

**Review by andy-goryachev-oracle — APPROVED** [review]
🕶 looks good to me

**Comment by andy-goryachev-oracle** [comment]
not sure why it shows READY label with only one reviewer...
cc @kevinrushforth

**Comment by andy-goryachev-oracle** [comment]
(please do not integrate until we get the required # of reviewers.  there seems to be a problem with SCARA bot)

**Comment by kevinrushforth** [comment]
It looks like there is a recently-introduced bug in Skara's handling of the `/reviewers` command. I filed [SKARA-2088](https://bugs.openjdk.org/browse/SKARA-2088) to track it.

**Comment by beldenfox** [comment]
Still looking for another reviewer. This was entered due to a bug in a desktop app, see defold/defold#5102 or defold/defold#5589. Both were closed as dupes of other bugs because the app developers had no way of knowing that KeyCharacterCombinations require per-platform fixes in Glass.

**Comment by kevinrushforth** [comment]
@jperedadnr Would you be able to be the second reviewer?

**Review by jperedadnr — APPROVED** [review]
Looks good!

I've tested this PR on Windows 11 with my Spanish keyboard.

Without the patch from this PR, the KeyboardTest app (without keypad combinations) gives:
```
[Win] Testing 80 keys on Spanish without keypad combinations
Failed: code Delete did not match combination U+007F
Failed: code Quote did not match combination '
Failed: code Quote did not match combination ?
Failed: code Inverted Exclamation Mark did not match combination ¡
Failed: code Inverted Exclamation Mark did not match combination ¿
Failed: code Plus did not match combination +
Failed: code Plus did not match combination *
Failed: code Plus did not match combination ]
Tested 80 keys with 8 failures
```
with the patch:
```
[Win] Testing 80 keys on Spanish without keypad combinations
Tested 80 keys with 0 failures
```

The same goes with US English, German and French (after setting those as local keyboards).

**Pull request closed without merging**
