### PR TITLE
8295962: Reference to State in Task.java is ambiguous when building with JDK 19

### PR DESCRIPTION
**Pull request by kevinrushforth**
This PR replaces all occurrences of `State` with `Worker.State` in `javafx.concurrent.Task`.

The `javafx.concurrent.Task` class implements `javafx.concurrent.Worker` and extends `java.util.concurrent.FutureTask`, which in turn implements `java.util.concurrent.Future`.

`Worker` has a nested `State` enum, which is used in the implementing `Task` class without being qualified -- since `Task` is a `Worker`, we can just say `State` instead of `Worker.State`.

[JDK-8277090](https://bugs.openjdk.org/browse/JDK-8277090) added a nested `State` enum to the `java.util.concurrent.Future` interface in JDK 19, so an unqualified reference to `State` from the `Task` class is now ambiguous when using JDK 19 to build. The javadoc task fails with an error (and the only reason the javac task doesn't is that we use `--release 17`).

With this fix, a local build and test using JDK 19 passes.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295962](https://bugs.openjdk.org/browse/JDK-8295962): Reference to State in Task.java is ambiguous when building with JDK 19

### Reviewers
 * [Andy Goryachev](https://openjdk.org/census#angorya) (@andy-goryachev-oracle - Author)
 * [Ambarish Rapte](https://openjdk.org/census#arapte) (@arapte - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx pull/933/head:pull/933` \
`$ git checkout pull/933`

Update a local copy of the PR: \
`$ git checkout pull/933` \
`$ git pull https://git.openjdk.org/jfx pull/933/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 933`

View PR using the GUI difftool: \
`$ git pr show -t 933`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/933.diff">https://git.openjdk.org/jfx/pull/933.diff</a>

</details>

### CODE REVIEW

**Review by andy-goryachev-oracle — APPROVED** [review]
all instances in Task class

**Comment by andy-goryachev-oracle** [comment]
@kevinrushforth 
I am getting 9 errors:

```
Description	Resource	Location
The type State is ambiguous	AbstractTask.java	line 62
The type State is ambiguous	TaskShim.java	line 52
The type Task.State is ambiguous	TaskCancelTest.java	line 60
The type Task.State is ambiguous	TaskCancelTest.java	line 72
The type Task.State is ambiguous	TaskCancelTest.java	line 93
The type Task.State is ambiguous	TaskCancelTest.java	line 108
The type Task.State is ambiguous	TaskCancelTest.java	line 120
The type Task.State is ambiguous	TaskCancelTest.java	line 139
The type Task.State is ambiguous	TaskSimpleTest.java	line 68

```

**Review by andy-goryachev-oracle — CHANGES_REQUESTED** [review]
see 9 errors.
why do we not see these errors in github actions checks?

edit: pls disregard the question - forgot we are building with 18 in github.

**Comment by kevinrushforth** [comment]
> @kevinrushforth I am getting 9 errors:

Thanks for reporting this, I'll fix them. I think I know why I missed them when I did my test run.

**Comment by kevinrushforth** [comment]
The reason I didn't catch these is that `gradle test` passes when using JDK 19, for the same reason that "gradle sdk" does: we compile classes for all modules except `javafx.swing` and the system tests with `--release 17`. When building the javadocs and when building `javafx.swing` and the system tests, we (necessarily) use `-source 17 -target 17` instead of `--release 17`. I'll bet your Eclipse test run does the same (or maybe doesn't specificy anything relating the target release).

If I temporarily modify my build to use `-source 17 -target 17` for all modules, I also get errors. Conversely, if you add `--release 17` to your Eclipse options, you won't see the error.

I'll still fix those tests to make it more future proof.

**Review by andy-goryachev-oracle — CHANGES_REQUESTED** [review]
please update copyright year in modified tests :-)

**Comment by kevinrushforth** [comment]
> please update copyright year in modified tests :-)

Sure. I generally don't manually update the copyright date (we run a script for that), but since I already did it for `Task.java`, I'll update it for the tests, too.

**Review by andy-goryachev-oracle — APPROVED** [review]
looks good in eclipse with jdk-19

**Review by arapte — APPROVED** [review]
LGTM, tested on Mac.

**Pull request closed without merging**
