### PR TITLE
8274967: KeyCharacterCombinations for punctuation and symbols fail on non-US keyboards

### PR DESCRIPTION
**Pull request by beldenfox**
The code that maps from a Windows virtual key code to a Java key code in `getKeyCodeForChar` did not match the similar code in `ViewContainer::HandleViewKeyEvent`. The OEM keys are assigned to printable punctuation and symbols in ways which vary across layouts and even keyboards. To determine the correct Java key code you have to query the layout to determine the character the key would generate without modifiers and map that character to the key code. `ViewContainer::HandleViewKeyEvent` did this, `getKeyCodeForChar` did not. This PR copies a few snippets of code from `ViewContainer::HandleViewKeyEvent` to make the two algorithms match.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8274967](https://bugs.openjdk.org/browse/JDK-8274967): KeyCharacterCombinations for punctuation and symbols fail on non-US keyboards

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/672/head:pull/672` \
`$ git checkout pull/672`

Update a local copy of the PR: \
`$ git checkout pull/672` \
`$ git pull https://git.openjdk.org/jfx.git pull/672/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 672`

View PR using the GUI difftool: \
`$ git pr show -t 672`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/672.diff">https://git.openjdk.org/jfx/pull/672.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/672#issuecomment-969286166)

### CODE REVIEW

**Comment by pankaj-bansal** [comment]
I tested the testcase attached in JBS and I see some issues with some of the keys with German Keyboard layout

* Failed: key code Dead Acute did not match ´
* Failed: key code Dead Acute did not match ´
* Failed: key code Dead Acute did not match Shift+`
* Failed: key code Dead Acute did not match Shift+`

**Comment by beldenfox** [comment]
Thanks for catching this, I should have investigated dead keys in more detail earlier.

The test case code should exclude dead keys since they're not eligible as shortcuts on Windows. If the Control key is down when a dead key is pressed both Windows and JavaFX just ignore it. If some other modifier is down (say, Alt) Windows will treat it as a dead key and JavaFX should not treat it as a shortcut.

In a perfect world `getKeyCodeForChar` would return `KeyCode.UNDEFINED` for dead keys to disable shortcut processing. But I can't figure out way of detecting that the key is a dead key. `MapVirtualKeyEx` is supposed to tell me that but doesn't. `ToUnicodeEx` would do the job but has side effects in the global keyboard state so it is off-limits. The best I can do is what the code already does and return a non-dead `KeyCode` that will never match the current `KeyEvent`.

**Comment by beldenfox** [comment]
Marking this as DRAFT since this code could be superseded by #694. The review cycles weren't wasted since similar code will re-appear in the PR for [JDK-8278938](https://bugs.openjdk.java.net/browse/JDK-8278938) which fixes the way the Robot code resolves JavaFX KeyCodes.

(And I was wrong when I wrote that `MapVirtualKeyEx` doesn't inform me of dead keys. I must have fumbled my testing. Mea culpa.)

**Pull request closed without merging**
