### PR TITLE
8280840: Update libFFI to 3.4.2

### PR DESCRIPTION
**Pull request by sashamatveev**
LibFFI updated to 3.4.2. No additional changes to our code, libffi code or build system were required. Tested on all platforms.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8280840](https://bugs.openjdk.java.net/browse/JDK-8280840): Update libFFI to 3.4.2

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Joeri Sykora](https://openjdk.java.net/census#sykora) (@tiainen - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/738/head:pull/738` \
`$ git checkout pull/738`

Update a local copy of the PR: \
`$ git checkout pull/738` \
`$ git pull https://git.openjdk.java.net/jfx pull/738/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 738`

View PR using the GUI difftool: \
`$ git pr show -t 738`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/738.diff">https://git.openjdk.java.net/jfx/pull/738.diff</a>

</details>

### CODE REVIEW

**Comment by sashamatveev** [comment]
[v2] - Fixed TAB issue.
[v3] - Fixed space alignment issue in aarch64/ffitarget.h.

**Review by kevinrushforth — APPROVED** [review]
Looks good. Pending a second reviewer.

**Review by tiainen — APPROVED** [review]
Built and tested.

**Pull request closed without merging**
