### PR TITLE
8262366: Update glib to version 2.66.7

### PR DESCRIPTION
**Pull request by sashamatveev**
- GLib was updated to version 2.66.7 and GStreamer to version 1.18.3
 - One bug was discovered in updated GStreamer which was causing deadlock or infinite loop during seek on macOS. See gstsystemclock.c for changes between ifdef GSTREAMER_LITE. Otherwise no changes.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issues
 * [JDK-8262366](https://bugs.openjdk.java.net/browse/JDK-8262366): Update glib to version 2.66.7
 * [JDK-8262365](https://bugs.openjdk.java.net/browse/JDK-8262365): Update GStreamer to version 1.18.3

### Reviewers
 * [Johan Vos](https://openjdk.java.net/census#jvos) (@johanvos - **Reviewer**)
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/447/head:pull/447` \
`$ git checkout pull/447`

Update a local copy of the PR: \
`$ git checkout pull/447` \
`$ git pull https://git.openjdk.java.net/jfx pull/447/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 447`

View PR using the GUI difftool: \
`$ git pr show -t 447`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/447.diff">https://git.openjdk.java.net/jfx/pull/447.diff</a>

</details>

### CODE REVIEW

**Comment by sashamatveev** [comment]
/solves 8262365: Update GStreamer to version 1.18.3

**Comment by kevinrushforth** [comment]
I get a compilation error on Linux:

```
../../../gstreamer-lite/gst-plugins-base/gst-libs/gst/audio/audio-buffer.c: In function 'gst_audio_buffer_map':
../../../gstreamer-lite/gst-plugins-base/gst-libs/gst/audio/audio-buffer.c:158:7: error: implicit declaration of function 'memset' [-Werror=implicit-function-declaration]
  158 |       memset (buffer->map_infos, 0,
      |       ^~~~~~
../../../gstreamer-lite/gst-plugins-base/gst-libs/gst/audio/audio-buffer.c:158:7: warning: incompatible implicit declaration of built-in function 'memset'
../../../gstreamer-lite/gst-plugins-base/gst-libs/gst/audio/audio-buffer.c:26:1: note: include '<string.h>' or provide a declaration of 'memset'
...
cc1: some warnings being treated as errors
Makefile:270: recipe for target 'modules/javafx.media/build/native/linux/Release/obj/gstreamer-lite/gst-plugins-base/gst-libs/gst/audio/audio-buffer.o' failed
make: *** [modules/javafx.media/build/native/linux/Release/obj/gstreamer-lite/gst-plugins-base/gst-libs/gst/audio/audio-buffer.o] Error 1
```

This is with the gcc 10.2 compiler used for production builds.

**Comment by sashamatveev** [comment]
I cannot reproduce build failure on Linux.

**Comment by johanvos** [comment]
It compiles for me (on gcc-9, 10.1 and 10.2) but I can imagine it doesn't compile on all configurations. `memset` is declared in `string.h` and that may or may not be included. 
Running gcc -H shows that on my system, `string.h` is included by `glib-2.0/glib/gtestutils.h` (which is included by `glib-2.0/glib.h`) but on other systems, that might not be the case.
Since this PR introduces `memset` in the `audio-buffer.c` file, I think it is safest to include `string.h` in this file as well, as this removes the dependency on that file to be included indirectly.

**Comment by kevinrushforth** [comment]
Alexander tried it on our CI build machine yesterday and it builds fine there, too. I should add that I was building on a very old Ubuntu 16.04 system.

> Since this PR introduces memset in the audio-buffer.c file, I think it is safest to include string.h in this file as well, as this removes the dependency on that file to be included indirectly.

I was thinking the same thing. There is one more file that should include `<string.h>`: `qtdemux_tags.c` uses `strlen`and fails to compile on my system. With the change to include `string.h` in those two files, the build now passes on my system.

**Comment by kevinrushforth** [comment]
All my testing looks good on all three platforms. I'll take a look at the diffs next.

One thing I did spot is that you need to update `gstreamer.md` and `glib.md` to bump the version numbers.

**Comment by kevinrushforth** [comment]
It now builds for me on my old Linux box. And the changes to the /legal/ files looks good.

One more thing I just thought of: we should do a test build on macOS aarch64. I have no reason to believe that there will be a problem, but worth double-checking.

**Comment by sashamatveev** [comment]
It builds fine on macOS aarch64 and I did minor testing as well. No issues.

**Review by johanvos — APPROVED** [review]

**Review by kevinrushforth — APPROVED** [review]
Looks good.

**Pull request closed without merging**
