### PR TITLE
8283328: Update libxml2 to 2.9.13

### PR DESCRIPTION
**Pull request by HimaBinduMeda**
We currently use libxml2 version 2.9.12. It should be updated to latest stable release, which is version 2.9.13.
The steps to update libxml are documented in UPDATING.txt.
There is compilation issue with the release 2.9.13, as mentioned here: https://gitlab.gnome.org/GNOME/libxml2/-/issues/349.
Updated the code with the changes as per the fix mentioned in above link.

Compiled and verified on Windows, Mac and Linux platforms.
Sanity testing looks fine.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8283328](https://bugs.openjdk.java.net/browse/JDK-8283328): Update libxml2 to 2.9.13

### Reviewers
 * [Johan Vos](https://openjdk.java.net/census#jvos) (@johanvos - **Reviewer**)
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Ambarish Rapte](https://openjdk.java.net/census#arapte) (@arapte - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/764/head:pull/764` \
`$ git checkout pull/764`

Update a local copy of the PR: \
`$ git checkout pull/764` \
`$ git pull https://git.openjdk.java.net/jfx pull/764/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 764`

View PR using the GUI difftool: \
`$ git pr show -t 764`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/764.diff">https://git.openjdk.java.net/jfx/pull/764.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
I'll do testing and a sanity check review tomorrow. Here are three meta issues:

1. As noted in [SKARA-1222](https://bugs.openjdk.java.net/browse/SKARA-1222), your patch introduces a sym-link that is causing jcheck to throw an exception. Given that we do not want any sym-links in the repo anyway, you will need to revert the file in question.
2. Once the above is fixed, you will note that jcheck reports some whitespace errors.
3. You need to update the version in [libxml2.md](https://github.com/openjdk/jfx/blob/f169dde501c58fe107ab6da7f35667efb4992b65/modules/javafx.web/src/main/legal/libxml2.md).

**Comment by kevinrushforth** [comment]
4. I see that the following files were deleted as part of this PR. Was this intentional?
```
D       modules/javafx.web/src/main/native/Source/ThirdParty/libxml/src/AUTHORS
D       modules/javafx.web/src/main/native/Source/ThirdParty/libxml/src/ChangeLog
D       modules/javafx.web/src/main/native/Source/ThirdParty/libxml/src/README
```

**Comment by johanvos** [comment]
This looks good. Just for my understanding: this is the 2.9.13-tagged plus the fix for the issue with xmlValidNormalizeString() with --without-valid-build (https://gitlab.gnome.org/GNOME/libxml2/-/commit/d05317cee5eb2bd35269b7706a8850c6c3097de3) ?
I notice there was a followup patch (https://gitlab.gnome.org/GNOME/libxml2/-/commit/b057239b3f65c8dd9d472fc878214ea4b1d852d3) but that doesn't touch files we have, and since builds are compiling for me, it seems that we are all good now.

**Comment by HimaBinduMeda** [comment]
> 1. As noted in [SKARA-1222](https://bugs.openjdk.java.net/browse/SKARA-1222), your patch introduces a sym-link that is causing jcheck to throw an exception. Given that we do not want any sym-links in the repo anyway, you will need to revert the file in question.

--- Fixed symlinks issue by reverting the file

> 2. Once the above is fixed, you will note that jcheck reports some whitespace errors.

-- Resolved

> 3. You need to update the version in [libxml2.md](https://github.com/openjdk/jfx/blob/f169dde501c58fe107ab6da7f35667efb4992b65/modules/javafx.web/src/main/legal/libxml2.md).

-- Updated

**Comment by HimaBinduMeda** [comment]
> This looks good. Just for my understanding: this is the 2.9.13-tagged plus the fix for the issue with xmlValidNormalizeString() with --without-valid-build (https://gitlab.gnome.org/GNOME/libxml2/-/commit/d05317cee5eb2bd35269b7706a8850c6c3097de3) ?

-- Yes, just this patch is sufficient to resolve compilation error.
> I notice there was a followup patch (https://gitlab.gnome.org/GNOME/libxml2/-/commit/b057239b3f65c8dd9d472fc878214ea4b1d852d3) but that doesn't touch files we have, and since builds are compiling for me, it seems that we are all good now.

-- Yes , the followup patch  is not needed.

**Review by johanvos — APPROVED** [review]
Looks good and works fine on Mac/Linux/Windows

**Comment by HimaBinduMeda** [comment]
> 7\. I see that the following files were deleted as part of this PR. Was this intentional?
> 
> ```
> D       modules/javafx.web/src/main/native/Source/ThirdParty/libxml/src/AUTHORS
> D       modules/javafx.web/src/main/native/Source/ThirdParty/libxml/src/ChangeLog
> D       modules/javafx.web/src/main/native/Source/ThirdParty/libxml/src/README
> ```

-- The above files have been deleted in the release v2.9.13.
Added README.md which contains information regarding Authors,License and libxml project

**Review by kevinrushforth — APPROVED** [review]
Looks good. Tested on all three platforms.

**Review by arapte — APPROVED** [review]
Looks good, tested Mac M1 build and macos sanity check.

**Pull request closed without merging**
