### PR TITLE
8328718: Remove unused imports in javafx.controls

### PR DESCRIPTION
**Pull request by andy-goryachev-oracle**
Using Eclipse IDE to remove unused imports in javafx.controls and update the copyright year to 2024.  Using wildcard for more than 10 static imports.

This is a trivial change, 1 reviewer is probably enough.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8328718](https://bugs.openjdk.org/browse/JDK-8328718): Remove unused imports in javafx.controls (**Bug** - P4)

### Reviewers
 * [Ajit Ghaisas](https://openjdk.org/census#aghaisas) (@aghaisas - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1416/head:pull/1416` \
`$ git checkout pull/1416`

Update a local copy of the PR: \
`$ git checkout pull/1416` \
`$ git pull https://git.openjdk.org/jfx.git pull/1416/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1416`

View PR using the GUI difftool: \
`$ git pr show -t 1416`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1416.diff">https://git.openjdk.org/jfx/pull/1416.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1416#issuecomment-2013394846)

### CODE REVIEW

**Comment by andy-goryachev-oracle** [comment]
@Maran23 @nlisker would you like to review this PR and its relatives?

**Comment by Maran23** [comment]
Sure.
I may also need a little more time, as my free time is somewhat limited. 🙂

**Review by aghaisas — APPROVED** [review]
This cleanup Looks good.

**Pull request closed without merging**
