### PR TITLE
8278980: Update WebKit to 613.1

### PR DESCRIPTION
**Pull request by arapte**
Update JavaFX WebKit to GTK WebKit 2.34 (613.1).

Verified the updated version build, tests run and sanity testing.
This does not cause any issues except a unit test failure `IrresponsiveScriptTest`.
It is recorded and ignored using [JDK-8280421](https://bugs.openjdk.java.net/browse/JDK-8280421)

/contributor add kevinrushforth  
/contributor add aghaisas
/contributor add Jay Bhaskar jay.bhaskar@oracle.com

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278980](https://bugs.openjdk.java.net/browse/JDK-8278980): Update WebKit to 613.1

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Johan Vos](https://openjdk.java.net/census#jvos) (@johanvos - **Reviewer**)
 * [Ajit Ghaisas](https://openjdk.java.net/census#aghaisas) (@aghaisas - **Reviewer**)

### Contributors
 * Ajit Ghaisas `<aghaisas@openjdk.org>`
 * Jay Bhaskar `<jay.bhaskar@oracle.com>`
 * Kevin Rushforth `<kcr@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/723/head:pull/723` \
`$ git checkout pull/723`

Update a local copy of the PR: \
`$ git checkout pull/723` \
`$ git pull https://git.openjdk.java.net/jfx pull/723/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 723`

View PR using the GUI difftool: \
`$ git pr show -t 723`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/723.diff">https://git.openjdk.java.net/jfx/pull/723.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
One other thing to note about this update is that WebKit 613.1 will not compile with Visual Studio 2017 -- it requires VS 2019. This is similar to the previous 612.1 update, [JDK-8268849](https://bugs.openjdk.java.net/browse/JDK-8268849), where a follow-on fix, [JDK-8270479](https://bugs.openjdk.java.net/browse/JDK-8270479), was needed. I filed a similar bug this time:

[JDK-8278983](https://bugs.openjdk.java.net/browse/JDK-8278983): WebKit 613.1 build fails with Visual Studio 2017

but it doesn't seem so straight-forward. We are likely at the point where we need to require VS 2019 to build (I note that WebKit itself has required VS 2019 for about 1.5 years). In order to eventually backport this to JavaFX 11, we will need to solve a long-standing problem when `jlink`ing the JavaFX jmods into a JDK that was built with an earlier version of the Visual Studio compiler than the one used to build JavaFX. I filed the following to track this:

[JDK-8281089](https://bugs.openjdk.java.net/browse/JDK-8281089): JavaFX built with VS2019 and jlinked into JDK 11.x fails to start

**Comment by yososs** [comment]
You may have noticed ...
The change file contains changes that are not related to the WebKit upgrade. 
It looks like you're reverting to an older version.

**Comment by kevinrushforth** [comment]
> The change file contains changes that are not related to the WebKit upgrade.

Thanks for pointing this out! It looks like the patch was applied incorrectly.

@arapte please fix this.

**Comment by arapte** [comment]
> You may have noticed ... The change file contains changes that are not related to the WebKit upgrade. It looks like you're reverting to an older version.

Thanks for pointing it out. It is corrected now. 
Thanks @kevinrushforth for quick fix.

**Review by kevinrushforth — APPROVED** [review]
Testing complete on all platforms. Looks good.

**Review by johanvos — APPROVED** [review]
builds on all platforms, basic tests are ok. We should do an EA release soon after this is merged, so we can have more testers.

**Comment by aghaisas** [comment]
I have tested on macOS and Windows. No new issue observed.

**Review by aghaisas — APPROVED** [review]

**Pull request closed without merging**
