### PR TITLE
8320267: WebView crashes on macOS 11 with WebKit 616.1

### PR DESCRIPTION
**Pull request by kevinrushforth**
With the help of debug build which pinpointed the crash, I found the commit in upstream WebKit core that caused the crash. That commit was subsequently reverted not long after it was initially committed. This reverted commit wasn't in the stabilization branch we picked up for WebKit 616.1. It will be in the next WebKit update, but we need a fix sooner than that.

The proposed fix is to cherry-pick the commit that reverts the problematic commit: https://github.com/WebKit/WebKit/commit/d6d61bb1b76bbac53b403d217428e65a12c4e2e3

I've done an initial sanity test run on all platforms.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8320267](https://bugs.openjdk.org/browse/JDK-8320267): WebView crashes on macOS 11 with WebKit 616.1 (**Bug** - P2)

### Reviewers
 * [Jay Bhaskar](https://openjdk.org/census#jbhaskar) (@jaybhaskar - Committer)
 * [Jose Pereda](https://openjdk.org/census#jpereda) (@jperedadnr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1297/head:pull/1297` \
`$ git checkout pull/1297`

Update a local copy of the PR: \
`$ git checkout pull/1297` \
`$ git pull https://git.openjdk.org/jfx.git pull/1297/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1297`

View PR using the GUI difftool: \
`$ git pr show -t 1297`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1297.diff">https://git.openjdk.org/jfx/pull/1297.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1297#issuecomment-1830736478)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
@jperedadnr Would you be able to test this? My testing shows that it fixes the problem, but confirmation would be helpful.

**Comment by jperedadnr** [comment]
My preliminary tests (using GitHub Actions with a macOS 11 runner, no UI) are green!
Trying to get a final confirmation on a real device.

**Review by jaybhaskar — APPROVED** [review]
Looks good to me

**Review by jperedadnr — APPROVED** [review]
Tested successfully as well on a real device with macOS 11.

**Pull request closed without merging**
