### PR TITLE
JDK-8310681: Update WebKit to 616.1

### PR DESCRIPTION
**Pull request by HimaBinduMeda**
Updated JavaFX Webkit to GTK WebKit 2.40 (616.1).
Verified the updated version build, sanity tests and stability. No issues have been observed.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8310681](https://bugs.openjdk.org/browse/JDK-8310681): Update WebKit to 616.1 (**Bug** - P2)

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Joeri Sykora](https://openjdk.org/census#sykora) (@tiainen - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1180/head:pull/1180` \
`$ git checkout pull/1180`

Update a local copy of the PR: \
`$ git checkout pull/1180` \
`$ git pull https://git.openjdk.org/jfx.git pull/1180/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1180`

View PR using the GUI difftool: \
`$ git pr show -t 1180`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1180.diff">https://git.openjdk.org/jfx/pull/1180.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1180#issuecomment-1644178342)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
I have two questions. Because of the large number of files, I can't use the "diffs" view to add inline comments, so I will add them as general comments.

**Comment by kevinrushforth** [comment]
```
--- a/modules/javafx.web/src/main/native/Source/WebCore/dom/Element.cpp
+++ b/modules/javafx.web/src/main/native/Source/WebCore/dom/Element.cpp
@@ -2295,8 +2295,11 @@ URL Element::absoluteLinkURL() const

     if (linkAttribute.isEmpty())
         return URL();
-
+#if PLATFORM(JAVA)
+    return document().completeURL(linkAttribute);
+#else
     return document().completeURL(stripLeadingAndTrailingHTMLSpaces(linkAttribute));
+#endif
 }

 #if ENABLE(TOUCH_EVENTS)
```

Why did we need to make this change? Will there be any problems as a result of our not stripping leading and trailing spaces?

**Comment by kevinrushforth** [comment]
```
--- a/modules/javafx.web/src/main/native/Source/WebCore/dom/FullscreenManager.cpp
+++ b/modules/javafx.web/src/main/native/Source/WebCore/dom/FullscreenManager.cpp
@@ -389,6 +389,132 @@ void FullscreenManager::exitFullscreen(RefPtr<DeferredPromise>&& promise)
     });
 }

+#if PLATFORM(JAVA)
+void FullscreenManager::exitFullscreen()
+{
...
+}
+
+void FullscreenManager::pushFullscreenElementStack(Element& element)
+{
+    m_fullscreenElementStack.append(&element);
+}
+#endif
```

Is this new code or was it moved / refactored from elsewhere? If new code, what is its purpose, and who is calling it?

**Comment by jaybhaskar** [comment]
> ```
> --- a/modules/javafx.web/src/main/native/Source/WebCore/dom/FullscreenManager.cpp
> +++ b/modules/javafx.web/src/main/native/Source/WebCore/dom/FullscreenManager.cpp
> @@ -389,6 +389,132 @@ void FullscreenManager::exitFullscreen(RefPtr<DeferredPromise>&& promise)
>      });
>  }
> 
> +#if PLATFORM(JAVA)
> +void FullscreenManager::exitFullscreen()
> +{
> ...
> +}
> +
> +void FullscreenManager::pushFullscreenElementStack(Element& element)
> +{
> +    m_fullscreenElementStack.append(&element);
> +}
> +#endif
> ```
> 
> Is this new code or was it moved / refactored from elsewhere? If new code, what is its purpose, and who is calling it?

It was taken from last webkit update, as it was giving undefined reference error for current webkit update.

**Comment by jaybhaskar** [comment]
> ```
> --- a/modules/javafx.web/src/main/native/Source/WebCore/dom/Element.cpp
> +++ b/modules/javafx.web/src/main/native/Source/WebCore/dom/Element.cpp
> @@ -2295,8 +2295,11 @@ URL Element::absoluteLinkURL() const
> 
>      if (linkAttribute.isEmpty())
>          return URL();
> -
> +#if PLATFORM(JAVA)
> +    return document().completeURL(linkAttribute);
> +#else
>      return document().completeURL(stripLeadingAndTrailingHTMLSpaces(linkAttribute));
> +#endif
>  }
> 
>  #if ENABLE(TOUCH_EVENTS)
> ```
> 
> Why did we need to make this change? Will there be any problems as a result of our not stripping leading and trailing spaces?

The code is taken from the WebKit upstream main.

**Comment by kevinrushforth** [comment]
Oh, I see that now. What led me to ask this question was that there is an alternative implementation in `#if PLATFORM(JAVA)`, which implies that we removed the call to `stripLeadingAndTrailingHTMLSpaces` and that it is still present in the upstream.

Given that this code block now matches the upstream, the `if..else..endif` block should simply be replaced with:

```
    return document().completeURL(linkAttribute);
```

removing the `#if PLATFORM(JAVA)` and the entire `#else` block (including the old call to `stripLeadingAndTrailingHTMLSpaces`). Otherwise it will be confusing and possibly lead to merge conflicts later.

**Comment by kevinrushforth** [comment]
You can include this in the next "cherry-pick" update, if you prefer.

**Comment by HimaBinduMeda** [comment]
> You can include this in the next "cherry-pick" update, if you prefer.



> You can include this in the next "cherry-pick" update, if you prefer.

Noted. This change would be included as part of next Cherry-pick update

**Review by kevinrushforth — APPROVED** [review]
Looks good. Testing is green.

**Comment by kevinrushforth** [comment]
@johanvos or @tiainen Can one you be the second reviewer?

**Comment by yososs** [comment]
I found a change to turn off DFGJIT by default, is this a fix for some problem?

modules/javafx.web/src/main/java/com/sun/webkit/WebPage.java

**Comment by johanvos** [comment]
> Oh, I see that now. What led me to ask this question was that there is an alternative implementation in `#if PLATFORM(JAVA)`, which implies that we removed the call to `stripLeadingAndTrailingHTMLSpaces` and that it is still present in the upstream.
> 
> Given that this code block now matches the upstream, the `if..else..endif` block should simply be replaced with:
> 
> ```
>     return document().completeURL(linkAttribute);
> ```
> 
> removing the `#if PLATFORM(JAVA)` and the entire `#else` block (including the old call to `stripLeadingAndTrailingHTMLSpaces`). Otherwise it will be confusing and possibly lead to merge conflicts later.

I agree with this. Is there a reason this can't be done in the current PR?

**Comment by jaybhaskar** [comment]
> I found a change to turn off DFGJIT by default, is this a fix for some problem?
> 
> modules/javafx.web/src/main/java/com/sun/webkit/WebPage.java

The Change is required, as it is making issues with complex js code written for a website.

**Comment by jaybhaskar** [comment]
> absoluteLinkURL

Agree

**Comment by jaybhaskar** [comment]
> > Oh, I see that now. What led me to ask this question was that there is an alternative implementation in `#if PLATFORM(JAVA)`, which implies that we removed the call to `stripLeadingAndTrailingHTMLSpaces` and that it is still present in the upstream.
> > Given that this code block now matches the upstream, the `if..else..endif` block should simply be replaced with:
> > ```
> >     return document().completeURL(linkAttribute);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > removing the `#if PLATFORM(JAVA)` and the entire `#else` block (including the old call to `stripLeadingAndTrailingHTMLSpaces`). Otherwise it will be confusing and possibly lead to merge conflicts later.
> 
> I agree with this. Is there a reason this can't be done in the current PR?

I agree, we will apply the suggestion.

**Comment by HimaBinduMeda** [comment]
> > Oh, I see that now. What led me to ask this question was that there is an alternative implementation in `#if PLATFORM(JAVA)`, which implies that we removed the call to `stripLeadingAndTrailingHTMLSpaces` and that it is still present in the upstream.
> > Given that this code block now matches the upstream, the `if..else..endif` block should simply be replaced with:
> > ```
> >     return document().completeURL(linkAttribute);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > removing the `#if PLATFORM(JAVA)` and the entire `#else` block (including the old call to `stripLeadingAndTrailingHTMLSpaces`). Otherwise it will be confusing and possibly lead to merge conflicts later.
> 
> I agree with this. Is there a reason this can't be done in the current PR?

Pushed the change.

**Review by kevinrushforth — APPROVED** [review]

**Review by tiainen — APPROVED** [review]
After upgrading our version of python from 3.7 to 3.8 all builds and tests completed successfully.

**Pull request closed without merging**
