### PR TITLE
8259864: Cleanup unused Prism files

### PR DESCRIPTION
**Pull request by johanvos**
Fix for JDK-8259864
Remove java and native files that are not used/maintained in prism configurations.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8259864](https://bugs.openjdk.java.net/browse/JDK-8259864): Cleanup unused Prism files

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jfx pull/378/head:pull/378`
`$ git checkout pull/378`

### CODE REVIEW

**Comment by kevinrushforth** [comment]
There are references to `eglx11` and `eglfb` in some of the `buildSrc/*.gradle` files. I recommend cleaning those up, too.

**Comment by kevinrushforth** [comment]
I also see references in `ES2Pipeline.java`, `GLFactory.java` and `PrismES2Defs.h`. Should those be removed, too?

**Comment by johanvos** [comment]
I removed more references.
Note that not all references are removed, since e.g. the flag EGL_FB might also be passed to the c compiler when compiling for non-eglfb systems. This requires another cleanup.

**Review by kevinrushforth — APPROVED** [review]
Looks good.

**Pull request closed without merging**
