### PR TITLE
8300705: Update boot JDK to 19.0.2

### PR DESCRIPTION
**Pull request by arapte**
Updating boot JDK to 19.0.2.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8300705](https://bugs.openjdk.org/browse/JDK-8300705): Update boot JDK to 19.0.2

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Johan Vos](https://openjdk.org/census#jvos) (@johanvos - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx pull/1019/head:pull/1019` \
`$ git checkout pull/1019`

Update a local copy of the PR: \
`$ git checkout pull/1019` \
`$ git pull https://git.openjdk.org/jfx pull/1019/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1019`

View PR using the GUI difftool: \
`$ git pr show -t 1019`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1019.diff">https://git.openjdk.org/jfx/pull/1019.diff</a>

</details>

### CODE REVIEW

**Review by kevinrushforth — APPROVED** [review]
Looks good. Since it is just updating to a new update in the JDK 19 family (from 19.0.1 to 19.0.2), a single reviewer should be sufficient.

You might wait until tomorrow (as long as it is before RDP2) to integrate it in case @johanvos has any concerns.

**Review by kevinrushforth — CHANGES_REQUESTED** [review]
Actually, I just noticed that this is targeted to `master`. It should be targeted to `jfx20`.

**Review by kevinrushforth — APPROVED** [review]
All good now.

**Review by johanvos — APPROVED** [review]

**Comment by johanvos** [comment]
Looks good

**Pull request closed without merging**
