### PR TITLE
8339212: gradle downloads x64 binary of SWT on Linux/aarch64 

### PR DESCRIPTION
**Pull request by anupamdev20**
Hi,

I have updated the name of the SWT.jar that needs to be downloaded during the build process for Linux aarch64.
from:
    IS_LINUX ? "org.eclipse.swt.gtk.linux.x86_64_3.124.200.v20231113-1355" : ""

to:
    IS_LINUX && IS_AARCH64 ? "org.eclipse.swt.gtk.linux.aarch64_3.124.200.v20231113-1355" :
    IS_LINUX && !IS_AARCH64 ? "org.eclipse.swt.gtk.linux.x86_64_3.124.200.v20231113-1355" : ""

Please review.

Regards,
Anupam

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Warning
&nbsp;⚠️ Found leading lowercase letter in issue title for `8339212: gradle downloads x64 binary of SWT on Linux/aarch64`

### Issue
 * [JDK-8339212](https://bugs.openjdk.org/browse/JDK-8339212): gradle downloads x64 binary of SWT on Linux/aarch64 (**Bug** - P4)

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Joeri Sykora](https://openjdk.org/census#sykora) (@tiainen - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1549/head:pull/1549` \
`$ git checkout pull/1549`

Update a local copy of the PR: \
`$ git checkout pull/1549` \
`$ git pull https://git.openjdk.org/jfx.git pull/1549/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1549`

View PR using the GUI difftool: \
`$ git pr show -t 1549`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1549.diff">https://git.openjdk.org/jfx/pull/1549.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1549#issuecomment-2316711781)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
@anupamdev20 You also need to add an entry for the Linux/aarch64 jar file in `gradle/verification-metadata.xml`. Copy the entry for the Linux / x64 jar file and modify it as needed. Without this, the build will fail on Linux / aarch64. We don't do Linux / aarch64 builds in our CI nor is there a GHA build on Linux / aarch64. I'll file a bug for the latter.

@tiainen Would you be able to test this once Anupam has added the checksum?

Reviewers: @kevinrushforth @tiainen 

/reviewers 2

**Comment by kevinrushforth** [comment]
I updated the JBS bug title to be clearer. Can you update this PR title to match?

**Comment by anupamdev20** [comment]
Hi @kevinrushforth,
Thankyou for the review. Can you please let me know how to get the checksum for aarch64? I see it gets generated automatically by gradle. ( https://github.com/openjdk/jfx/tree/master/gradle#readme )
I do not have aarch64 headful machine to generate the checksum either. As you suggested, copying the entry for Linux /x64 and modifying it will have the same checksum as x86-64 which would be wrong. 
Please suggest.

Thanks,
~Anupam

**Comment by kevinrushforth** [comment]
> Can you please let me know how to get the checksum for aarch64?

Download the file locally, then:

```
shasum -a 256 org.eclipse.swt.gtk.linux.aarch64_3.124.200.v20231113-1355.jar
```

**Comment by anupamdev20** [comment]
Thanks @kevinrushforth. I have updated verification-metadata.xml.

Regards,
Anupam

**Comment by kevinrushforth** [comment]
The checksum you added looks correct (it matches the one I get when I download it). I still want to run one more test.

**Review by kevinrushforth — APPROVED** [review]
I pulled the PR branch, then locally edited `build.gradle` to download the new linux_aarch64 artifact on the platform I was building on (it happened to be Windows, but whatever platform you have will work). It worked, meaning the entry you added to `gradle/verification.xml` was good.

Btw, I filed the following bug to add a GHA build for Linux / aarch64, similar to what I recently did for macOS / aarch64:

[JDK-8339270](https://bugs.openjdk.org/browse/JDK-8339270): GHA: build on Linux / aarch64

**Review by tiainen — APPROVED** [review]
Build was successful on a linux aarch64 machine.

**Pull request closed without merging**
