### PR TITLE
8339726: Remove pausing code (used for testing) from AbstractPrimaryTimer

### PR DESCRIPTION
**Pull request by hjohn**
This PR removes the pausing logic from AbstractPrimaryTimer.  The test that is using it wasn't actually testing anything in AbstractPrimaryTimer itself, and no other code needs this pausing code.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8339726](https://bugs.openjdk.org/browse/JDK-8339726): Remove pausing code (used for testing) from AbstractPrimaryTimer (**Enhancement** - P4)

### Reviewers
 * [Andy Goryachev](https://openjdk.org/census#angorya) (@andy-goryachev-oracle - **Reviewer**)
 * [Michael Strauß](https://openjdk.org/census#mstrauss) (@mstr2 - Committer)
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Marius Hanl](https://openjdk.org/census#mhanl) (@Maran23 - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1558/head:pull/1558` \
`$ git checkout pull/1558`

Update a local copy of the PR: \
`$ git checkout pull/1558` \
`$ git pull https://git.openjdk.org/jfx.git pull/1558/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1558`

View PR using the GUI difftool: \
`$ git pr show -t 1558`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1558.diff">https://git.openjdk.org/jfx/pull/1558.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1558#issuecomment-2338871005)

### CODE REVIEW

**Review by andy-goryachev-oracle — APPROVED** [review]
nice cleanup!

**Review by mstr2 — APPROVED** [review]
Looks good.

**Review by kevinrushforth — APPROVED** [review]
Good cleanup. Without digging a bit more, I'm not sure why these were originally added, but they are clearly useless now.

**Review by Maran23 — APPROVED** [review]
Looks good to me too and always good to clean up things that are especially only used for testing.
The git history does not reveal why this was added, but it probably doesn't matter.

**Pull request closed without merging**
