### PR TITLE
8239589: JavaFX UI will not repaint after reconnecting via Remote Desktop

### PR DESCRIPTION
**Pull request by Schmidor**
When connecting via Remote Desktop to a Windows 10 machine ans starting a JavaFX application, the D3D pipeline is used successfully.
After closing the the Remote Desktop session and reconnecting, the D3D requests fail with an D3DERR_DEVICEREMOVED  HResult, and the application contents are not rendered anymore.
Reinitializing the whole pipeline fixes that.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8239589](https://bugs.openjdk.java.net/browse/JDK-8239589): JavaFX UI will not repaint after reconnecting via Remote Desktop

### Download
`$ git fetch https://git.openjdk.java.net/jfx pull/315/head:pull/315`
`$ git checkout pull/315`

### CODE REVIEW

**Comment by kevinrushforth** [comment]
This will need a fair bit of testing. I'm not certain that we always want to recreate the factory when the device is lost, but we can evaluate that during the review.

**Comment by Schmidor** [comment]
The full recreation of the pipeline is only done when D3DERR_DEVICEREMOVED is occurring. On other causes of why the device is not ready, only the factory reference in the painter is cleared.

**Comment by kevinrushforth** [comment]
> The full recreation of the pipeline is only done when D3DERR_DEVICEREMOVED is occurring

I see that now. That part is fine then.

Another concern is that this would be the first time we have recreated a GraphicsPipeline -- they are effectively singletons today. This could have unexpected side effects and would need to be very carefully reviewed and tested.

Have you considered an alternative where you retain the GraphicsPipeline, but recreate the native device?

**Comment by Schmidor** [comment]
I hope I understood your intend. I've tried to replace the recreation of the GraphicsPipeline-Instance by only calling the native parts. Unfortunately that doesn't seem to work at all. Probably I'm missing some updates.
```
    public boolean reinit() {
        if (d3dEnabled) {
            if (creator != Thread.currentThread()) {
                throw new IllegalStateException(
                        "This operation is not permitted on the current thread ["
                                + Thread.currentThread().getName() + "]");
            }
            notifyAllResourcesReleased();
            nDispose();
            for (int i = 0; i != factories.length; ++i) {
                factories[i] = null;
            }
            nInit(PrismSettings.class);
            factories = new D3DResourceFactory[nGetAdapterCount()];
        }
        return d3dEnabled;
    }
```

**Comment by chewett** [comment]
Now more of my company are remoting into machines this issue is causing problems for us.

**Comment by kevinrushforth** [comment]
I moved it to Draft before noticing that there were additional commits after your last comment that I had missed seeing earlier, so I moved it back to RFR.

**Comment by kevinrushforth** [comment]
This is a good starting point, but it will need additional work, possibly in the native D3D code as well as on the Java side, to fully cleanup and recreate all of the resources after the device is recreated. As discussed offline, I'll take a stab at this using your PR as a starting point.

I ran some tests this afternoon. It does detect that the devide was removed, and the disposes and recreates the device, but then it has problem drawing anything with a texture; it throws an exception and there are rendering artifacts:

```
KCR: create resource factor for screen 0
D3DContext::testCooperativeLevel
D3DContext::testCooperativeLevel
D3DContext::testCooperativeLevel
D3DContext::testCooperativeLevel
D3DContext::testCooperativeLevel
KCR: D3DERR_DEVICEREMOVED
KCR: dispose graphics pipeline
KCR: instance is null: reinitialize D3DPipeline
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Cannot invoke "com.sun.prism.GraphicsPipeline.is3DSupported()" because the return value of "com.sun.prism.GraphicsPipeline.getPipeline()" is null
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.isSupported(QuantumToolkit.java:1209)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.isSupportedImpl(PlatformImpl.java:979)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.isSupported(PlatformImpl.java:646)
	at javafx.graphics/javafx.application.Platform.isSupported(Platform.java:262)
	at javafx.graphics/com.sun.javafx.scene.input.PickResultChooser.processOffer(PickResultChooser.java:182)
	at javafx.graphics/com.sun.javafx.scene.input.PickResultChooser.offer(PickResultChooser.java:143)
	at javafx.graphics/javafx.scene.Node.intersects(Node.java:5229)
	at javafx.graphics/javafx.scene.Node$1.intersects(Node.java:553)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.intersects(NodeHelper.java:258)
	at javafx.graphics/javafx.scene.layout.Region.doPickNodeLocal(Region.java:3227)
        ...
	at javafx.graphics/javafx.scene.Scene.pick(Scene.java:2031)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3810)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1851)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2584)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:413)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:942)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:832)
...
KCR: create resource factor for screen 0
D3DContext::testCooperativeLevel
D3DContext::testCooperativeLevel
KCR: dispose graphics pipeline
```
HelloFontSize

**Comment by kevinrushforth** [comment]
I created PR #403 using this as a starting point, so I am moving this PR back to draft (and it probably can be closed).

**Comment by kevinrushforth** [comment]
I just created the final PR #430 to fix this bug. As a result, I'm closing this PR

**Pull request closed without merging**
