### PR TITLE
8326619: Stage.sizeToScene() on maximized/fullscreen Stage breaks the Window

### PR DESCRIPTION
**Pull request by Maran23**
This PR fixes the problem that maximizing/fullscreen a `Stage` or `Dialog` is broken when `sizeToScene()` was called before or after.

The approach here is to ignore the `sizeToScene()` request when the `Stage` is maximized or set to fullscreen. 
Otherwise the Window Manager of the OS will be confused and you will get weird flickering or wrong Window buttons (e.g. on Windows, the 'Maximize' button still shows the 'Restore' Icon, while we already resized the `Stage` to not be maximized).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))
- [x] Change requires CSR request [JDK-8334966](https://bugs.openjdk.org/browse/JDK-8334966) to be approved

### Issues
 * [JDK-8326619](https://bugs.openjdk.org/browse/JDK-8326619): Stage.sizeToScene() on maximized/fullscreen Stage breaks the Window (**Bug** - P4)
 * [JDK-8334966](https://bugs.openjdk.org/browse/JDK-8334966): Stage.sizeToScene() on maximized/fullscreen Stage breaks the Window (**CSR**)

### Reviewers
 * [Lukasz Kostyra](https://openjdk.org/census#lkostyra) (@lukostyra - Committer)
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1382/head:pull/1382` \
`$ git checkout pull/1382`

Update a local copy of the PR: \
`$ git checkout pull/1382` \
`$ git pull https://git.openjdk.org/jfx.git pull/1382/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1382`

View PR using the GUI difftool: \
`$ git pr show -t 1382`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1382.diff">https://git.openjdk.org/jfx/pull/1382.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1382#issuecomment-1965252243)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
Since this involved changing the specified behavior it will need a CSR. If we agree that this is the right behavior, then the CSR will be trivial.

/csr
/reviewers 2

**Comment by kevinrushforth** [comment]
This seems like a reasonable fix and spec change. Have you tested the case of calling sizeToScene before setting full-screen or maximzed? Since the pending flag will still be set in that case, I want to make sure that case is tested as well.

Also, if this fixed [JDK-8316425](https://bugs.openjdk.org/browse/JDK-8316425), then that bug should be closed as a duplicate of this one.

@lukostyra @arapte can you also review this?

**Comment by kevinrushforth** [comment]
Btw, I get the following test failures on our headful Linux test systems:

```
SizeToSceneFullscreenTest > testInitialSizeFullscreen FAILED
    java.lang.AssertionError: Stage height expected:<1080.0> but was:<1117.0>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:555)
        at test.javafx.stage.SizeToSceneFullscreenTest.testInitialSizeFullscreen(SizeToSceneFullscreenTest.java:78)
```

This seems unrelated to your fix. I think the problem might be that in full-screen mode the stage can be bigger than the visible screen size or maybe the decorations are just larger on that system. You might either need to increase the tolerance values or instead check for >= visible width / height (possibly with some small tolerance).

**Comment by Maran23** [comment]
> This seems like a reasonable fix and spec change. Have you tested the case of calling sizeToScene before setting full-screen or maximzed? Since the pending flag will still be set in that case, I want to make sure that case is tested as well.

I thought about this as well but could not find any problem at least on Windows.
If we want to be perfectly safe, we may still want to set the flag when `sizeToScene()` is called. What do you think?

I used the following code to test this, and it didn't matter when `sizeToScene()` was called:

```
   @Override
    public void start(Stage primaryStage) throws Exception {
        StackPane root = new StackPane();
        Button wss = new Button("Wss");
        wss.setPrefSize(50, 50);
        root.getChildren().add(wss);

        Scene scene = new Scene(root);

        Stage stage = new Stage();
        stage.setWidth(500);
        stage.setMaximized(true);
        stage.sizeToScene();
        stage.setScene(scene);
        stage.show();
    }
```

**Review by lukostyra — APPROVED** [review]
LGTM, tests also seem to be fine on my end (checked on Windows and Ubuntu 22.04 LTS)

**Review by kevinrushforth — COMMENTED** [review]
The fix looks good. The spec changes (updated javadocs) look good. Can you create the CSR for the spec change?

I have a couple overall comments:

* I wanted to verify different orders of operation, so I wrote a (manual) test program and attached it to the JBS bug. It covers the following cases:
    * set ; sizeToScene ; show
    * sizeToScene ; set ; show
    * show ; set ; sizeToScene
    * show ; sizeToScene ; set

I verified that the first 3 are broken today. All cases work with your fix. I think it might be a good idea to add automated tests for the different orderings.

* Please merge the latest master. Note that the calls to Util.shutdown in the tests must be fixed after this is done or they will no longer compile.

**Comment by kevinrushforth** [comment]
@Maran23 I think this is pretty close to being ready to go in. At a minimum, you will need to merge master and then fix the test so that it will compile, and then create a CSR with the updated specification (I can help with that if needed). My only other suggestion was around additional tests that might be useful, but they could be done as a follow-on fix.

**Comment by Maran23** [comment]
> @Maran23 I think this is pretty close to being ready to go in. At a minimum, you will need to merge master and then fix the test so that it will compile, and then create a CSR with the updated specification (I can help with that if needed). My only other suggestion was around additional tests that might be useful, but they could be done as a follow-on fix.

Yes, sure, I've just been very busy with my day job over the last few weeks. I hopefully have more time now though :)
And I totally agree with writing more tests, always good to have and to ensure quality. So no need for a follow-on ticket.

**Comment by Maran23** [comment]
> * I wanted to verify different orders of operation, so I wrote a (manual) test program

I'm retesting and writing tests right now and reproduced one usecase out of my head that indeed 'fails' now.
Take the following code:
```
        Button button = new Button();
        button.setMinSize(440, 440);

        Scene scene = new Scene(button);
        stage.setTitle("JavaFX test stage!");
        stage.setScene(scene);

        stage.setWidth(50);
        stage.setHeight(50);

        stage.setFullScreen(true);
        stage.sizeToScene();
        stage.setFullScreen(false);

        stage.show();
```

With my logic, the `sizeToScene()` flag is not remembered, so the scene is not adjusted in the `sizeToScene` style after I 'go out' of fullscreen mode.

If I do instead:
```
        stage.sizeToScene();
        stage.setFullScreen(true);
        stage.setFullScreen(false);
```

The flag is remembered and the scene has the size of the button. Not sure what the expectation is here, but we could fix this problem by still remembering the flag if called.

**Review by kevinrushforth — COMMENTED** [review]
The fix looks good. I left one comment on the docs, but otherwise OK.

The test fails for me on Linux. Adding a sleep(500) before the assert checks fixes it (there is no reliable way to ensure certain operations without a sleep). I left inline comments. I also left one question regarding the per-test cleanup method.

**Comment by kevinrushforth** [comment]
@Maran23 Can you create the CSR? The updated docs (with the small suggestion I made) look ready.

**Review by kevinrushforth — APPROVED** [review]
Looks good. I'll review the CSR and then you can "Finalize" it.

**Comment by kevinrushforth** [comment]
@lukostyra Please re-review.

**Review by lukostyra — COMMENTED** [review]
Change looks good, but I'm still seeing failures on my macOS system (Sonoma 14.5, MacBook Pro M1 Max):

```
SizeToSceneTest > testInitialSizeOnSizeToSceneThenFullscreen() FAILED
    org.opentest4j.AssertionFailedError: 1080.0 >= 1085.0 ==> expected: <true> but was: <false>
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at app//org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
        at app//org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:210)
        at app//test.javafx.stage.SizeToSceneTest.assertStageScreenBounds(SizeToSceneTest.java:76)
        at app//test.javafx.stage.SizeToSceneTest.testInitialSizeOnSizeToSceneThenFullscreen(SizeToSceneTest.java:150)

SizeToSceneTest > testInitialSizeAfterShowFullscreenThenSizeToScene() FAILED
    org.opentest4j.AssertionFailedError: 1080.0 >= 1085.0 ==> expected: <true> but was: <false>
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at app//org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
        at app//org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:210)
        at app//test.javafx.stage.SizeToSceneTest.assertStageScreenBounds(SizeToSceneTest.java:76)
        at app//test.javafx.stage.SizeToSceneTest.testInitialSizeAfterShowFullscreenThenSizeToScene(SizeToSceneTest.java:186)

SizeToSceneTest > testInitialSizeAfterShowSizeToSceneThenFullscreen() FAILED
    org.opentest4j.AssertionFailedError: 1080.0 >= 1085.0 ==> expected: <true> but was: <false>
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at app//org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
        at app//org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:210)
        at app//test.javafx.stage.SizeToSceneTest.assertStageScreenBounds(SizeToSceneTest.java:76)
        at app//test.javafx.stage.SizeToSceneTest.testInitialSizeAfterShowSizeToSceneThenFullscreen(SizeToSceneTest.java:162)

SizeToSceneTest > testInitialSizeOnFullscreenThenSizeToScene() FAILED
    org.opentest4j.AssertionFailedError: 1080.0 >= 1085.0 ==> expected: <true> but was: <false>
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at app//org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
        at app//org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:210)
        at app//test.javafx.stage.SizeToSceneTest.assertStageScreenBounds(SizeToSceneTest.java:76)
        at app//test.javafx.stage.SizeToSceneTest.testInitialSizeOnFullscreenThenSizeToScene(SizeToSceneTest.java:128)
```

Windows and Ubuntu 22.04 LTS work fine for me.

**Comment by kevinrushforth** [comment]
Based on those failures it would be a good idea to add tolerance to the check for >= visual bounds.

**Comment by Maran23** [comment]
> Change looks good, but I'm still seeing failures on my macOS system (Sonoma 14.5, MacBook Pro M1 Max):

I'm confused, the screen height is reported as 1085? Looks like the width, but I still would not expect a width like that. Thats why the condition is written the other way around.

**Review by kevinrushforth — APPROVED** [review]

**Comment by kevinrushforth** [comment]
@Maran23 This is ready for you to integrate now.

**Comment by kevinrushforth** [comment]
I'm not sure how we missed this in testing, but the full screen tests fail on Ubuntu 22.04 because a full screen window can be larger than the visual bounds. I started seeing nightly headful test failures after this was integrated, but didn't have time to look at it until now. I filed [JDK-8336272](https://bugs.openjdk.org/browse/JDK-8336272) to fix the test.

**Pull request closed without merging**
