### PR TITLE
8257895: Allow building of JavaFX media libs for Apple Silicon

### PR DESCRIPTION
**Pull request by sashamatveev**
- Added support to compile media on arm.
- libffi is based on 3.3.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8257895](https://bugs.openjdk.java.net/browse/JDK-8257895): Allow building of JavaFX media libs for Apple Silicon

### Reviewers
 * [Johan Vos](https://openjdk.java.net/census#jvos) (@johanvos - **Reviewer**)
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)

### Contributors
 * Johan Vos `<jvos@openjdk.org>`

### Download
`$ git fetch https://git.openjdk.java.net/jfx pull/412/head:pull/412`
`$ git checkout pull/412`

### CODE REVIEW

**Comment by johanvos** [comment]
I didn't test it on real hardware, but it looks good and doesn't cause regression.

**Review by johanvos — APPROVED** [review]

**Review by kevinrushforth — CHANGES_REQUESTED** [review]
This breaks the build on Windows.

```
cl.exe -DFFI_BUILDING -DGSTREAMER_LITE -I../../../3rd_party/libffi/include -I../../../3rd_party/libffi/include/win/x64 -nologo -W3 -WX- -EHsc -GS -fp:precise -Gm- -Zc:wchar_t -Zc:forScope -Gd -wd"4430" -analyze- -errorReport:queue -O1 -Oy -MD -Gy -GF -DX86_WIN64 -TC -c -Fo.../jfx/modules/javafx.media/build/native/win/Release/obj/3rd_party/libffi/src/java_raw_api.obj ../../../3rd_party/libffi/src/java_raw_api.c
../../../3rd_party/libffi/include/win/x64\ffi.h(58): fatal error C1083: Cannot open include file: 'ffitarget.h': No such file or directory
make[1]: *** [Makefile.ffi:79: .../jfx/modules/javafx.media/build/native/win/Release/obj/3rd_party/libffi/src/closures.obj] Error 2
make[1]: *** Waiting for unfinished jobs....
java_raw_api.c
../../../3rd_party/libffi/include/win/x64\ffi.h(58): fatal error C1083: Cannot open include file: 'ffitarget.h': No such file or directory
make[1]: *** [Makefile.ffi:79: .../jfx/modules/javafx.media/build/native/win/Release/obj/3rd_party/libffi/src/java_raw_api.obj] Error 2
make[1]: Leaving directory '.../jfx/modules/javafx.media/src/main/native/gstreamer/projects/win/glib-lite'
make: *** [Makefile:60: .../jfx/modules/javafx.media/build/native/win/Release/libffi.lib] Error 2
make: Leaving directory '.../jfx/modules/javafx.media/src/main/native/gstreamer/projects/win/glib-lite'

FAILURE: Build failed with an exception.

* Where:
Build file '...\jfx\build.gradle' line: 3284

* What went wrong:
Execution failed for task ':media:buildWinGlib'.
> Process 'command 'make'' finished with non-zero exit value 2
```

**Comment by sashamatveev** [comment]
Windows build should be fixed.

**Review by kevinrushforth — APPROVED** [review]
Looks good. I did a sanity build on all three platforms (using the default x86_64 arch for macOS) and that passed.

I then did a macOS aarch64 build, and verified that it runs and can play media files.

**Comment by kevinrushforth** [comment]
@johanvos can you re-review?

@sashamatveev since you started with Johan's patch, can you add him as a contributor?

**Review by johanvos — APPROVED** [review]

**Pull request closed without merging**
