### PR TITLE
8336941 : Update libxslt to 1.1.42

### PR DESCRIPTION
**Pull request by HimaBinduMeda**
Updated libxslt to v1.1.42. Verified build on all platforms. No issue seen

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8336941](https://bugs.openjdk.org/browse/JDK-8336941): Update libxslt to 1.1.42 (**Bug** - P2)

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Jay Bhaskar](https://openjdk.org/census#jbhaskar) (@jaybhaskar - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1527/head:pull/1527` \
`$ git checkout pull/1527`

Update a local copy of the PR: \
`$ git checkout pull/1527` \
`$ git pull https://git.openjdk.org/jfx.git pull/1527/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1527`

View PR using the GUI difftool: \
`$ git pr show -t 1527`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1527.diff">https://git.openjdk.org/jfx/pull/1527.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1527#issuecomment-2264673637)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
Reviewers: @kevinrushforth @tiainen 

/reviewers 2

**Review by kevinrushforth — COMMENTED** [review]
Looks good, although I notice one difference between the upstream libxslt repo and this PR in a now-unmaintained config file:

```
diff -u -w -r $JFX/modules/javafx.web/src/main/native/Source/ThirdParty/libxslt/src/libxslt.m4 $LIBXML/libxslt.m4
--- $JFX/modules/javafx.web/src/main/native/Source/ThirdParty/libxslt/src/libxslt.m4 2023-07-27 15:08:29.124274800 -0700
+++ $LIBXML/libxslt.m4        2024-08-02 10:18:29.007649600 -0700
@@ -5,6 +5,8 @@
 # Configure paths for GLIB
 # Owen Taylor     97-11-3
 #
+# Deprecated and unmaintained. Use pkg-config or xslt-config.
+#
 # Modified to work with libxslt by Thomas Schraitle 2002/10/25
 # Fixed by Edward Rudd 2004/05/12
```

Do we use `libxslt.m4` when we run configure to generate the platform-specific headers? If not, I recommend that you remove it from our repo. If we do, please add the two lines from the above patch so that we match the upstream.

Note that the deprecation comment was added by:

https://gitlab.gnome.org/GNOME/libxslt/-/commit/200ee26982b4c8cbe165555ae36aa684a744ccf4

so we will eventually need to stop using it if we still are.

**Review by Clearvision92 — COMMENTED** [review]
Hi @Clearvision92, thanks for making a comment in an OpenJDK project!

All comments and discussions in the OpenJDK Community must be made available under the OpenJDK [Terms of Use](https://openjdk.java.net/legal/tou/). If you already are an OpenJDK [Author](https://openjdk.java.net/bylaws#author), [Committer](https://openjdk.java.net/bylaws#committer) or [Reviewer](https://openjdk.java.net/bylaws#reviewer), please click [here](https://bugs.openjdk.java.net/secure/CreateIssue.jspa?pid=11300&issuetype=1) to open a new issue so that we can record that fact. Please Use "Add GitHub user Clearvision92" for the summary.

If you are not an OpenJDK Author, Committer or Reviewer, simply check the box below to accept the OpenJDK Terms of Use for your comments.

 - [ ]  I agree to the [OpenJDK Terms of Use](https://openjdk.java.net/legal/tou/) for all comments I make in a project in the [OpenJDK GitHub organization](https://github.com/openjdk).

Your comment will be automatically restored once you have accepted the OpenJDK [Terms of Use](https://openjdk.java.net/legal/tou/).

**Review by kevinrushforth — APPROVED** [review]

**Comment by victordyakov** [comment]
@arapte please review

**Comment by kevinrushforth** [comment]
@tiainen Do you want a chance to review this?

**Comment by kevinrushforth** [comment]
@jaybhaskar Can you be the second reviewer?

**Review by jaybhaskar — APPROVED** [review]
+looks good to me

**Pull request closed without merging**
