### PR TITLE
8318387: Update GStreamer to 1.22.6

### PR DESCRIPTION
**Pull request by sashamatveev**
- GStreamer updated to 1.22.6 and GLib updated to 2.78.1.
- Tested on all platforms with all supported media streams.
- GStreamer 1.22.6 requires GLib 2.62.0, but since we need to support older GLib versions on Linux following APIs were changed from new to old one (restored GStreamer 1.20.1 code) (Linux only, other platforms using latest code):
  - g_queue_clear_full() -> g_queue_foreach(), g_queue_clear().
  - g_atomic_rc_box_*() -> g_weak_ref_init(), g_weak_ref_clear().

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issues
 * [JDK-8318387](https://bugs.openjdk.org/browse/JDK-8318387): Update GStreamer to 1.22.6 (**Bug** - P3)
 * [JDK-8318386](https://bugs.openjdk.org/browse/JDK-8318386): Update Glib to 2.78.1 (**Bug** - P3)

### Reviewers
 * [Joeri Sykora](https://openjdk.org/census#sykora) (@tiainen - Author)
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1290/head:pull/1290` \
`$ git checkout pull/1290`

Update a local copy of the PR: \
`$ git checkout pull/1290` \
`$ git pull https://git.openjdk.org/jfx.git pull/1290/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1290`

View PR using the GUI difftool: \
`$ git pr show -t 1290`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1290.diff">https://git.openjdk.org/jfx/pull/1290.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1290#issuecomment-1817133913)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
The Windows GHA failure is a transient network or infrastructure failure unrelated to this PR:

```
curl: (56) Recv failure: Connection was reset
```

/reviewers 2

**Comment by sashamatveev** [comment]
8318387: Update GStreamer to 1.22.6 [v3]
- Fixed GLib version. It should be 2.78.1 instead of 2.78.0.

**Review by tiainen — APPROVED** [review]
All builds and tests succeeded.

**Review by kevinrushforth — APPROVED** [review]
Looks good. Testing is green.

**Pull request closed without merging**
