### PR TITLE
8304041: [WebView] Text on the left and right of emoji is not visible

### PR DESCRIPTION
**Pull request by prrace**
This fixes a problem with mixing Emoji and regular text in Webview.
The Prism implementation expects that Emoji will not be in the same call to drawString as regular glyphs,
since they need very different handling.
This fix breaks up the runs webview hands to Prism.
The test program in the bug report now renders properly (which it never did before in any release)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8304041](https://bugs.openjdk.org/browse/JDK-8304041): [WebView] Text on the left and right of emoji is not visible (**Bug** - P3)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1083/head:pull/1083` \
`$ git checkout pull/1083`

Update a local copy of the PR: \
`$ git checkout pull/1083` \
`$ git pull https://git.openjdk.org/jfx.git pull/1083/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1083`

View PR using the GUI difftool: \
`$ git pr show -t 1083`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1083.diff">https://git.openjdk.org/jfx/pull/1083.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1083#issuecomment-1499554005)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
The intent is to split up the runs passed into `WCGraphicsPrismContext::drawString` into separate drawString calls in the same way that they would be split if they were drawn in a Label or Text node. It now works correctly for text mixed with simple emojis. For emojis with modifiers, it is better than it was, but is still not equivalent to the same string drawn in a Text node or Label in all cases. I ran the test case attached to [JDK-8303494](https://bugs.openjdk.org/browse/JDK-8303494), and the skin tone modifiers are now displayed in WebView (just like they are in a Label), but the male modifiers are not displayed in WebView (whereas they are in a Label).

If I modify your patch to force splitting the string on each character (regardless of whether it is a color glyph or not), then it produces expected result, meaning it is then equivalent to drawing the same string in a Label.

Current code (without your fix) produces the following output:

emoji-orig

This PR produces the following output:

emoji-fix

Drawing that same string in a Label produces the following output, as does a modified version of your patch that forces each character into its own string:

emoji-label

Maybe you need to check something other than (or in addition to) "isColorGlyph()" to determine where to split the string?

**Comment by kevinrushforth** [comment]
This PR is still being worked on.

**Comment by yososs** [comment]
The G2D implementation of OpenJDK would be helpful in solving this problem.

https://github.com/openjdk/jdk/blob/0db63ec76d451295e273c8e3272d013e2c3348ef/src/java.desktop/share/classes/sun/java2d/pipe/GlyphListLoopPipe.java#L41C2-L59C6

**Pull request closed without merging**
