### PR TITLE
8276206: Rename TextBinding class to better express its purpose

### PR DESCRIPTION
**Pull request by mstr2**
This PR renames `TextBinding` to `MnemonicInfo` and adds the following text to its javadoc:

          /**
    33 +    * Provides information about mnemonics contained within a string.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8276206](https://bugs.openjdk.java.net/browse/JDK-8276206): Rename TextBinding class to better express its purpose

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Jeanette Winzenburg](https://openjdk.java.net/census#fastegal) (@kleopatra - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/678/head:pull/678` \
`$ git checkout pull/678`

Update a local copy of the PR: \
`$ git checkout pull/678` \
`$ git pull https://git.openjdk.java.net/jfx pull/678/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 678`

View PR using the GUI difftool: \
`$ git pr show -t 678`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/678.diff">https://git.openjdk.java.net/jfx/pull/678.diff</a>

</details>

### CODE REVIEW

**Review by kevinrushforth — APPROVED** [review]
Looks good. I'd like a review from one or both of @aghaisas or @kleopatra

**Review by kleopatra — APPROVED** [review]
looks good (modulo our disagreement on whether or not to do it at all :)

**Pull request closed without merging**
