### PR TITLE
8270867: Debug build of WebKit 613.1 fails on Linux

### PR DESCRIPTION
**Pull request by petermz**
The file `wtf/linux/MemoryPressureLinux.cpp` was renamed `wtf/unix/MemoryPressureUnix.cpp` in https://trac.webkit.org/changeset/261428 . In the openjfx workspace, both files are present. I'm removing the old file.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8270867](https://bugs.openjdk.java.net/browse/JDK-8270867): Debug build of WebKit 613.1 fails on Linux

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Jay Bhaskar](https://openjdk.java.net/census#jbhaskar) (@jaybhaskar - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/756/head:pull/756` \
`$ git checkout pull/756`

Update a local copy of the PR: \
`$ git checkout pull/756` \
`$ git pull https://git.openjdk.java.net/jfx pull/756/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 756`

View PR using the GUI difftool: \
`$ git pr show -t 756`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/756.diff">https://git.openjdk.java.net/jfx/pull/756.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
Thanks for the PR to fix this? As I noted in the JBS issue, [JDK-8283246](https://bugs.openjdk.java.net/browse/JDK-8283246) is a duplicate of [JDK-8270867](https://bugs.openjdk.java.net/browse/JDK-8270867) . Can you modify the title of this PR to the following?

```
8270867: Debug build of WebKit 613.1 fails on Linux
```

/reviewers 2

**Comment by kevinrushforth** [comment]
@jaybhaskar Can you also review this?

**Comment by jaybhaskar** [comment]
The patch https://trac.webkit.org/changeset/261428  committed in May 8, 2020. it is older than a recent patch https://bugs.webkit.org/attachment.cgi?id=443979&action=prettypatch

But i remember , the error for this file [MemoryPressureHandlerLinux.cpp]  was  at 
  if (ReliefLogger::loggingEnabled() && isUnderMemoryPressure())
        LOG(MemoryPressure, "System is no longer under memory pressure.");

The variable  isUnderMemoryPressure was giving error. saying right variable m_underMemoryPressure instead of isUnderMemoryPressure

Error:
[jfx/modules/javafx.web/src/main/native/Source/WTF/wtf/linux/MemoryPressureHandlerLinux.cpp:39:28: error: 'LogMemoryPressure' was not declared in this scope; did you mean 'isUnderMemoryPressure'? ]


There was anothe issue with the build, as below 
[JavaScriptCore/Scripts/resolve-asm-file-conflicts.rb](http://rejfx.us.oracle.com:8080/job/jfx-submit/label=lin-ol7-x64/ws/jfx/rt/modules/javafx.web/build/linux/Debug/JavaScriptCore/Scripts/resolve-asm-file-conflicts.rb)>:99:in `parse': undefined method `/' for

This was removed by updating rub version.

**Comment by jaybhaskar** [comment]
Yes , The PR looks good. We can file new bug for ruby version related issue.

**Review by kevinrushforth — APPROVED** [review]
I was able to do a local debug build using `-PCONF=DebugNative` on my Linux system using this patch. I also confirmed that a production build still works fine on our CI build system.

Btw, I filed [JDK-8283273](https://bugs.openjdk.java.net/browse/JDK-8283273) as a follow-up bug to track the problem of nor being able to do a debug build on Linux with an older version of Ruby.

**Review by jaybhaskar — APPROVED** [review]
Since there are two equivalent files for same purpose , it looks good to remove older one.

**Pull request closed without merging**
