### PR TITLE
8238650: Allow to override buildDate with SOURCE_DATE_EPOCH

### PR DESCRIPTION
**Pull request by jgneff**
This is a continuation of the [pull request][1] started by @bmwiedemann in January 2020. After this change is integrated, I can follow up immediately with additional pull requests that get us much closer to providing fully reproducible builds.

#### Motivation

The only conclusive way to verify a software package is to reproduce it. That's the main point of the Linux Foundation article [Preventing Supply Chain Attacks like SolarWinds][2] by David Wheeler, Director of Open Source Supply Chain Security. "In the longer term," he writes, "I know of only one strong countermeasure for this kind of attack: verified reproducible builds."

It's not enough anymore to trust the person, organization, or company that publishes a software package. David Wheeler explains, "Assuming a system can 'never be broken into' is a failing strategy." As I see it, any project that doesn't yet allow for reproducible builds is on a list of possible attack vectors. I'd like to get OpenJFX off that list.

This is a huge undertaking involving the entire open-source community. Just [Debian, for example][3], has over 30,000 source packages to build in a reproducible manner. Remarkably, it's almost 96 percent complete. The OpenJFX package is one of three percent still failing. Our first step towards helping in this goal is to support the [`SOURCE_DATE_EPOCH` specification][4].

#### Implementation

When you want to build 30,000 packages in a reproducible manner, [command-line flags][5] unique to each package aren't so helpful. The environment variable needs to be set, anyway, for the tools invoked by Gradle to pick it up. We could allow for a Gradle property in addition to the environment variable. The Gradle property would override the default current date and export the environment variable, and the environment variable would override the command-line property. I think it makes more sense in the OpenJFX build to support the environment variable directly.

With these considerations, I added the support just as recommended by the example for "Java / gradle" on the Reproducible Builds [`SOURCE_DATE_EPOCH`][6] page. For comparison, the [OpenJDK build][7] does the reverse, using the *configure* script option `--with-source-date` to export the `SOURCE_DATE_EPOCH` environment variable.

[1]: https://github.com/openjdk/jfx/pull/99
[2]: https://www.linuxfoundation.org/en/blog/preventing-supply-chain-attacks-like-solarwinds
[3]: https://tests.reproducible-builds.org/debian/reproducible.html
[4]: https://reproducible-builds.org/specs/source-date-epoch/
[5]: https://wiki.debian.org/ReproducibleBuilds/StandardEnvironmentVariables#More_detailed_discussion
[6]: https://reproducible-builds.org/docs/source-date-epoch/
[7]: https://github.com/openjdk/jdk/commit/1a16a4b6

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8238650](https://bugs.openjdk.java.net/browse/JDK-8238650): Allow to override buildDate with SOURCE_DATE_EPOCH

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)

### Contributors
 * Bernhard M. Wiedemann `<javabmw@lsmod.de>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/422/head:pull/422` \
`$ git checkout pull/422`

Update a local copy of the PR: \
`$ git checkout pull/422` \
`$ git pull https://git.openjdk.java.net/jfx pull/422/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 422`

View PR using the GUI difftool: \
`$ git pr show -t 422`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/422.diff">https://git.openjdk.java.net/jfx/pull/422.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
This is a simple enough change by itself, but since it is intended as the start of a larger effort, I'd like @johanvos (or someone else he designates from Gluon) to be a second reviewer.

**Review by kevinrushforth — APPROVED** [review]
This looks good to me. I tested it and it does what I would expect.

I generally prefer gradle properties to env vars, but supporting the `SOURCE_DATE_EPOCH` env variable directly makes sense for the reasons you pointed out. We could always add a property later to override it, but I suspect we won't ever feel the need to do that.

**Comment by kevinrushforth** [comment]
> @jgneff Could not parse `bmwiedemann` as a valid contributor.

You might retry the "contributor" command with the `@` before their GitHub username (I'm not 100% sure that will work, though).

**Comment by jgneff** [comment]
> You might retry the "contributor" command with the `@` before their GitHub username.

Thanks. I'll try that now. I checked and Bernhard is on the list of "OCAs submitted prior to 2021," but not on the OpenJDK Census list, in case that matters.

By the way, should I be adding my own name, too? It looks as if sometimes people do that and sometimes not. That would put me as "Author" and also on a line with "Co-authored-by" in the commit message.

/contributor add @bmwiedemann

**Comment by jgneff** [comment]
> This is a simple enough change by itself, but since it is intended as the start of a larger effort, I'd like @johanvos (or someone else he designates from Gluon) to be a second reviewer.

I jumped the gun and created the [follow-up pull request][1]. I thought it might help when reviewing this pull request to have a full picture of that larger effort. Although these two changes are part of a huge undertaking in the open-source community, it turns out that the changes required on our part are quite small.

[1]: https://github.com/openjdk/jfx/pull/446

**Comment by kevinrushforth** [comment]
Pending review by @johanvos

**Comment by jgneff** [comment]
Closing this pull request in favor of #446.

The [changes in this pull request][1] are included as the [first commit][2] of pull request #446.

[1]: https://github.com/openjdk/jfx/pull/422/commits/3ada5a30c490abec884d878b4fd86219f2f8c60c
[2]: https://github.com/openjdk/jfx/pull/446/commits/7ef5031c25fe52c3967c482d6960544aa0e1c9f5

**Pull request closed without merging**
