### PR TITLE
8267621: Mark HonorDeveloperSettingsTest as unstable on Linux

### PR DESCRIPTION
**Pull request by arapte**
The test HonorDeveloperSettingsTest.testOpacityWithManuallyChangedValueAndInlineStyleIsSetToInlineStyle is failing intermittently only on GHA build on Linux platform. see: [JDK-8267425](https://bugs.openjdk.java.net/browse/JDK-8267425)

A fix proposed at #509 is a potential fix which adds cleanup of test. But we do not know the root cause of this failure.
Identifying the root cause may take longer which we might push that to next test sprint and the test failure results in failing the Github checks on PR.  So we need to mark this test as unstable.
As of now the test fails only on Linux so we will mark it unstable only for Linux.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8267621](https://bugs.openjdk.java.net/browse/JDK-8267621): Mark HonorDeveloperSettingsTest as unstable on Linux

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/517/head:pull/517` \
`$ git checkout pull/517`

Update a local copy of the PR: \
`$ git checkout pull/517` \
`$ git pull https://git.openjdk.java.net/jfx pull/517/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 517`

View PR using the GUI difftool: \
`$ git pr show -t 517`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/517.diff">https://git.openjdk.java.net/jfx/pull/517.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
Since the NPE is happening in the `setUp` method, which is annotated with `@Before` and runs before the test itself, it seems unlikely that marking just a single test method as unstable is sufficient.

**Comment by arapte** [comment]
True, it is possible that some other test may fail similarly. Shall we mark all tests as unstable ?

**Comment by kevinrushforth** [comment]
I would mark the whole class as unstable. You can do this by adding a static method annotated with `@BeforeClass`.

**Comment by kevinrushforth** [comment]
Or you can add it to the existing per-test `setUp` method.

**Comment by arapte** [comment]
Both ways are generating same report, But @BeforeClass looks better to me.
Shall I change the JBS summary too ?

**Comment by kevinrushforth** [comment]
Yes, please update the JBS title and PR title.

**Review by kevinrushforth — APPROVED** [review]

**Pull request closed without merging**
