### PR TITLE
8294400: Provide media support for libavcodec version 59

### PR DESCRIPTION
**Pull request by sashamatveev**
- Added support for libavcodec 59.
 - libavcodec 59 removed several deprecated APIs and avplugin code was updated to use replacement APIs instead.
 - No changes to avplugin when used with 58 or below.
 - Note: Support for libavcodec 59 was added based on ffmpeg only. libav does not have version 59.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8294400](https://bugs.openjdk.org/browse/JDK-8294400): Provide media support for libavcodec version 59

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Johan Vos](https://openjdk.org/census#jvos) (@johanvos - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx pull/932/head:pull/932` \
`$ git checkout pull/932`

Update a local copy of the PR: \
`$ git checkout pull/932` \
`$ git pull https://git.openjdk.org/jfx pull/932/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 932`

View PR using the GUI difftool: \
`$ git pr show -t 932`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/932.diff">https://git.openjdk.org/jfx/pull/932.diff</a>

</details>

### CODE REVIEW

**Review by kevinrushforth — COMMENTED** [review]
I did a successful test build, but I don't currently have a system with libav59 libraries to test it on.

The fix looks good to me with one exception. You also need to add an entry for `"avplugin-ffmpeg-59"` in the [NativeMediaManager constructor](https://github.com/openjdk/jfx/blob/bb4cead00e952484896191ca0e41f1608ae5b41e/modules/javafx.media/src/main/java/com/sun/media/jfxmediaimpl/NativeMediaManager.java#L127).

**Comment by sashamatveev** [comment]
8294400: Provide media support for libavcodec version 59 [v2]
 - Added `avplugin-ffmpeg-59` in the NativeMediaManager constructor.

**Review by kevinrushforth — APPROVED** [review]

**Comment by kevinrushforth** [comment]
This needs a second reviewer.

**Comment by kevinrushforth** [comment]
@johanvos or @tiainen Do you want to test this? It should be a straight-forward update, but since it doesn't get run via GitHub actions, you might want to urn this in your CI. We've already run it on our CI.

**Comment by johanvos** [comment]
I'll build + do basic tests

**Comment by johanvos** [comment]
Works fine, but fails to build on win32.

**Comment by kevinrushforth** [comment]
> Works fine, but fails to build on win32.

That is surprising since the libav changes are limited to Linux-specific code. Have you confirmed that the win32 build passes without this fix and fails with this fix? How does it fail?

**Comment by johanvos** [comment]
> > Works fine, but fails to build on win32.
> 
> That is surprising since the libav changes are limited to Linux-specific code. Have you confirmed that the win32 build passes without this fix and fails with this fix? How does it fail?

Failures were CI-related. They are fixed now, and everything looks good.

**Review by johanvos — APPROVED** [review]

**Pull request closed without merging**
