### PR TITLE
8328716: [TestBug] Screen capturing utility for failed tests

### PR DESCRIPTION
**Pull request by andy-goryachev-oracle**
Created a JUnit5-compatible utility to capture screenshots of failed headful tests. The idea is that a certain annotation can be added to an intermittently failing test or a test that fails on a certain platform to capture the screenshot for debugging:

```
@ExtendWith(ScreenCaptureTestWatcher.class)
```

Screenshots of the primary screen will be captured in PNG format, encoded to a Base64 string, and logged to stderr.

A special utility is then needed to extract the actual screenshot image from the log file (I am thinking of Monkey Tester, but it can be a standalone app or a script).

## Questions

- stdout or stderr?
- do we need a separate decoder script or Monkey Tester is enough?
- should it emit a valid JSON segment to be compatible with any log viewer applications that understand JSON? i.e. `{ screenshot:"...base64..." }`

Example (partial) of the captured screenshot (in the dedicated viewer):

Screenshot 2024-03-22 at 12 45 41

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8328716](https://bugs.openjdk.org/browse/JDK-8328716): [TestBug] Screen capturing utility for failed tests (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1415/head:pull/1415` \
`$ git checkout pull/1415`

Update a local copy of the PR: \
`$ git checkout pull/1415` \
`$ git pull https://git.openjdk.org/jfx.git pull/1415/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1415`

View PR using the GUI difftool: \
`$ git pr show -t 1415`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1415.diff">https://git.openjdk.org/jfx/pull/1415.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
This needs some discussion before making it RFR. I have more questions than just the ones you listed about the design and implementation of such a feature.

**Comment by andy-goryachev-oracle** [comment]
what are the questions?

**Comment by andy-goryachev-oracle** [comment]
keep-alive; discuss-later;

**Comment by andy-goryachev-oracle** [comment]
keep-alive

**Comment by andy-goryachev-oracle** [comment]
has to wait for the next test sprint

**Pull request closed without merging**
