### PR TITLE
8321603: Bump minimum JDK version for JavaFX to JDK 21

### PR DESCRIPTION
**Pull request by kevinrushforth**
This PR bumps the minimum version of the JDK needed to run JavaFX to **JDK 21**.

In order for JavaFX to be able to use newer JDK features, such as code snippets (in API docs), record patterns, pattern matching for switch statements, and so forth, we need to increase the minimum version of the JDK required run the latest JavaFX. Additionally, there is an ongoing cost to keeping JavaFX buildable and runnable on older versions of Java, and little reason to continue to do so.

This is targeted to JavaFX 23, and must not be backported to any earlier version. This needs a CSR and a release note.

/reviewers 2
/csr

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change requires CSR request [JDK-8325993](https://bugs.openjdk.org/browse/JDK-8325993) to be approved
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issues
 * [JDK-8321603](https://bugs.openjdk.org/browse/JDK-8321603): Bump minimum JDK version for JavaFX to JDK 21 (**Enhancement** - P3)
 * [JDK-8325993](https://bugs.openjdk.org/browse/JDK-8325993): Bump minimum JDK version for JavaFX to JDK 21 (**CSR**)

### Reviewers
 * [Andy Goryachev](https://openjdk.org/census#angorya) (@andy-goryachev-oracle - **Reviewer**)
 * [Johan Vos](https://openjdk.org/census#jvos) (@johanvos - **Reviewer**)
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1370/head:pull/1370` \
`$ git checkout pull/1370`

Update a local copy of the PR: \
`$ git checkout pull/1370` \
`$ git pull https://git.openjdk.org/jfx.git pull/1370/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1370`

View PR using the GUI difftool: \
`$ git pr show -t 1370`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1370.diff">https://git.openjdk.org/jfx/pull/1370.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1370#issuecomment-1947312897)

### CODE REVIEW

**Comment by andy-goryachev-oracle** [comment]
Are there any special steps needed to re-configure github actions?
Are there any other dependencies?

**Review by andy-goryachev-oracle — APPROVED** [review]
combined (pr + master) builds on macOS 14.3

**Review by johanvos — APPROVED** [review]

**Review by prrace — APPROVED** [review]

**Comment by kevinrushforth** [comment]
> Are there any special steps needed to re-configure github actions?

No. We already bumped the boot JDK used to build JavaFX to JDK 21 a couple months ago (in the JavaFX 22 release).

> Are there any other dependencies?

Not that I know of.

**Pull request closed without merging**
