### PR TITLE
8286678: Fix mistakes in FX API docs

### PR DESCRIPTION
**Pull request by nlisker**
Fixes the mistakes in the JBS ticket and some additional minor corrections.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8286678](https://bugs.openjdk.org/browse/JDK-8286678): Fix mistakes in FX API docs

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx pull/877/head:pull/877` \
`$ git checkout pull/877`

Update a local copy of the PR: \
`$ git checkout pull/877` \
`$ git pull https://git.openjdk.org/jfx pull/877/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 877`

View PR using the GUI difftool: \
`$ git pr show -t 877`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/877.diff">https://git.openjdk.org/jfx/pull/877.diff</a>

</details>

### CODE REVIEW

**Comment by andy-goryachev-oracle** [comment]
Nir, have you sync'ed your branch with the latest master?  There are 5000+ files changed listed.

**Comment by nlisker** [comment]
It's a PR against the javafx19 branch. I think I forked the master branch though, which is why it is showing all the commits. I might need to rebase, but if the changes are approved it should integrate without issues.

**Comment by andy-goryachev-oracle** [comment]
you probably need to rebase.  impossible to review.

**Comment by kevinrushforth** [comment]
> It's a PR against the javafx19 branch. I think I forked the master branch though, which is why it is showing all the commits.

Yeah, this is a fairly easy mistake to make. It's also very obvious when it happens.

> I might need to rebase, but if the changes are approved it should integrate without issues.

You will definitely deed to rebase and force push before this can be reviewed. No, it otherwise won't integrate without issues.

/reviewers 2

**Comment by kevinrushforth** [comment]
I'll review it.

@arapte or @aghaisas Can one of you be the second reviewer?

**Comment by nlisker** [comment]
Looks like the rebase missed a few commits. Not sure why.

**Comment by kevinrushforth** [comment]
How did you do the rebase? It should be something like:

```
git fetch upstream
git rebase -i upstream/master
<remove all commits that came from the master branch>
```

Alternatively, you can `git reset --hard upstream/jfx19` to reset your branch, and then cherry pick all of the commits (or apply the aggregate diffs as one commit).

**Comment by kevinrushforth** [comment]
Oh, there is only a single unique commit in your branch (or rather there was before you rebased some of the commits from master), so the following should work:

```
git reset --hard upstream/jfx19
git cherry-pick 263061e366e5c7b4d0928b33d7bc4da90b9fa519
```

Check that there is only the one commit, and that the diffs look good:

```
git log upstream/jfx19..
git diff upstream/jfx19..
```

then force push.

**Comment by nlisker** [comment]
`git reset --hard upstream/jfx19`
That gives an error
```
fatal: ambiguous argument 'upstream/jfx19': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

I will close this PR and resubmit.

**Comment by nlisker** [comment]
#880 is the new PR.

**Comment by kevinrushforth** [comment]
> ```
> fatal: ambiguous argument 'upstream/jfx19': unknown revision or path not in the working tree.
> ```

I should have said "presuming you have a remote configured with the name `upstream`". Anyway, what you did was good.

**Pull request closed without merging**
