### PR TITLE
8269259: Remove obsolete apps, tests, and scripts

### PR DESCRIPTION
**Pull request by kevinrushforth**
This PR deletes the following applications, tests, and scripts that are either obsolete 
or unmaintained:

apps/performance/*

apps/tests/HelloTest

apps/toys/FXSlideShow
apps/toys/Industrial
apps/toys/Shape3DToy
apps/toys/StretchyGrid
apps/toys/TouchSuite

tests/functional/*
tests/performance/VMPerformance

tools/*

See the JBS issue and [this thread](https://mail.openjdk.java.net/pipermail/openjfx-dev/2021-June/030894.html) on the openjfx-dev mailing list for more info.

There are two commits for ease of review. The first one is generated by doing a "git rm -r" on each of the above listed directories. The second is to remove any remaining references to the removed directories.

/reviewers 2

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8269259](https://bugs.openjdk.java.net/browse/JDK-8269259): Remove obsolete apps, tests, and scripts

### Reviewers
 * [Nir Lisker](https://openjdk.java.net/census#nlisker) (@nlisker - **Reviewer**)
 * [Ambarish Rapte](https://openjdk.java.net/census#arapte) (@arapte - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/545/head:pull/545` \
`$ git checkout pull/545`

Update a local copy of the PR: \
`$ git checkout pull/545` \
`$ git pull https://git.openjdk.java.net/jfx pull/545/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 545`

View PR using the GUI difftool: \
`$ git pr show -t 545`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/545.diff">https://git.openjdk.java.net/jfx/pull/545.diff</a>

</details>

### CODE REVIEW

**Comment by nlisker** [comment]
I will review the eclipse file changes. I'm not sure what constitutes a review for removed files in the case where nothing depends on them.

**Review by nlisker — APPROVED** [review]
Looks fine. I don't know which of these are used frequently and which aren't, but I tested that there are no errors as a result of this patch.

Under tests/system/src there are several projects called "testappN". Are they named cryptically on purpose?

**Review by arapte — APPROVED** [review]
Build and sanity testing looks good.

**Comment by kevinrushforth** [comment]
> Under tests/system/src there are several projects called "testappN". Are they named cryptically on purpose?

Not really, no. They are all added to `build.gradle` as separate source sets [here](https://github.com/openjdk/jfx/blob/master/build.gradle#L3643), but we don't take advantage of the naming. They just need to be difference from the primary `test` source set.

**Pull request closed without merging**
