### PR TITLE
8232824: Removing TabPane with strong referenced content causes memory leak from weak one

### PR DESCRIPTION
**Pull request by arapte**
This PR is a fix for [JDK-8232824](https://bugs.openjdk.java.net/browse/JDK-8232824)
This issue is regression of [JDK-8187074](https://bugs.openjdk.java.net/browse/JDK-8187074).

Issue.
- `Parent.viewOrderChildren` is a list of children sorted according to view order.
- `Parent.viewOrderChildren` is cleared and computed in `Parent.computeViewOrderChildren()` which is called from `Parent.doUpdatePeer()` when a `pulse `is received.

- Below is the scenario mentioned in this issue,
1. `TabPane` is created with few `tabs`.
2. For each tab,  a `TabHeaderSkin` is created with `setViewOrder(1)` and is added to `TabHeaderArea.headersRegion`
3. All these `TabHeaderSkin`s are added to `Parent.viewOrderChildren` on `pulse`.
4. When the `TabPane` is removed from scene, then on the next pulse the method `Parent.doUpdatePeer()` does not get called for `TabHeaderArea.headersRegion`, because it is not part for scenegraph anymore.
So `Parent.computeViewOrderChildren()` does not get called and the `Parent.viewOrderChildren` does not get cleared, which causes the leak.

Fix:
Clear the `Parent.viewOrderChildren` list when marking `DirtyBits.PARENT_CHILDREN_VIEW_ORDER` as dirty.
`Parent.viewOrderChildren` will be computed on next `pulse`.
This will maintain lazy computation of `Parent.viewOrderChildren`. 

Added a system test, fails without fix and passes with. No failures in existing tests.

## Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

## Issue
[JDK-8232824](https://bugs.openjdk.java.net/browse/JDK-8232824): Removing TabPane with strong referenced content causes memory leak from weak one

## Approvers
 * Kevin Rushforth ([kcr](@kevinrushforth) - **Reviewer**)
 * Ajit Ghaisas ([aghaisas](@aghaisas) - **Reviewer**)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
@arapte - This bug looks like a good candidate for JavaFX 14. Can you retarget this PR to the jfx14 branch?

**Comment by kevinrushforth** [comment]
This will need a second reviewer.

@aghaisas can you review this, too?

**Comment by arapte** [comment]
> 
> 
> @arapte - This bug looks like a good candidate for JavaFX 14. Can you retarget this PR to the jfx14 branch?

Thanks for guiding Kevin, PR is now targeted to jfx14.

**Comment by kevinrushforth** [comment]
The fix looks good. I'll take a closer look at the unit test later.

Speaking of tests...since the addition of the `TabPane` reordering logic was a victim of the already-existing leak in the `viewOrderChildren` list in `Parent`, it should be possible to write a test case using a Group node and a few Shape nodes, using setViewOrder directly on the Group node (this would be in addition to the system test you wrote). Can you take a look at adding one? It might even be possible to do it as a `javafx.graphics` module unit test rather than a system test, although you would need to see if the bug reproduced there (I suspect it will).

**Comment by arapte** [comment]
> 
> 
> The fix looks good. I'll take a closer look at the unit test later.
> 
> Speaking of tests...since the addition of the `TabPane` reordering logic was a victim of the already-existing leak in the `viewOrderChildren` list in `Parent`, it should be possible to write a test case using a Group node and a few Shape nodes, using setViewOrder directly on the Group node (this would be in addition to the system test you wrote). Can you take a look at adding one? It might even be possible to do it as a `javafx.graphics` module unit test rather than a system test, although you would need to see if the bug reproduced there (I suspect it will).

Hello Kevin,
The bug can be reproduced with system test written using `Group` and `Shape` which is very similar to `TabPaneHeaderLeakTest` test. but it seems the bug is not reproducible with unit test. I tried a unit test very similar to the newly added system test `ShapeViewOrderLeakTest`, but looks like `Parent.viewOrderChildren` list does not get populated and so the issue does not occur.

**Comment by kevinrushforth** [comment]
> The bug can be reproduced with system test written using `Group` and `Shape` which is very similar to `TabPaneHeaderLeakTest` test. but it seems the bug is not reproducible with unit test. I tried a unit test very similar to the newly added system test `ShapeViewOrderLeakTest`, but looks like `Parent.viewOrderChildren` list does not get populated and so the issue does not occur.

Did you run a pulse? That would be needed in order to sync the changes down to the peer. In any event, it is fine to use a system test if you can't get it to fail with a unit test.

I have three cleanup comments that are apply to both of the new tests. The first is the most important of these.

1. Test classes should not extend from `javafx.application.Application`. You should use a nested class that extends Application. See [this comment on PR #34](https://github.com/openjdk/jfx/pull/34#pullrequestreview-322619657) for at least one reason why.

2. The initFX method can be simplified using a pattern we've adopted in our newer tests. See [QuadraticCssTimeTest.java](https://github.com/openjdk/jfx/blob/jfx14/tests/system/src/test/java/test/javafx/scene/QuadraticCssTimeTest.java#L84)

3. Most tests run `startupLatch::countDown` in a `Platform.runLater` call.

**Comment by arapte** [comment]
> Did you run a pulse? That would be needed in order to sync the changes down to the peer. In any event, it is fine to use a system test if you can't get it to fail with a unit test.
> 

Yes Kevin, I had tried using `Toolkit.getToolkit().firePulse();`. But the test did not fail without fix.
I am not sure if I am missing anything with unit test, Ideally it should reproduce with unit test too.

Have updated the PR to fix the other review comments.

**Pull request closed without merging**
