### PR TITLE
8260165: CSSFilterTest.testCSSFilterRendering system test fails

### PR DESCRIPTION
**Pull request by arun-Joseph**
Issue: Initial layout delay was removed and layout() is called from layoutTimer instead of WebPage::prePaint().

Fix: Re-introduce the initial layout delay.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8260165](https://bugs.openjdk.java.net/browse/JDK-8260165): CSSFilterTest.testCSSFilterRendering system test fails

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Guru Hb](https://openjdk.java.net/census#ghb) (@guruhb - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jfx pull/408/head:pull/408`
`$ git checkout pull/408`

### CODE REVIEW

**Comment by kevinrushforth** [comment]
This seems a safe enough fix to restore the layout delay that was removed in WebKit 610.2 (and which has caused a regression). Are there any drawbacks to doing this?

**Comment by arun-Joseph** [comment]
The only drawback would be layout is calculated in the next updateContent cycle instead of right after loading the first page, which is same as before WebKit 610.2. This would only cause a delay of a few milliseconds (~10 ms for this test).

**Review by kevinrushforth — APPROVED** [review]
Looks good. Tested on all three platforms.

**Comment by kevinrushforth** [comment]
@johanvos @guruhb can one of you be the second reviewer on this?

**Review by guruhb — APPROVED** [review]
Tested on Linux and Windows, Looks good to me.

**Pull request closed without merging**
