### PR TITLE
8227371: Drag&Drop while holding the CMD key does not work on macOS

### PR DESCRIPTION
**Pull request by beldenfox**
During a drag-and-drop operation on the Mac the Command key will filter out every drag source operation except `NSDragOperationGeneric` (this behavior is provided by the OS). JavaFX drag sources only set the Move, Copy, and Link drag operation bits so the Command key reduces the set of available operations to nothing.

This PR changes nothing about how JavaFX behaves when the dnd operation involves an external application. As a drag source the same set of operations will be broadcast and as a drag destination the operations will be interpreted as they have always been.

For internal dnd within the JavaFX app `NSDragOperationMove` and `NSDragOperationGeneric` will both be set if the drag source specifies `TransferMode.MOVE`. On the other end a drag destination will interpret `NSDragOperationGeneric` and `NSDragOperationMove` as synonyms.

As part of this PR it was necessary to verify that `NSDragOperationGeneric` was not already being used during an internal drag operation.  There's a clause in `mapJavaMaskToNsOperation:` which translates `com_sun_glass_ui_Clipboard_ACTION_ANY` to `NSDragOperationEvery` and this includes the Generic bit. I believe this is a red herring, the Java dnd code converts `TransferMode.ANY` to a bitwise-OR of COPY, MOVE, and REFERENCE so `com_sun_glass_ui_Clipboard_ACTION_ANY` will never be passed down to the platform level.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8227371](https://bugs.openjdk.java.net/browse/JDK-8227371): Drag&Drop while holding the CMD key does not work on macOS

### Reviewers
 * [Pankaj Bansal](https://openjdk.java.net/census#pbansal) (@pankaj-bansal - Committer)
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/651/head:pull/651` \
`$ git checkout pull/651`

Update a local copy of the PR: \
`$ git checkout pull/651` \
`$ git pull https://git.openjdk.java.net/jfx pull/651/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 651`

View PR using the GUI difftool: \
`$ git pr show -t 651`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/651.diff">https://git.openjdk.java.net/jfx/pull/651.diff</a>

</details>

### CODE REVIEW

**Review by pankaj-bansal — APPROVED** [review]
Looks good to me. I tested the testcase attached in JBS on macOS BigSur and I can see the move operation is selected if cmd key is pressed after the fix.

**Review by kevinrushforth — APPROVED** [review]
The fix looks good to me, too.

**Comment by kevinrushforth** [comment]
@beldenfox this is ready for you to integrate.

**Pull request closed without merging**
