### PR TITLE
8322703: Intermittent crash in WebView in a JFXPanel from IME calls on macOS

### PR DESCRIPTION
**Pull request by kevinrushforth**
As noted in the JBS bug, this is a follow-on to [JDK-8196011](https://bugs.openjdk.org/browse/JDK-8196011) that I discovered while testing the fix for [JDK-8221261](https://bugs.openjdk.org/browse/JDK-8221261) (a deadlock in the IME code when using WebView in a JFXPanel on macOS).

I have tested this in connection with with the proposed fix for JDK-8221261, although it is a valid fix regardless.

This expands the fix done in [JDK-8221261](https://bugs.openjdk.org/browse/JDK-8221261) to call all of the WebKit methods on the right thread. Additionally, we sometimes see spurious exceptions where the committed text is coming back as null, so I changed the log level to "fine" rather than "severe" for those exceptions. I'll file a follow-up bug  to see if any of these are real problems or not.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8322703](https://bugs.openjdk.org/browse/JDK-8322703): Intermittent crash in WebView in a JFXPanel from IME calls on macOS (**Bug** - P2)

### Reviewers
 * [Jay Bhaskar](https://openjdk.org/census#jbhaskar) (@jaybhaskar - Committer)
 * [Ambarish Rapte](https://openjdk.org/census#arapte) (@arapte - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1321/head:pull/1321` \
`$ git checkout pull/1321`

Update a local copy of the PR: \
`$ git checkout pull/1321` \
`$ git pull https://git.openjdk.org/jfx.git pull/1321/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1321`

View PR using the GUI difftool: \
`$ git pr show -t 1321`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1321.diff">https://git.openjdk.org/jfx/pull/1321.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1321#issuecomment-1879420819)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
@jaybhaskar Can you be one of the reviewers?

/reviewers 2

**Comment by kevinrushforth** [comment]
NOTE to reviewers: If you want to test this, you will also need the fix for [JDK-8221261](https://bugs.openjdk.org/browse/JDK-8221261), which is under review in PR #1327 to avoid the deadlock.

I have created a test branch that has both fixes:

https://github.com/kevinrushforth/jfx/tree/test-8221261-8322703

You can either fetch that branch or fetch both PR branches and build. It is not necessary to build the native WebKit if you have an up-to-date library in your cache.

**Comment by kevinrushforth** [comment]
Now that [JDK-8221261](https://bugs.openjdk.org/browse/JDK-8221261) is integrated you can just fetch this branch and no longer worry about the deadlock.

**Comment by kevinrushforth** [comment]
> Additionally, we sometimes see spurious exceptions where the committed text is coming back as null, so I changed the log level to "fine" rather than "severe" for those exceptions. I'll file a follow-up bug to see if any of these are real problems or not.

I decided to revert this change to the log level so as not to hide exceptions that might occur. They don't happen often, and we should report them when they do.

**Comment by kevinrushforth** [comment]
Reviewers: @arapte @jaybhaskar

**Review by jaybhaskar — APPROVED** [review]
+ looks good to me, tested on my machine

**Review by arapte — APPROVED** [review]

**Pull request closed without merging**
