### PR TITLE
8237889: Update libxml2 to version 2.9.10

### PR DESCRIPTION
**Pull request by arun-Joseph**
We currently use libxml2 version 2.9.9. We should update to the latest stable release 2.9.10.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8237889](https://bugs.openjdk.java.net/browse/JDK-8237889): Update libxml2 to version 2.9.10

### Reviewers
 * Kevin Rushforth ([kcr](@kevinrushforth) - **Reviewer**)
 * Johan Vos ([jvos](@johanvos) - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jfx pull/120/head:pull/120`
`$ git checkout pull/120`

### CODE REVIEW

**Comment by kevinrushforth** [comment]
@johanvos or @tiainen can one of you be the second reviewer. This isn't urgent, but we would like to get it in in the next week or two.

**Comment by johanvos** [comment]
This looks ok. I suggest to merge it sooner rather than later, so that we can create an EA built that has this code and have it tested.

**Pull request closed without merging**
