### PR TITLE
JDK-8295755 : Update SQLite to 3.39.4

### PR DESCRIPTION
**Pull request by HimaBinduMeda**
Updated sqlite to v3.39.4
Verified build on windows, linux and mac.
Sanity testing looks fine.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8295755](https://bugs.openjdk.org/browse/JDK-8295755): Update SQLite to 3.39.4

### Reviewers
 * [Ambarish Rapte](https://openjdk.org/census#arapte) (@arapte - **Reviewer**)
 * [Johan Vos](https://openjdk.org/census#jvos) (@johanvos - **Reviewer**)
 * [Jay Bhaskar](https://openjdk.org/census#jbhaskar) (@jaybhaskar - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx pull/953/head:pull/953` \
`$ git checkout pull/953`

Update a local copy of the PR: \
`$ git checkout pull/953` \
`$ git pull https://git.openjdk.org/jfx pull/953/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 953`

View PR using the GUI difftool: \
`$ git pr show -t 953`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/953.diff">https://git.openjdk.org/jfx/pull/953.diff</a>

</details>

### CODE REVIEW

**Review by arapte — APPROVED** [review]
Sanity testing looks good.

**Comment by johanvos** [comment]
Doing a test build + sanity tests

**Comment by johanvos** [comment]
Looks good on darwin-x86_64, linux and windows. Didn't test darwin-aarch64.

**Review by johanvos — APPROVED** [review]

**Review by jaybhaskar — APPROVED** [review]
+ looks ok to me

**Pull request closed without merging**
