### PR TITLE
8196079: Remove obsolete Pisces rasterizer

### PR DESCRIPTION
**Pull request by kevinrushforth**
This removes the obsolete OpenPiscesRasterizer (Java-based) and NativePiscesRasterizer implementations. The Marlin rasterizer was added in FX 9 and was made the default in FX 10. Marlin both outperforms Pisces and is more robust. There is no reason to keep the Pisces rasterizer(s) any more.

Note that the SW pipeline still has a Pisces-based renderer for the actual rendering of primitives. This is separate from the rasterizer and is not affected by this proposed fix.

I have tested this on Mac, Windows, and Linux.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8196079](https://bugs.openjdk.java.net/browse/JDK-8196079): Remove obsolete Pisces rasterizer

### Reviewers
 * Phil Race ([prr](@prrace) - **Reviewer**)
 * Laurent Bourgès ([lbourges](@bourgesl) - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jfx pull/268/head:pull/268`
`$ git checkout pull/268`

### CODE REVIEW

**Comment by bourgesl** [comment]
That's the case, michael.
In SWContext, the Marlin renderer is called to rasterize any shape.

See https://github.com/openjdk/jfx/pull/268/files#diff-28f93b00dc9cba7197f0a6c2fef022ed

**Comment by kevinrushforth** [comment]
I think you are conflating the rasterization step with the rendering step. In Prism the rasterization mainly includes clipping the shape and generating the mask data for the filled and/or stroked shape (the latter possibly being a wide and/or dashed stroke). The rasterized shape is then sent to the Prism GraphicsPipeline for drawing into the render target. This latter step is either done using shaders + D3D or OpenGL, or via the SW pipeline (or the J2D pipeline for printing). In the case of the SW pipeline, the renderer is based on code that was originally derived from Pisces, but it is distinct from the rasterization step that OpenPisces used to perform and Marlin now does perform. Take a look at the [SW pipeline](https://github.com/openjdk/jfx/tree/master/modules/javafx.graphics/src/main/java/com/sun/prism/sw) classes, the [Java PiscesRendering](https://github.com/openjdk/jfx/tree/master/modules/javafx.graphics/src/main/java/com/sun/pisces) classes, and the [prism-sw](https://github.com/openjdk/jfx/tree/master/modules/javafx.graphics/src/main/native-prism-sw) native code.

**Comment by bourgesl** [comment]
@kevinrushforth I asked skara JBS to associate my github account with my openjdk role... 
I will approve your PR once I have proper credentials.

Good job, 10k LOC removed.

I wonder if I should also deprecate the Float-precision Marlin renderer to remove 10k lines too.
The Double-precision Marlin renderer was enabled as the default renderer since JDK10, so it is doing the job properly, no reason to have 2 variants anymore and it will ease the maintenance.

Laurent

**Comment by kevinrushforth** [comment]
That's a good question about removing the single-precision float Marlin rasterizer. For desktop platforms, I see no reason to keep it. Perhaps Johan could weigh in as to whether their might be value in keeping it for some embedded platforms.

**Pull request closed without merging**
