### PR TITLE
8253351: MediaPlayer does not display an mp4 if there no speakers connected to the PC's

### PR DESCRIPTION
**Pull request by sashamatveev**
Fixed by not failing initialization if DSERR_NODRIVER is returned, which will be return if device is not present at all. Fixed format initialization even if DirectSound device was not created in case if audio device will arrive after playback started. Since we already handle correctly device arrival after playback started, audio will resume if device is enabled or USB audio card is plugged back. Due to lack of access to USB audio device, it was tested by disabling sound card via Device Manager, then starting playback (video plays, but not audio) and then enabling device and once enabled audio will start playing.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8253351](https://bugs.openjdk.java.net/browse/JDK-8253351): MediaPlayer does not display an mp4 if there no speakers connected to the PC's

### Reviewers
 * [Johan Vos](https://openjdk.java.net/census#jvos) (@johanvos - **Reviewer**)
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/586/head:pull/586` \
`$ git checkout pull/586`

Update a local copy of the PR: \
`$ git checkout pull/586` \
`$ git pull https://git.openjdk.java.net/jfx pull/586/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 586`

View PR using the GUI difftool: \
`$ git pr show -t 586`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/586.diff">https://git.openjdk.java.net/jfx/pull/586.diff</a>

</details>

### CODE REVIEW

**Comment by johanvos** [comment]
The linux test fails since https://github.com/openjdk/jfx/commit/b0d158629ed5f9c92cbcc39a7099f2d37e34ecf7 doesn't seem to be applied to this branch.

**Comment by kevinrushforth** [comment]
@sashamatveev Can you merge in the latest upstream master into your branch? That should fix the test failures as well as being easier to test.

/reviewers 2

**Review by johanvos — COMMENTED** [review]
Looks good. I will do builds and tests, but the idea seems ok. I can imagine it's very hard to have a unit or even system test for this.

**Review by kevinrushforth — APPROVED** [review]
Looks good to me. I didn't fully verify the fix on a system without speakers (although I did some limited testing), but did run a set of regression tests.

**Review by johanvos — APPROVED** [review]
Looks good. In the old and new code, there are some memory operations that I'm a little worried about, but as far as I can tell there are no changes related to that between the old and the new code -- at least I don't see a scenario where a free occurs now while it didn't occur before.

**Pull request closed without merging**
