### PR TITLE
8231188: Update SQLite to version 3.30.1

### PR DESCRIPTION
**Pull request by arun-Joseph**
We currently use SQLite version 3.28.0. We should update to the latest stable release version 3.30.1 released.
https://www.sqlite.org/index.html

## Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

## Issue
[JDK-8231188](https://bugs.openjdk.java.net/browse/JDK-8231188): Update SQLite to version 3.30.1

## Approvers
 * Kevin Rushforth ([kcr](@kevinrushforth) - **Reviewer**)
 * Johan Vos ([jvos](@johanvos) - **Reviewer**)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
This will need a second reviewer.

@johanvos @tiainen - could one of you be the second reviewer?

**Comment by johanvos** [comment]
Code changes look ok. Will test on 3 platforms later today.

**Pull request closed without merging**
