### PR TITLE
8284654: Modal behavior returns to wrong stage

### PR DESCRIPTION
**Pull request by tsayao**
When there's an APPLICATION_MODAL window, all other windows are disabled and re-enabled when the APPLICATION_MODAL window closes. This causes `requestToFront()` to be called on every window, and it does not guarantee order.

The fix also works for:
https://bugs.openjdk.java.net/browse/JDK-8269429

But this one might need another fix:
https://bugs.openjdk.java.net/browse/JDK-8240640

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer), 1 [Author](https://openjdk.java.net/bylaws#author))

### Issue
 * [JDK-8284654](https://bugs.openjdk.java.net/browse/JDK-8284654): Modal behavior returns to wrong stage

### Reviewers
 * [Ambarish Rapte](https://openjdk.java.net/census#arapte) (@arapte - **Reviewer**)
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/784/head:pull/784` \
`$ git checkout pull/784`

Update a local copy of the PR: \
`$ git checkout pull/784` \
`$ git pull https://git.openjdk.java.net/jfx pull/784/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 784`

View PR using the GUI difftool: \
`$ git pr show -t 784`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/784.diff">https://git.openjdk.java.net/jfx/pull/784.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
I'll take a look at it, and also ask @arapte to review. As you know from my comment in the bug report, I especially want to ensure that this causes no regressions, so need to test [JDK-8240640](https://bugs.openjdk.java.net/browse/JDK-8240640) on macOS.

/reviewers 2

**Comment by arapte** [comment]
This change fixes the exact issue that is reported in [JDK-8284654](https://bugs.openjdk.java.net/browse/JDK-8284654).

But I observed another issue that occurs with this change.
Steps:
1. Run the sample attached to [JDK-8284654](https://bugs.openjdk.java.net/browse/JDK-8284654).
2. Click button One and Two both once
3. Re-arrange both the windows such that they are visible.
4. Click the button "Click here" in Window Two: Error dialog will be displayed
5. Click anywhere in Window One
6. Close the Error dialog
 => Observe that Window One gets the focus and not Window Two.

I think the expected behavior here should be: After closing a dialog the Focus should return to its parent window.

**Comment by tsayao** [comment]
@arapte I think it's another bug on Linux, as the window should not accept focus when disabled, so it should not reorder windows when you click it ("Window One" on step 5).

Did you test it on Linux?

**Comment by tsayao** [comment]
Step 5 falls on:
```
    mainEnv->CallVoidMethod(jwindow, jWindowNotifyFocusDisabled);
```

which is correct, so might be a bug on java code.

**Comment by arapte** [comment]
> Did you test it on Linux?
I tested it on MacOS Catalina 10.15.7

> the window should not accept focus when disabled,
The window does not really gets the focus. The button cannot be clicked. but it does bring the window in foreground.

Yes, It may be a different bug. The similarity is that the focus does not go back to parent stage after closing the dialog.

**Comment by tsayao** [comment]
The test does not set the Window owner. It's one APPLICATION_MODAL window.

I have adjusted the PR to handle this case. It will set focus on the latest opened window when re-enabling, but will not change stacking order.

**Comment by arapte** [comment]
The original fix gets affected by the new commit.
Now, after closing dialog the focus always returns only to the stage that was created later.

1. Run the sample attached to [JDK-8284654](https://bugs.openjdk.java.net/browse/JDK-8284654).
2. Click button One and Two both once in order
3. Re-arrange both the windows such that they are visible.
4. Click the button "Click here" in Window One: Error dialog will be displayed
5. Close the Error dialog
=> Window Two gets focused but Window One should gets focused.
=> This worked correctly before the latest commit.

**Comment by arapte** [comment]
The original fix gets affected by the new commit.
Now, after closing dialog the focus always returns only to the stage that was created later.

1. Run the sample attached to [JDK-8284654](https://bugs.openjdk.java.net/browse/JDK-8284654).
2. Click button One and Two both once in order
3. Re-arrange both the windows such that they are visible.
4. Click the button "Click here" in Window One: Error dialog will be displayed
5. Close the Error dialog
=> Window Two gets focused but Window One should gets focused.
=> This worked correctly before the latest commit.

**Comment by arapte** [comment]
The fix look good to me.
The other behavior is observed on mac but not on windows. The platform behavior itself looks different. Not sure if should be captured in a JBS (at least for documentation purpose)

**Review by arapte — APPROVED** [review]

**Review by kevinrushforth — APPROVED** [review]
Looks good now.

**Pull request closed without merging**
