### PR TITLE
8261460: Incorrect CSS applied to ContextMenu on DialogPane

### PR DESCRIPTION
**Pull request by abhinayagarwal**
Both DialogPane and ContextMenu have a child node with a style-class `graphic-container`. This leads to a corner case where an unwanted style is applied to ContextMenu when it is shown on a DialogPane.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8261460](https://bugs.openjdk.java.net/browse/JDK-8261460): Incorrect CSS applied to ContextMenu on DialogPane

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Ajit Ghaisas](https://openjdk.java.net/census#aghaisas) (@aghaisas - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jfx pull/400/head:pull/400`
`$ git checkout pull/400`

### CODE REVIEW

**Comment by kevinrushforth** [comment]
This looks like a simple and safe fix, but I'd like a second reviewer for anything that touches the `modena.css` stylesheet.

/reviewers 2

**Review by kevinrushforth — APPROVED** [review]
Both the fix and the new tests look good to me. I can confirm that it fixes the test program attached to JBS, and that the new ContextMenu unit test fails before and passes after the fix.

**Review by aghaisas — APPROVED** [review]

**Pull request closed without merging**
