### PR TITLE
8342912: Remove calls to doPrivileged in fxml

### PR DESCRIPTION
**Pull request by andy-goryachev-oracle**
Removes `doPrivileged` in the following module:

* javafx.fxml

See JDK-8342441 for details.

As a helpful hint for reviewers, I recommend reviewing this using the "Hide whitespace" option.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8342912](https://bugs.openjdk.org/browse/JDK-8342912): Remove calls to doPrivileged in fxml (**Bug** - P3)

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Lukasz Kostyra](https://openjdk.org/census#lkostyra) (@lukostyra - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1610/head:pull/1610` \
`$ git checkout pull/1610`

Update a local copy of the PR: \
`$ git checkout pull/1610` \
`$ git pull https://git.openjdk.org/jfx.git pull/1610/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1610`

View PR using the GUI difftool: \
`$ git pr show -t 1610`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1610.diff">https://git.openjdk.org/jfx/pull/1610.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1610#issuecomment-2442035814)
</details>

### CODE REVIEW

**Review by kevinrushforth — APPROVED** [review]
/reviewers 2

**Comment by kevinrushforth** [comment]
@lukostyra Can you be the second reviewer?

**Review by lukostyra — APPROVED** [review]
LGTM

**Pull request closed without merging**
