### PR TITLE
8311124: [Windows] User installed font 8281327 fix does not work for all cases

### PR DESCRIPTION
**Pull request by prrace**
The problem is due to per-user install fonts on windows having full paths so they may be too long.
This is identical to the JDK fix that was done some time ago https://github.com/openjdk/jdk/pull/13359
I've tested that per-user fonts still work and so do the system-wide installed fonts.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8311124](https://bugs.openjdk.org/browse/JDK-8311124): [Windows] User installed font 8281327 fix does not work for all cases (**Bug** - P4)

### Reviewers
 * [Lukasz Kostyra](https://openjdk.org/census#lkostyra) (@lukostyra - Committer)
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1487/head:pull/1487` \
`$ git checkout pull/1487`

Update a local copy of the PR: \
`$ git checkout pull/1487` \
`$ git pull https://git.openjdk.org/jfx.git pull/1487/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1487`

View PR using the GUI difftool: \
`$ git pr show -t 1487`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1487.diff">https://git.openjdk.org/jfx/pull/1487.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1487#issuecomment-2187503939)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
Reviewers: @lukostyra @kevinrushforth 

/reviewers 2

**Review by lukostyra — APPROVED** [review]
Looks good, gave it a brief test and seems to introduce no regressions.

**Review by kevinrushforth — APPROVED** [review]
Looks good. I verified that the patch is the same as the corresponding JDK patch, which has been in production for almost a year.

**Pull request closed without merging**
