### PR TITLE
 8284184: Crash in GraphicsContextJava::drawLinesForText on https://us.yahoo.com/

### PR DESCRIPTION
**Pull request by jaybhaskar**
Issue: Floating point overflow , when making end point for line drawing as FloatPoint endPoint = startPoint + FloatPoint(widths.last(), 0);
Solution: traverse widths to calculate end point and increment start point.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8284184](https://bugs.openjdk.java.net/browse/JDK-8284184): Crash in GraphicsContextJava::drawLinesForText on https://us.yahoo.com/

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Ambarish Rapte](https://openjdk.java.net/census#arapte) (@arapte - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/765/head:pull/765` \
`$ git checkout pull/765`

Update a local copy of the PR: \
`$ git checkout pull/765` \
`$ git pull https://git.openjdk.java.net/jfx pull/765/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 765`

View PR using the GUI difftool: \
`$ git pr show -t 765`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/765.diff">https://git.openjdk.java.net/jfx/pull/765.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
I'll take a closer look at this next week. I see that you are reverting back to looping over the `widths` array, which will give a different visual result than the current code for dashed lines (of course, the current code, which was changed in [JDK-8280020](https://bugs.openjdk.java.net/browse/JDK-8280020), could be giving the wrong visual result in addition to causing the arithmetic overflow). Can you explain what the `widths` array represents? I also don't immediately see how this avoids the overflow, but that's another thing I'll look at.

/reviewers 2

**Comment by jaybhaskar** [comment]
The TextDecorationPainter class is responsible to call GraphicsContextJava::drawLinesForText. Before that GraphicsContextJava::drawLinesForText the TextDecorationPainter class compute the rect based on the text decoration style, text origin.

Before calling     GraphicsContextJava::drawLinesForText, The TextDecorationPainter class creates arrays of intersection points from rect.
       // using DashArray = Vector<DashArrayElement>;
        DashArray boundaries = translateIntersectionPointsToSkipInkBoundaries(intersections, underlineBoundingBox.height(), rect.width());


  m_context.drawLinesForText(rect.location(), rect.height(), boundaries, m_isPrinting, style == TextDecorationStyle::Double, strokeStyle);

So following code as fix

for (const auto& width : widths) {
        FloatPoint endPoint = startPoint + FloatPoint(width, 0);
        drawLine(
            IntPoint(startPoint.x(), startPoint.y()),
            IntPoint(endPoint.x(), endPoint.y()));
        startPoint = endPoint;
    }
avoid arithmetic overflow as in previous fix we were calculating end point FloatPoint endPoint = startPoint + FloatPoint(widths.last(), 0);

I have tested all style of line drawing , continuous , dashes , overflow  and underline , it is working well with the recent fix.

**Review by kevinrushforth — COMMENTED** [review]
I instrumented the code, and discovered that in the failing case, the list of `widths` is empty. I see that other implementations of GraphicsContext have a check for this at the beginning of the method, and do an early return in that case. That seems a good idea regardless. So I recommend adding this around line 345:

```
    if (widths.size() == 0)
        return;
```

That alone is sufficient to fix this bug.

As for the change to loop over the widths array, I'm not sure about that part. I see code in some of the ports that treat the widths array as pairs of start / end values, but that doesn't match what I see in a simple strike-through test case where there is only a single width value.

For the case of a simple underline (with or without dashing), the widths array is of length 2 with the first value being 0.0, which tends to support the definition used by the other ports. This will need more analysis.

So I think the simplest (and safest) fix is to just add the check for size == 0, but leave the drawing part of the code unchanged, and file a follow-up bug to investigate.

**Review by kevinrushforth — APPROVED** [review]
Looks good. I confirm that it fixes the crash. Can you file the follow-on bug to investigate our use of the `widths` list?

**Comment by jaybhaskar** [comment]
Yes, i will file a new follow up bug

**Pull request closed without merging**
