### PR TITLE
8193442: Removing TreeItem from a TreeTableView sometime changes selectedItem

### PR DESCRIPTION
**Pull request by jperedadnr**
This PR fixes JDK-[8193442](https://bugs.openjdk.java.net/browse/JDK-8193442), but also [JDK-8187596](https://bugs.openjdk.java.net/browse/JDK-8187596), and verifies that the tests mentioned in [JDK-8088157](https://bugs.openjdk.java.net/browse/JDK-8088157) are working (with a minor fix).

When removing an item that is below the selected item from TreeTableView or TreeView controls the selection and/or focus was wrongly changed in some occasions, because a shift in the selection was applied.

This PR adds a method to ControlUtils to get the index of the sibling that is selected/focused or contains the descendant item with the current selection/focus. 

This index is required to compare properly if the selected/focus item is above or below the item that was removed, by comparing the indices of siblings.

Tests have been added to TreeViewTest and TreeTableViewTest based on the existing tests on JDK-8193442 and JDK-8187596. The four tests fail without this PR, pass with it.

In the process, I noticed that the ignored tests referred from JDK-8088157 were already passing, after removing some obsolete asserts, even without this PR.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issues
 * [JDK-8193442](https://bugs.openjdk.java.net/browse/JDK-8193442): Removing TreeItem from a TreeTableView sometime changes selectedItem
 * [JDK-8187596](https://bugs.openjdk.java.net/browse/JDK-8187596): TreeView selection incorrectly changes after deleting an unselected row

### Reviewers
 * [Ajit Ghaisas](https://openjdk.java.net/census#aghaisas) (@aghaisas - **Reviewer**)
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/753/head:pull/753` \
`$ git checkout pull/753`

Update a local copy of the PR: \
`$ git checkout pull/753` \
`$ git pull https://git.openjdk.java.net/jfx pull/753/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 753`

View PR using the GUI difftool: \
`$ git pr show -t 753`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/753.diff">https://git.openjdk.java.net/jfx/pull/753.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
The GHA test failure on macOS was due to [JDK-8282449](https://bugs.openjdk.java.net/browse/JDK-8282449) and not anything in this PR. I filed a new bug to skip the failing tests until that bug can be fixed. See PR #754.

**Comment by jperedadnr** [comment]
@kevinrushforth Thanks for the test fix. Do I need to add a change in order to pass the tests again?

**Comment by jperedadnr** [comment]
@kevinrushforth Thanks, that worked and the tests pass (as it was expected).

**Review by aghaisas — APPROVED** [review]
Looks good to me.
Apart from the bug id in title, you can use `/issue` command to list additional issues this PR fixes.

**Review by kevinrushforth — APPROVED** [review]
Looks good.

> In the process, I noticed that the ignored tests referred from JDK-8088157 were already passing, after removing some obsolete asserts, even without this PR.

After this is integrated, can you close JDK-8088157 as "Cannot reproduce"?

**Pull request closed without merging**
