### PR TITLE
8303217: Webview loaded webpage is not showing play, volume related buttons for embeded Audio/Video elements

### PR DESCRIPTION
**Pull request by jaybhaskar**
Issue: default html5 video element not showing media controls
Details: Media control design has been refactored in the current Webkit Gtk port. The CSS id 
                and properties related to media buttons, and slider have been removed, due to which the 
                media style mediaControlsAdwaita.css values are not being applied.
Solution: restored media control keywords and mapped to CSS keywords values.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issues
 * [JDK-8303217](https://bugs.openjdk.org/browse/JDK-8303217): Webview loaded webpage is not showing play, volume related buttons for embeded Audio/Video elements
 * [JDK-8300954](https://bugs.openjdk.org/browse/JDK-8300954): HTML default Range input control not rendered

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Hima Bindu Meda](https://openjdk.org/census#hmeda) (@HimaBinduMeda - Committer)

### Contributors
 * Hima Bindu Meda `<hmeda@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx pull/1049/head:pull/1049` \
`$ git checkout pull/1049`

Update a local copy of the PR: \
`$ git checkout pull/1049` \
`$ git pull https://git.openjdk.org/jfx pull/1049/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1049`

View PR using the GUI difftool: \
`$ git pr show -t 1049`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1049.diff">https://git.openjdk.org/jfx/pull/1049.diff</a>

</details>

### CODE REVIEW

**Comment by jaybhaskar** [comment]
with this pr default media control works excluding slider, slider might be solved with range input bug  JDK-8300954

**Comment by kevinrushforth** [comment]
@HimaBinduMeda Can you be the second reviewer?

**Comment by kevinrushforth** [comment]
NOTE: This is a follow-on to [JDK-8301022](https://bugs.openjdk.org/browse/JDK-8301022) which was fixed in PR #1045

**Comment by kevinrushforth** [comment]
As a note to other reviewers, the fix for PR #1050 was folded into this fix. There were overlapping changes (merge conflicts), so it was easier to resolve them in a single PR.

**Review by kevinrushforth — APPROVED** [review]
Looks good. I've tested this on macOS and Windows and confirm that both bugs are fixed.

**Comment by HimaBinduMeda** [comment]
Looks good. I have verified unit tests and drt tests on mac and windows.
No issue seen.Slider and media controls are rendered properly.

**Review by HimaBinduMeda — APPROVED** [review]

**Pull request closed without merging**
