### PR TITLE
8211234: Open-source simple test programs for FX / Swing interop

### PR DESCRIPTION
**Pull request by jayathirthrao**
This PR is for open-sourcing 2 closed toys EmbeddedSwing and HelloWorld.
JBS : https://bugs.openjdk.org/browse/JDK-8211234

1)EmbeddedSwing - a simple FX test app with a SwingNode containing a Swing application

2)HelloWorld contains 2 test apps :

- HelloJFXPanel - a simple Swing test app with a JButton and a JFXPanel containing an animated rectangle

- HelloJFXPanel2 - a simple Swing test app with a JButton and a JFXPanel containing a JavaFX Button and ComboBox (with Tooltips) 

These new test apps are added under apps/toys/ directory.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8211234](https://bugs.openjdk.org/browse/JDK-8211234): Open-source simple test programs for FX / Swing interop (**Enhancement** - P4)

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1572/head:pull/1572` \
`$ git checkout pull/1572`

Update a local copy of the PR: \
`$ git checkout pull/1572` \
`$ git pull https://git.openjdk.org/jfx.git pull/1572/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1572`

View PR using the GUI difftool: \
`$ git pr show -t 1572`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1572.diff">https://git.openjdk.org/jfx/pull/1572.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1572#issuecomment-2356280152)

### CODE REVIEW

**Review by kevinrushforth — APPROVED** [review]
Looks good. The test programs build and run as expected.

**Comment by kevinrushforth** [comment]
I suspect that this might get a merge conflict when Skara notices it. I'll poke it.

/reviewers 1

**Comment by kevinrushforth** [comment]
Ah, never mind. I see that you already resolved the conflict. I'll re-review then.

**Review by kevinrushforth — APPROVED** [review]

**Comment by jayathirthrao** [comment]
> Ah, never mind. I see that you already resolved the conflict. I'll re-review then.

Yes Kevin, i was pushing the changes one after another because i was also suspecting merge conflict in apps/toys/build.xml

**Pull request closed without merging**
