### PR TITLE
8259555: Webkit crashes on Apple Silicon

### PR DESCRIPTION
**Pull request by arun-Joseph**
WebKit crashes during JavaScriptCore initialization code for Apple Silicon.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8259555](https://bugs.openjdk.java.net/browse/JDK-8259555): Webkit crashes on Apple Silicon

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Johan Vos](https://openjdk.java.net/census#jvos) (@johanvos - **Reviewer**)

### Contributors
 * Peter Zhelezniakov `<peterz@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/452/head:pull/452` \
`$ git checkout pull/452`

Update a local copy of the PR: \
`$ git checkout pull/452` \
`$ git pull https://git.openjdk.java.net/jfx pull/452/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 452`

View PR using the GUI difftool: \
`$ git pr show -t 452`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/452.diff">https://git.openjdk.java.net/jfx/pull/452.diff</a>

</details>

### CODE REVIEW

**Comment by johanvos** [comment]
This works, as long as MACOSX_MIN_VERSION is set to 11. I guess we don't want to commit that in the build.gradle, as we only require that for a build on Apple Silicon.

**Comment by kevinrushforth** [comment]
Any changes to minimum OS version in `mac.gradle` would need to be qualified by a check for the target architecture. It might make sense to do that in connection with other needed build changes.

**Review by kevinrushforth — APPROVED** [review]

**Review by johanvos — APPROVED** [review]
The other required changes required to build for M1 can easily be passed as build parameters using gradlew -P 
Hence, this change contains all that is needed to be changed in the repository.

**Pull request closed without merging**
