### PR TITLE
[WIP] 8257895: Allow building of JavaFX media libs for Apple Silicon

### PR DESCRIPTION
**Pull request by johanvos**
This requires updates to the 3th party libffi files, including some
restructuring of putting header files in source directories.

---------
### Progress
- [ ] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Download
`$ git fetch https://git.openjdk.java.net/jfx pull/402/head:pull/402`
`$ git checkout pull/402`

### CODE REVIEW

**Comment by kevinrushforth** [comment]
@sashamatveev You should be able to use this as a starting point.

**Comment by kevinrushforth** [comment]
@johanvos I think this can be closed now.

**Comment by johanvos** [comment]
@kevinrushforth do we close from the Github repo, or with a Skara command?

**Comment by kevinrushforth** [comment]
From the GitHub PR (just use the Close button).

**Pull request closed without merging**
