### PR TITLE
8262276: Debug build of WebKit fails

### PR DESCRIPTION
**Pull request by arun-Joseph**
Fixing the Debug build of WebKit.

Test: Build JavaFX using `-PCOMPILE_WEBKIT=true -PCONF=DebugNative` and test using a simple HelloWebView app.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8262276](https://bugs.openjdk.java.net/browse/JDK-8262276): Debug build of WebKit fails

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Johan Vos](https://openjdk.java.net/census#jvos) (@johanvos - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/417/head:pull/417` \
`$ git checkout pull/417`

Update a local copy of the PR: \
`$ git checkout pull/417` \
`$ git pull https://git.openjdk.java.net/jfx pull/417/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 417`

View PR using the GUI difftool: \
`$ git pr show -t 417`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/417.diff">https://git.openjdk.java.net/jfx/pull/417.diff</a>

</details>

### CODE REVIEW

**Comment by PrimosK** [comment]
Hi dear OpenJdk team,

At first I would like to thank you for looking into this. I am the author of original `8262276` ticket.

I would just like to share some additional information with you. I've fetched and checked out this pull request (`pull/417`) and tried to run the build once more inside exactly the same environment in which original `8262276` ticket was produced.

The build failed again. The only difference I can spot at this time is the line at which the build failed (it changed from 3445 to 3453):

```
* Where:
Build file 'C:\jfx-arun-joseph\build.gradle' line: 3453
```

Please let me know if you need any further information.

**Comment by kevinrushforth** [comment]
> The build failed again. The only difference I can spot at this time is the line at which the build failed (it changed from 3445 to 3453):
> ...
> 
> Please let me know if you need any further information.

You might be running into a different problem then, since this patch solve the compilation problem for Arun, for me, and for our CI build systems, when building with `-PCONF=DebugNative` (as a side note, we have some problems running the unit tests, but that's a separate issue). I have a couple questions for you:

1. Does the build work if you build without `-PCONF=DebugNative`? If it still fails, then you are definitely running into a different problem, likely something in your environment.

2. Can you double-check the versions of the build tools that you are using? We build using Visual Studio 2019 rather than the 2017 that you are using, although it will build with the latest VS2017 update. The versions of the other tools should be:
* gradle 6.3
* cmake 3.13.3
* ninja 1.8.2

3. Have you tried building on a platform other than Windows?

**Comment by johanvos** [comment]
when passing `--info` to gradle, the build succeeds. Without passing `--info` it fails. I'll do more testing later.

**Comment by PrimosK** [comment]
> > The build failed again. The only difference I can spot at this time is the line at which the build failed (it changed from 3445 to 3453):
> > ...
> > Please let me know if you need any further information.
> 
> You might be running into a different problem then, since this patch solve the compilation problem for Arun, for me, and for our CI build systems, when building with `-PCONF=DebugNative` (as a side note, we have some problems running the unit tests, but that's a separate issue). I have a couple questions for you:
> 
> 1. Does the build work if you build without `-PCONF=DebugNative`? If it still fails, then you are definitely running into a different problem, likely something in your environment.
> 2. Can you double-check the versions of the build tools that you are using? We build using Visual Studio 2019 rather than the 2017 that you are using, although it will build with the latest VS2017 update. The versions of the other tools should be:
> 
> * gradle 6.3
> * cmake 3.13.3
> * ninja 1.8.2
> 
> 1. Have you tried building on a platform other than Windows?

**1.**
No, it doesn't work. As already stated in the [JDK-8262276](https://bugs.openjdk.java.net/browse/JDK-8262276), the build fails for me with the exactly same error also when I set:
```
COMPILE_WEBKIT = true
CONF = Release
``` 
in `gradle.properties`.

**2.** 
ATM I am using these libraries:

- Javafx (`pull/417`)
- Java 15 (installed on Windows)
- Ant 1.10.5 (installed on Windows)
- **CMake 3.13.3** (installed on Windows)
- Visual Studio 2017 community edition (**Ninja 1.8.2**)
- **Gradlew 6.3**
- CygWin (installed on Windows) with the following packages:
  - bison 3.0.4-1
  - flex 2.6.4-2
  - gcc-g++ 10.2.0-1
  - git 2.30.0-1
  - gperf 3.1-1
  - make 4.3-1
  - makedepend 1.0.6-1
  - openssh 8.4p1-2
  - perl 5.32.1-1
  - python27 2.7.18-4
  - ruby 2.6.4-1
  - unzip 6.0-17
  - zip 3.0-12
  
But I am seeing exactly the same error.

**3.**
No - I've tried it only with Windows as we need debug symbols there... 

Side note: 

Could you guys please provide me with the versions of the above libraries that are used in the case of your CI build system?  Is now Visual Studio the only difference? I tried to check it by myself to go through the log files at https://github.com/arun-Joseph/jfx/runs/2028653928 but I couldn't found CygWin plugin versions (bison, flex...).

Tomorrow I will try building it using Visual Studio 2019.

**Comment by PrimosK** [comment]
Hi everyone,

Today I've tried to create a build using **Visual Studio 2019** but with no success. I am seeing the same error. 

There is a complete output of `./gradlew --scan`:
[build-output.txt](https://github.com/openjdk/jfx/files/6106294/build-output.txt)

The build scan is available there:
https://scans.gradle.com/s/dimrfirscg7hm

OS:
- Windows 10

Repository:
- JavaFx (pull/417)

Installed libraries:
- Java 15 (15+36-1562)
- Ant 1.10.5 
- Gradlew 6.3
- CMake 3.13.3
- Visual Studio 2019 community edition (VS2019-16.7.2+1.0)
- Ninja 1.8.2

CygWin (installed on Windows) with the following packages:
 - bison 3.0.4-1
 - flex 2.6.4-2
 - gcc-g++ 10.2.0-1
 - git 2.30.0-1
 - gperf 3.1-1
 - make 4.3-1
 - makedepend 1.0.6-1
 - openssh 8.4p1-2
 - perl 5.32.1-1
 - python27 2.7.18-4
 - ruby 2.6.4-1
 - unzip 6.0-17
 - zip 3.0-12

`gradle.properties`:
```
COMPILE_WEBKIT = true
CONF = DebugNative
```

Content of `windows.tools`:
```
WINDOWS_VS_DEVENVDIR=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE
WINDOWS_VS_DEVENVCMD=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/devenv.com
WINDOWS_VS_VCINSTALLDIR=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC
WINDOWS_VS_VSINSTALLDIR=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community
WINDOWS_VS_MSVCDIR=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC
WINDOWS_VS_INCLUDE=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/ATLMFC/include;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/include;C:/Program Files (x86)/Windows Kits/10/include/10.0.19041.0/ucrt;C:/Program Files (x86)/Windows Kits/10/include/10.0.19041.0/shared;C:/Program Files (x86)/Windows Kits/10/include/10.0.19041.0/um;C:/Program Files (x86)/Windows Kits/10/include/10.0.19041.0/winrt;C:/Program Files (x86)/Windows Kits/10/include/10.0.19041.0/cppwinrt;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/ATLMFC/include;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/include;C:/Program Files (x86)/Windows Kits/10/include/10.0.19041.0/ucrt;C:/Program Files (x86)/Windows Kits/10/include/10.0.19041.0/shared;C:/Program Files (x86)/Windows Kits/10/include/10.0.19041.0/um;C:/Program Files (x86)/Windows Kits/10/include/10.0.19041.0/winrt;C:/Program Files (x86)/Windows Kits/10/include/10.0.19041.0/cppwinrt
WINDOWS_VS_LIB=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/ATLMFC/lib/x64;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/lib/x64;C:/Program Files (x86)/Windows Kits/10/lib/10.0.19041.0/ucrt/x64;C:/Program Files (x86)/Windows Kits/10/lib/10.0.19041.0/um/x64;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/ATLMFC/lib/x86;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/lib/x86;C:/Program Files (x86)/Windows Kits/10/lib/10.0.19041.0/ucrt/x86;C:/Program Files (x86)/Windows Kits/10/lib/10.0.19041.0/um/x86
WINDOWS_VS_LIBPATH=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/ATLMFC/lib/x64;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/lib/x64;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/lib/x86/store/references;C:/Program Files (x86)/Windows Kits/10/UnionMetadata/10.0.19041.0;C:/Program Files (x86)/Windows Kits/10/References/10.0.19041.0;C:/Windows/Microsoft.NET/Framework64/v4.0.30319;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/ATLMFC/lib/x86;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/lib/x86;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/lib/x86/store/references;C:/Program Files (x86)/Windows Kits/10/UnionMetadata/10.0.19041.0;C:/Program Files (x86)/Windows Kits/10/References/10.0.19041.0;C:/Windows/Microsoft.NET/Framework/v4.0.30319
WINDOWS_VS_PATH=;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/Extensions/Microsoft/IntelliCode/CLI;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/HostX64/x64;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/VC/VCPackages;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/TestWindow;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/bin/Roslyn;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Team Tools/Performance Tools/x64;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Team Tools/Performance Tools;C:/Program Files (x86)/Microsoft Visual Studio/Shared/Common/VSPerfCollectionTools/vs2019/x64;C:/Program Files (x86)/Microsoft Visual Studio/Shared/Common/VSPerfCollectionTools/vs2019/;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/Tools/devinit;C:/Program Files (x86)/Windows Kits/10/bin/10.0.19041.0/x64;C:/Program Files (x86)/Windows Kits/10/bin/x64;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin;C:/Windows/Microsoft.NET/Framework64/v4.0.30319;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/Tools/;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/Extensions/Microsoft/IntelliCode/CLI;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/HostX86/x86;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/VC/VCPackages;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/TestWindow;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/bin/Roslyn;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Team Tools/Performance Tools;C:/Program Files (x86)/Microsoft Visual Studio/Shared/Common/VSPerfCollectionTools/vs2019/;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/Tools/devinit;C:/Program Files (x86)/Windows Kits/10/bin/10.0.19041.0/x86;C:/Program Files (x86)/Windows Kits/10/bin/x86;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin;C:/Windows/Microsoft.NET/Framework/v4.0.30319;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/Tools/;C:/cygwin64/usr/local/bin;C:/cygwin64/bin;C:/Windows/system32;C:/Windows;C:/Windows/System32/Wbem;C:/Windows/System32/WindowsPowerShell/v1.0;C:/Windows/System32/OpenSSH;C:/Program Files/CMake/bin;C:/Users/WDAGUtilityAccount/AppData/Local/Microsoft/WindowsApps;C:/Program Files/jdk-15/bin;C:/apache-ant-1.10.5/bin;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja
WINDOWS_VS_VER=150
WINDOWS_SDK_DIR=C:/Program Files (x86)/Windows Kits/10
WINDOWS_SDK_VERSION=10.0.19041.0
```

Side note:
Please let me know if I should rather discuss this through another channel (maybe mailing list?).

**Comment by PrimosK** [comment]
Update:
I've just found out there are few **_C1060: compiler is out of heap space_** in my log file so this might very well explain it.

**Comment by kevinrushforth** [comment]
> Please let me know if I should rather discuss this through another channel (maybe mailing list?).

If you still have problems after resolving your "out of heap space" issue, then asking on the [openjfx-dev](https://mail.openjdk.java.net/mailman/listinfo/openjfx-dev) mailing list is probably best, given that you are unable to compile WebKit even without `-PCONF=DebugNative`.

**Comment by kevinrushforth** [comment]
> when passing `--info` to gradle, the build succeeds. Without passing `--info` it fails. I'll do more testing later.

Interesting. I don't see this problem. I am able to build with or without `--info`. I am also now (with this patch) able to build with or without `-PCONF=DebugNative`.

As mentioned earlier, some of the unit tests fail to run in debug mode. Arun will look into these failures.

**Comment by PrimosK** [comment]
I think this is actually a lack of physical memory. I was doing tests inside Windows Sandbox which has 4GB of memory by default.

After repeating the build procedure inside VM with 16GB of memory the build succeeded.

Side question - I see there was:
C:\jfx\build\modular-sdk\modules_libs\javafx.web\jfxwebkit.dll
produced but I don't see any PDB files (debugging and project state information) despite `CONF = DebugNative` is present. Am I missing something?

**Comment by arun-Joseph** [comment]
The PDB files are located in `modules\javafx.web\build\win\Debug\bin\jfxwebkit.pdb`. At present, they are not copied to sdk. This bug (https://bugs.openjdk.java.net/browse/JDK-8263259) is created to fix the same.

**Comment by PrimosK** [comment]
@arun-Joseph , thanks. This is exactly where PDB files were located.

To give something back to the community I've prepared a script ([openjfx-build-env.zip](https://github.com/openjdk/jfx/files/6114811/openjfx-build-env.zip)) which installs [Chocolatey ](https://chocolatey.org/) and all required dependencies (for anyone who want to came up with `JavaFX` & `WebKit` build environment quickly - _please use at your own risk_). 

I suggest using dedicated/clean Windows 10 Virtual machine or Windows Sandbox (​[with 8GB memory](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file#memory-in-mb)).

Steps needed to create JavaFX build from JFX Github repository (with included pull/417):

1. Run `PowerShell` as `Administrator`

2. Run `openjfx-build-env.bat` (extracted from [openjfx-build-env.zip](https://github.com/openjdk/jfx/files/6114811/openjfx-build-env.zip))

3. Run `Cygwin`

4. Run (last two commands won't be needed anymore after this pull request will be merged to the master):
  
   `git clone https://github.com/openjdk/jfx.git` (from `C:`)

   `git fetch https://git.openjdk.java.net/jfx pull/417/head:pull/417`(from `C:/jfx`)

   `git checkout pull/417` (from `C:/jfx`)

5. OPTIONAL: Only if `WebKit` and native debug is needed:
   
   Edit `gradle.properties` (renamed from `gradle.properties.template`) inside `C:/jfx` and set:

   `COMPILE_WEBKIT = true`

   `CONF = DebugNative`

6. Run `chmod +x gradlew` (from `C:/jfx`)

7. Run `./gradlew --console=plain` (from `C:/jfx`)

Side notes:
 - Due to [JDK-8263259 https://bugs.openjdk.java.net/browse/JDK-8263259] bug , the PDB files will be placed inside `c:/jfx/modules/javafx.web/build/win/Debug/bin/jfxwebkit.pdb`.

**Review by kevinrushforth — APPROVED** [review]

**Review by johanvos — APPROVED** [review]
I can't reproduce my previous issues, so I assume there was something wrong with my local environment (which is likely).
Looks good now.

**Pull request closed without merging**
