### PR TITLE
8238526: Cherry pick GTK WebKit 2.26.3 changes

### PR DESCRIPTION
**Pull request by guruhb**
Fix contains https://webkitgtk.org/2020/01/22/webkitgtk2.26.3-released.html

## Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

## Issue
[JDK-8238526](https://bugs.openjdk.java.net/browse/JDK-8238526): Cherry pick GTK WebKit 2.26.3 changes

## Approvers
 * Kevin Rushforth ([kcr](@kevinrushforth) - **Reviewer**)
 * Johan Vos ([jvos](@johanvos) - **Reviewer**)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
As part of the review, I did a sanity build / test on all three platforms. All looks good.

**Comment by johanvos** [comment]
build and basic checks ok on mac/linux/win64. Didn't test on win32.

**Pull request closed without merging**
