### PR TITLE
8306648: Update the JavaDocs to show the NEW section and DEPRECATED versions

### PR DESCRIPTION
**Pull request by nlisker**
Adds the javadoc commands to generate the NEW page and to be able to select versions in the DEPRECATED page.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8306648](https://bugs.openjdk.org/browse/JDK-8306648): Update the JavaDocs to show the NEW section and DEPRECATED versions (**Enhancement** - P4)

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Andy Goryachev](https://openjdk.org/census#angorya) (@andy-goryachev-oracle - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1109/head:pull/1109` \
`$ git checkout pull/1109`

Update a local copy of the PR: \
`$ git checkout pull/1109` \
`$ git pull https://git.openjdk.org/jfx.git pull/1109/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1109`

View PR using the GUI difftool: \
`$ git pr show -t 1109`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1109.diff">https://git.openjdk.org/jfx/pull/1109.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1109#issuecomment-1517847902)

### CODE REVIEW

**Comment by nlisker** [comment]
Notes to reviewers:

1. The `-since` option does not play well with the javafx one: if documentation was added on a `private` property field with the `@since` tag, it will not be included in the NEW and DEPRECATED lists. I presume that the `-since` release version comparison detects only public APIs and does not know that javafx generates public API from private members.

    As an example, the attenuation properties in `PointLight` have `@since 16`, but do not appear in the NEW page.

2. I started from version 9, but there are also versions "8" and "8u20" in the deprecation list, and "JavaFX 8u40" and "JavaFX 8.0" in `@since` tags. For comparison, the JDK starts from 12 (https://docs.oracle.com/en/java/javase/20/docs/api/new-list.html). I'm not sure what versions we want to include. Changing this is simply done by adding the strings that appear in the tags to the `-since` option list.

**Comment by nlisker** [comment]
> 3. Each major release, a new version string will need to be added.

This can be solved by reading the major version directly from the properties file, but it would require to script the generation of the string that includes the versions.

**Comment by nlisker** [comment]
> @nlisker This pull request has been inactive for more than 4 weeks and will be automatically closed if another 4 weeks passes without any activity. To avoid this, simply add a new comment to the pull request. Feel free to ask for assistance if you need help with progressing this pull request towards integration!

Active

**Comment by kevinrushforth** [comment]
> 1. The `-since` option does not play well with the javafx one: if documentation was added on a `private` property field with the `@since` tag, it will not be included in the NEW and DEPRECATED lists. I presume that the `-since` release version comparison detects only public APIs and does not know that javafx generates public API from private members.

Confirmed. I can file a bug against the javadoc tool. This looks like one more place where they need to handle JavaFX properties.

> 2. I started from version 9, but there are also versions "8" and "8u20" in the deprecation list, and "JavaFX 8u40" and "JavaFX 8.0" in `@since` tags. For comparison, the JDK starts from 12 (https://docs.oracle.com/en/java/javase/20/docs/api/new-list.html). I'm not sure what versions we want to include. Changing this is simply done by adding the strings that appear in the tags to the `-since` option list.

I might recommend starting with 11, but I don't mind starting with 9 if others feel that's best.

/reviewers 2

**Comment by kevinrushforth** [comment]
@johanvos @andy-goryachev-oracle Do either of you have an opinion on this PR?

I'm especially interested in knowing whether we should include 9 and 10 in the (growing) list of versions shown in the NEW API section (they'll show up in the DEPRECATED section regardless).

See the attached screenshot.

javadoc-since

**Comment by Maran23** [comment]
> I am somewhat divided on which version to start with. On one hand, it makes sense to use last LTS version (or previous, if the current one is also LTS), so 17.

I think we should either start from 9 or 11.
Depending on the source, Java 11 is used more often than 8, which probably also means JavaFX 11+ is used more often than 8.

**Comment by kevinrushforth** [comment]
> > I am somewhat divided on which version to start with. On one hand, it makes sense to use last LTS version (or previous, if the current one is also LTS), so 17.
> 
> I think we should either start from 9 or 11. Depending on the source, Java 11 is used more often than 8, which probably also means JavaFX 11+ is used more often than 8.

I tend to agree that we should either start with 9 or 11. I can also see an argument for starting with 12 like the JDK did, but I am not in favor of that, given that this is the first time we are introducing the NEW section.

If we think that most new readers of these docs will be coming from JDK 8, then **NEW since 9** makes the most sense. Worth noting, though, is that FX was bundled with the JDK in 8 and 9 (and 10) -- JavaFX 11 was the first unbundled release, which would argue for **NEW since 11**.

Another argument for starting with 9 is that the reader who is just interested in what's new since 11 can simply uncheck 9 and 10 and get that view. So if there is some value in presenting new in 9, that argues for starting with 9. Unless someone feels strongly that we shouldn't, let's stick with 9.

**Comment by kevinrushforth** [comment]
> > The `-since` option does not play well with the javafx one: if documentation was added on a `private` property field with the `@since` tag, it will not be included in the NEW and DEPRECATED lists.
> 
> Confirmed. I can file a bug against the javadoc tool. This looks like one more place where they need to handle JavaFX properties.

I filed [JDK-8309765](https://bugs.openjdk.org/browse/JDK-8309765) to track this.

**Review by kevinrushforth — APPROVED** [review]

**Pull request closed without merging**
