### PR TITLE
8295324: JavaFX: Blank pages when printing

### PR DESCRIPTION
**Pull request by eduardsdv**
This fixes a race condition between application and 'Print Job Thread' threads when printing.

The race condition occurs when application thread calls `endJob()`, which in effect sets the `jobDone` flag to true,
and when the 'Print Job Thread' thread was in the `synchronized` block in `waitForNextPage()` at that time.
The 'Print Job Thread' thread checks `jobDone` flag after exiting the `synchronized` block and, if it is true, skips the last page.

In this fix, not only the `jobDone` is checked, but also that there is no other page to be printed.
It was also needed to introduce a new flag 'jobCanceled', to skip the page if the printing was canceled by 'cancelJob()'.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8295324](https://bugs.openjdk.org/browse/JDK-8295324): JavaFX: Blank pages when printing

### Reviewers
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx pull/916/head:pull/916` \
`$ git checkout pull/916`

Update a local copy of the PR: \
`$ git checkout pull/916` \
`$ git pull https://git.openjdk.org/jfx pull/916/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 916`

View PR using the GUI difftool: \
`$ git pr show -t 916`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/916.diff">https://git.openjdk.org/jfx/pull/916.diff</a>

</details>

### CODE REVIEW

**Comment by eduardsdv** [comment]
It seems that not all errors were fixed with this PR. Yesterday, a blank page was printed again. I will analyze what this can be due to.

**Comment by eduardsdv** [comment]
I found the second place with the race condition. It was in the print(Graphics g, PageFormat pf, int pageIndex) method.
Also here "jobDone" was checked without checking if a page was pending.

Please review.

**Comment by kevinrushforth** [comment]
@prrace Can you review this?

**Comment by eduardsdv** [comment]
Can someone else check this PR if @prace is not available?

**Comment by prrace** [comment]
I think this is OK, but whilst I can see you went to some lengths to create a test case, I do not think it justifies
the refactoring you had to do in order to create the test program.
So I'd prefer that ALL refactoring be reverted, even if it means no test program.

**Comment by eduardsdv** [comment]
Ok. I have reverted all changes regarding refactoring and testing.

**Review by prrace — APPROVED** [review]

**Review by kevinrushforth — APPROVED** [review]

**Pull request closed without merging**
