### PR TITLE
8263095: Provide a way for a custom control to indicate that its userAgentStyleSheet has changed

### PR DESCRIPTION
**Pull request by palexdev**
This change allows custom control to change their style dynamically
When the user-agent stylesheet changes the property automatically calls `NodeHelper.reapplyCSS(Region.this);` to recompute the CSS for the node and its children.
To make this work the StyleManager class must be fixed too.
The line `regionUserAgentStylesheet = weakRegionUserAgentStylesheetMap.computeIfAbsent((Region)region, Region::getUserAgentStylesheet);
` is problematic because if the region is already present in the map but the user-agent stylesheet changed, the value of `regionUserAgentStylesheet` is not updated and this leads to controls having the wrong style.
To fix this issue I added this check:
```
if (((Region) region).getUserAgentStylesheet() != null && !((Region) region).getUserAgentStylesheet().equals(regionUserAgentStylesheet)) {
    weakRegionUserAgentStylesheetMap.put((Region) region, ((Region) region).getUserAgentStylesheet());
    regionUserAgentStylesheet = ((Region) region).getUserAgentStylesheet();
}

```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change requires a CSR request matching fixVersion (No fixVersion in .jcheck/conf) to be approved (needs to be created)
- [ ] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8263095](https://bugs.openjdk.org/browse/JDK-8263095): Provide a way for a custom control to indicate that its userAgentStyleSheet has changed

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx pull/525/head:pull/525` \
`$ git checkout pull/525`

Update a local copy of the PR: \
`$ git checkout pull/525` \
`$ git pull https://git.openjdk.org/jfx pull/525/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 525`

View PR using the GUI difftool: \
`$ git pr show -t 525`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/525.diff">https://git.openjdk.org/jfx/pull/525.diff</a>

</details>

### CODE REVIEW

**Comment by palexdev** [comment]
@nlisker Hello, sorry I'm new to contributions, my OCA has been approved recently
I have read the CSR FAQ but I don't understand where I should go to create it

**Comment by nlisker** [comment]
Don't worry about the CSR for now, someone will create it when the review is near completion. However, since this is an enhancement, you should discuss it first in the mailing list as explained in the README file of the repo.

**Comment by kevinrushforth** [comment]
> Don't worry about the CSR for now, someone will create it when the review is near completion. However, since this is an enhancement, you should discuss it first in the mailing list as explained in the README file of the repo.

Exactly. The discussion should happen on openjfx-dev@openjdk.java.net. Specifically, the place to start is with the newly proposed API and behavioral changes. This is what is important to get general agreement / buy-in on. Any newly proposed public methods need to be clearly documented and justified. Also, there needs to be a discussion as to whether this change in behavior should be done unconditionally, which the current PR proposes to do, or whether this behavior should be "opt in".

Since we haven't yet had the discussion, this PR is not yet ready to be reviewed. It can be used for illustrative purposes as long as the focus is on the public API and behavioral changes and not (yet anyway) on the code.

**Comment by kevinrushforth** [comment]
Moving this to `Draft` to make it clear that it isn't yet ready for review.

**Pull request closed without merging**
