### PR TITLE
8302684 : Cherry-pick WebKit 615.1 stabilization fixes (2)

### PR DESCRIPTION
**Pull request by HimaBinduMeda**
Stabilization fixes from Webkitgtk-2.38.5.
Verified drt and unit tests. No issues observed.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8302684](https://bugs.openjdk.org/browse/JDK-8302684): Cherry-pick WebKit 615.1 stabilization fixes (2)

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Joeri Sykora](https://openjdk.org/census#sykora) (@tiainen - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx pull/1038/head:pull/1038` \
`$ git checkout pull/1038`

Update a local copy of the PR: \
`$ git checkout pull/1038` \
`$ git pull https://git.openjdk.org/jfx pull/1038/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1038`

View PR using the GUI difftool: \
`$ git pr show -t 1038`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1038.diff">https://git.openjdk.org/jfx/pull/1038.diff</a>

</details>

### CODE REVIEW

**Review by kevinrushforth — APPROVED** [review]
Looks good. Testing is green.

**Comment by kevinrushforth** [comment]
@tiainen or @johanvos could one of you be the second reviewer?

**Review by tiainen — APPROVED** [review]
Building and testing completed without issues.

**Pull request closed without merging**
