### PR TITLE
Remove a stray semicolon

### PR DESCRIPTION
**Pull request by elliotcm**
I've read the contributing guidelines and I acknowledge that I'm not following any of them, but this is such a tiny change it seemed excessive.

Do please let me know if it's a hard requirement and I'll go through the paperwork.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Error
&nbsp;⚠️ OCA signatory status must be verified

### Download
`$ git fetch https://git.openjdk.java.net/jfx pull/377/head:pull/377`
`$ git checkout pull/377`

### CODE REVIEW

**Comment by nlisker** [comment]
You must sign the OCA and submit an issue in JBS (or have someone do it for you) if you want this PR to be integrated.

Since this is such a small fix, it can be lumped into [JDK-8252389](https://bugs.openjdk.java.net/browse/JDK-8252389) for example and save the trouble.

**Comment by elliotcm** [comment]
@nlisker To clarify, do I need an account on JBS to open a new issue, or is submitting an issue through bugreport.java.com sufficient?

**Comment by nlisker** [comment]
Yes, bugreport.java.com is the way to go. It will take a few days for it to appear in JBS. If you want, I can create it for you immediately.

Note that generally we don't take such small requests because it's more hassle than it's worth, but I can take care of this one.

**Comment by elliotcm** [comment]
> Yes, bugreport.java.com is the way to go. It will take a few days for it to appear in JBS. If you want, I can create it for you immediately.

Thanks.  I'm happy to do it, but if you'd prefer to then by all means.

> Note that generally we don't take such small requests because it's more hassle than it's worth, but I can take care of this one.

It's a shame that bureaucracy can get in the way of quick improvements :(

**Comment by nlisker** [comment]
> Thanks. I'm happy to do it, but if you'd prefer to then by all means.

Then go ahead and do it. It will take time for your OCA to be approved anyway, so it won't delay you much.

> It's a shame that bureaucracy can get in the way of quick improvements :(

It's not only bureaucracy , it's the reviewers' time and things like possible merge conflict.

**Comment by elliotcm** [comment]
True.

**Comment by kevinrushforth** [comment]
Closing, since we do not have a confirmed OCA.

**Pull request closed without merging**
