### PR TITLE
8264137: Suppress deprecation and removal warnings of internal methods

### PR DESCRIPTION
**Pull request by aghaisas**
This PR suppresses -PLINT="removal" warnings and fixes -PLINT="deprecation" warnings. I have created separate commits for each type of warnings for the ease of review.

`gradle --info -PLINT="deprecation,removal"` -- results in warnings during build without this PR and results in no warnings with this PR.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issues
 * [JDK-8264137](https://bugs.openjdk.java.net/browse/JDK-8264137): Suppress deprecation and removal warnings of internal methods
 * [JDK-8252820](https://bugs.openjdk.java.net/browse/JDK-8252820): Skins: cleanup use of deprecated snapSize/snapPosition

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Marius Hanl](https://openjdk.java.net/census#mhanl) (@Maran23 - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/538/head:pull/538` \
`$ git checkout pull/538`

Update a local copy of the PR: \
`$ git checkout pull/538` \
`$ git pull https://git.openjdk.java.net/jfx pull/538/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 538`

View PR using the GUI difftool: \
`$ git pr show -t 538`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/538.diff">https://git.openjdk.java.net/jfx/pull/538.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
I tested this patch, and verified that it does eliminate the deprecation and removal warnings when building the sdk.

There are still a few warnings when compiling the tests. I ran the following command:

```
$ gradle --continue --info -PLINT="deprecation,removal" test
```

I get the following deprecation warnings:

```
modules\javafx.graphics\src\shims\java\javafx\scene\input\GestureEventShim.java:48: warning: [deprecation] GestureEvent(Object,EventTarget,EventType<? extends GestureEvent>) in GestureEvent has been deprecated
modules\javafx.graphics\src\test\java\test\javafx\css\StylesheetTest.java:628: warning: [deprecation] toURL() in File has been deprecated
modules\javafx.graphics\src\test\java\test\javafx\scene\Scenegraph_eventHandlers_Test.java:342: warning: [deprecation] EventType() in EventType has been deprecated
modules\javafx.controls\src\test\java\test\javafx\scene\chart\XYChartTest.java:92: warning: [deprecation] set(S,V,StyleOrigin) in CssMetaData has been deprecated
modules\javafx.controls\src\test\java\test\javafx\scene\control\LabeledTest.java:768: warning: [deprecation] set(S,V,StyleOrigin) in CssMetaData has been deprecated
modules\javafx.controls\src\test\java\test\javafx\scene\control\TreeItemTest.java:201: warning: [deprecation] getNodeLevel(TreeItem<?>) in TreeView has been deprecated
modules\javafx.controls\src\test\java\test\javafx\scene\control\TreeItemTest.java:208: warning: [deprecation] getNodeLevel(TreeItem<?>) in TreeView has been deprecated
modules\javafx.controls\src\test\java\test\javafx\scene\control\TreeItemTest.java:217: warning: [deprecation] getNodeLevel(TreeItem<?>) in TreeView has been deprecated
modules\javafx.controls\src\test\java\test\javafx\scene\control\TreeItemTest.java:231: warning: [deprecation] getNodeLevel(TreeItem<?>) in TreeView has been deprecated
modules\javafx.controls\src\test\java\test\javafx\scene\control\TreeItemTest.java:232: warning: [deprecation] getNodeLevel(TreeItem<?>) in TreeView has been deprecated
modules\javafx.fxml\src\test\java\test\com\oracle\javafx\fxml\test\TestLoadPerformance.java:107: warning: [deprecation] XMLReaderFactory in org.xml.sax.helpers has been deprecated
tests\system\src\test\java\test\robot\com\sun\glass\ui\monocle\input\devices\TestTouchDevices.java:46: warning: [deprecation] newInstance() in Class has been deprecated
tests\system\src\test\java\test\robot\javafx\embed\swing\JFXPanelTest.java:95: warning: [deprecation] BUTTON1_MASK in InputEvent has been deprecated
tests\system\src\test\java\test\robot\javafx\embed\swing\JFXPanelTest.java:96: warning: [deprecation] BUTTON1_MASK in InputEvent has been deprecated
tests\system\src\test\java\test\robot\javafx\embed\swing\NonFocusableJFXPanelTest.java:74: warning: [deprecation] BUTTON1_MASK in InputEvent has been deprecated
tests\system\src\test\java\test\robot\javafx\embed\swing\NonFocusableJFXPanelTest.java:75: warning: [deprecation] BUTTON1_MASK in InputEvent has been deprecated
```

and the following removal warnings:

```
modules\javafx.base\src\shims\java\javafx\util\converter\DateTimeStringConverterShim.java:34: warning: [removal] timeStyle in DateTimeStringConverter has been deprecated and marked for removal
modules\javafx.base\src\shims\java\javafx\util\converter\DateTimeStringConverterShim.java:38: warning: [removal] pattern in DateTimeStringConverter has been deprecated and marked for removal
modules\javafx.base\src\shims\java\javafx\util\converter\DateTimeStringConverterShim.java:42: warning: [removal] dateStyle in DateTimeStringConverter has been deprecated and marked for removal
modules\javafx.base\src\shims\java\javafx\util\converter\DateTimeStringConverterShim.java:46: warning: [removal] getDateFormat() in DateTimeStringConverter has been deprecated and marked for removal
modules\javafx.base\src\shims\java\javafx\util\converter\DateTimeStringConverterShim.java:50: warning: [removal] dateFormat in DateTimeStringConverter has been deprecated and marked for removal
modules\javafx.base\src\shims\java\javafx\util\converter\DateTimeStringConverterShim.java:54: warning: [removal] locale in DateTimeStringConverter has been deprecated and marked for removal
```

You can either fix it as part of this bug fix or else file a follow-on bug for the tests.

**Comment by kevinrushforth** [comment]
I'd like a second pair of eyes on this. The changes are very straight-forward, but there are a lot of them and it would be easy to have a copy-paste error and use `snapSizeX` instead of `snapSizeY` or vice versa.

/reviewers 2

**Review by kevinrushforth — APPROVED** [review]
Looks good.

**Review by Maran23 — APPROVED** [review]
Looks good. I double checked the snapSizeX/Y and snapPositionX/Y methods, I didn't found any location where the wrong method is used.
Good to see that all deprecated snapSize/snapPosition usages are finally replaced. :)

Btw, it looks like this PR also resolves: https://bugs.openjdk.java.net/browse/JDK-8252820
So this ticket can be either added to the issues this PR resolves or be closed.

**Comment by aghaisas** [comment]
> You can either fix it as part of this bug fix or else file a follow-on bug for the tests.

Thanks for reporting these warnings. I will fix them as part of the same PR.

**Review by kevinrushforth — APPROVED** [review]
Test changes look good, too.

**Review by Maran23 — APPROVED** [review]
Looks good. 👍

**Pull request closed without merging**
