### PR TITLE
8241476: Linux build warnings issued on gcc 9

### PR DESCRIPTION
**Pull request by tsayao**
Simple fix to remove annoying warnings.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8241476](https://bugs.openjdk.java.net/browse/JDK-8241476): Linux build warnings issued on gcc 9

### Reviewers
 * Kevin Rushforth ([kcr](@kevinrushforth) - **Reviewer**)
 * Ambarish Rapte ([arapte](@arapte) - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jfx pull/150/head:pull/150`
`$ git checkout pull/150`

### CODE REVIEW

**Comment by tsayao** [comment]
Like this?

I think all C builds are covered. Gstreamer seems to have a Makefile with the flags. Not sure about libxml and libxlst inside javafx.web.

**Comment by johanvos** [comment]
I think it's better to split the flags between CFLAGS and CPPFLAGS (as is done in OpenJDK). The `-Werror=implicit-function-declaration` is extremely useful for C files, and we don't want to risk that this somehow got lost.
If we use CFLAGS and CPPFLAGS, we can pass the latter as CXXFLAGS to cmake, so that should be fairly easy.

**Comment by kevinrushforth** [comment]
I took a look yesterday and came to the same conclusion that what we really want are separate C and C++ flags. For now, the only difference would be the presence or absence of `-Werror=implicit-function-declaration`, but it would allow for other differences in the future if needed.

**Comment by tsayao** [comment]
Please, let me know if this is the desired way to do it. If not, I will rework it. Thanks.

**Comment by kevinrushforth** [comment]
This is roughly what I had in mind. I want to test it, and also take a look at the WebKit and media builds as well. WebKit uses the flags from `linux.gradle`, and is mostly C++, so I think it needs no changes. Media does not use any flags from `linux.gradle` -- only the jfxmedia project has C++ files on Linux. I guess it should be fine, too, but I'll see.

**Comment by tsayao** [comment]
Done.

**Comment by kevinrushforth** [comment]
@johanvos or @arapte Can one of you be the second reviewer on this?

**Comment by arapte** [comment]
After this change below c files would be compiled without  `-Werror=implicit-function-declaration` option.
modules/javafx.media/src/main/native/jfxmedia/Utils/ColorConverter.c

modules/javafx.graphics/src/main/native-glass/gtk/wrapped.c
modules/javafx.graphics/src/main/native-glass/gtk/launcher.c

This can be addressed in follow on issue. Recording the files here for track.
Looks good to me.

**Pull request closed without merging**
