### PR TITLE
8088739: [TestBug] RegionBackgroundImageUITest fail with timeout error

### PR DESCRIPTION
**Pull request by arapte**
Each test in RegionBackgroundImageUITest makes several calls to `robot.getPixelColor()` on App thread. Due to this each test requires more than **60** seconds for execution.

Fix is to save a screen capture of Scene (on App thread) and then read pixel color from the screen capture(not on app thread). This reduces execution time of each test to less than **3** seconds.
Ideally with this fix(commit#1) all the tests should pass. All tests do pass on Windows and Linux but three tests fail on Mac, which used to pass without this change.
- RegionBackgroundImageUITest.unalignedImage
- RegionBackgroundFillUITest.testScenario2
- RegionBackgroundFillUITest.testScenario3

commit#2 solves the above problem. Solution is to fallback to test color again by reading it using `robot.getPixelColor()` on App thread when a test fails.

One test RegionBackgroundImageUITest.unalignedImage_Cover, fails only on Mac platform, before and after this fix.
It is reported as a new issue [JDK-8255679](https://bugs.openjdk.java.net/browse/JDK-8255679)

This is a test fix and affects only the tests that extend from `RegionUITestBase` test class and does not affect other tests.
Verified that `RegionBackgroundImageUITest` and `RegionBackgroundFillUITest` tests pass on all three platforms(except RegionBackgroundImageUITest.unalignedImage_Cover which fails on Mac).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8088739](https://bugs.openjdk.java.net/browse/JDK-8088739): [TestBug] RegionBackgroundImageUITest fail with timeout error

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/344/head:pull/344` \
`$ git checkout pull/344`

Update a local copy of the PR: \
`$ git checkout pull/344` \
`$ git pull https://git.openjdk.java.net/jfx pull/344/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 344`

View PR using the GUI difftool: \
`$ git pr show -t 344`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/344.diff">https://git.openjdk.java.net/jfx/pull/344.diff</a>

</details>

### CODE REVIEW

**Review by kevinrushforth — CHANGES_REQUESTED** [review]
The fact that you needed to implement a fallback to `Robot::getPixelColor` if reading a pixel from the buffer obtained by `Robot::getScreenCapture` fails (on Mac) suggests that `RegionBackgroundImageUITest` has some issues running on HiDPI displays. It also points out that there is a difference between the scaling algorithm used to read a single pixel vs an array of pixels (this might be a bug in Robot itself).

I confirmed the fact that these problems are related to HiDPI scaling by running it on my Windows 10 system with 125% scaling, and I get 30 test failures. I instrumented the code and I see a couple hundred fallbacks per test even for the non-failing tests. If I force screen scale to 1 on Windows then all tests pass with no fallbacks.

We used to have this problem for some of the tests in `RegionBackgroundFillUITest` as well. The fix for [JDK-8170026](https://bugs.openjdk.java.net/browse/JDK-8170026) addressed this by skipping the tests that were sensitive to screen scale (14 of them).  You either need to do something similar for `RegionBackgroundImageUITest` or else fix the tests to work with different screen scales (this would be challenging).

**Comment by arapte** [comment]
Following tests fail on windows with non-integer screen scale.

**30** tests fail with **125%** scale,	
    alignedImage
    alignedImage_Contain
    alignedImage_PositionBottomRight
    alignedImage_PositionBottomRightRepeatX
    alignedImage_PositionBottomRightRepeatY
    alignedImage_PositionCenterBottom
    alignedImage_PositionCenterBottomRepeatX
    alignedImage_PositionCenterBottomRepeatY
    alignedImage_PositionCenterFiftyPercentRepeatY
    alignedImage_PositionCenterLeftRepeatY
    alignedImage_PositionCenterRepeatY
    alignedImage_PositionCenterRightRepeatY
    alignedImage_PositionCenterTopRepeatY
    alignedImage_RepeatY
    alignedImage_Round
    alignedImage_RoundSpace
    alignedImage_Space
    unalignedImage
    unalignedImage_Contain
    unalignedImage_PositionBottomRightRepeatX
    unalignedImage_PositionBottomRightRepeatY
    unalignedImage_PositionCenterBottomRepeatX
    unalignedImage_PositionCenterBottomRepeatY
    unalignedImage_PositionCenterFiftyPercentRepeatY
    unalignedImage_PositionCenterLeftRepeatY
    unalignedImage_PositionCenterRepeatY
    unalignedImage_PositionCenterRightRepeatY
    unalignedImage_PositionCenterTopRepeatY
    unalignedImage_RepeatY
    unalignedImage_Round
	
**5** tests fail with **150%** scale,
    alignedImage_PositionCenterTopRepeatX
    alignedImage_RepeatX
    unalignedImage_Cover
    unalignedImage_PositionCenterTopRepeatX
    unalignedImage_RepeatX

These tests are marked to skip execution when screen scale is non-integer.

**Comment by arapte** [comment]
> this might be a bug in Robot itself

It seems like a robot issue. These failures can also be observed without this change and with increased timeout (70000 ms).

>  The fix for [JDK-8170026](https://bugs.openjdk.java.net/browse/JDK-8170026) addressed this by skipping the tests that were sensitive to screen scale (14 of them). You either need to do something similar for `RegionBackgroundImageUITest`

Here also I made same change to skip the failing tests(listed in previous comment).
Please take a look.

**Review by kevinrushforth — APPROVED** [review]
Looks good.

**Pull request closed without merging**
