### PR TITLE
8342913: Remove calls to doPrivileged in media

### PR DESCRIPTION
**Pull request by andy-goryachev-oracle**
Removes doPrivileged in the following module:

- javafx.media

See JDK-8342441 for details.

As a helpful hint for reviewers, I recommend reviewing this using the "Hide whitespace" option.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8342913](https://bugs.openjdk.org/browse/JDK-8342913): Remove calls to doPrivileged in media (**Bug** - P3)

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Alexander Matveev](https://openjdk.org/census#almatvee) (@sashamatveev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1612/head:pull/1612` \
`$ git checkout pull/1612`

Update a local copy of the PR: \
`$ git checkout pull/1612` \
`$ git pull https://git.openjdk.org/jfx.git pull/1612/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1612`

View PR using the GUI difftool: \
`$ git pr show -t 1612`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1612.diff">https://git.openjdk.org/jfx/pull/1612.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1612#issuecomment-2442041789)
</details>

### CODE REVIEW

**Comment by andy-goryachev-oracle** [comment]
@sashamatveev could you take a look at this PR please?

**Review by kevinrushforth — COMMENTED** [review]
I see a few now-unneeded `@SuppressWarnings("removal")` annotations in `NativeMediaManager.java`, but otherwise looks good.

/reviewers 2

**Review by kevinrushforth — APPROVED** [review]

**Review by sashamatveev — APPROVED** [review]
Looks good.

**Pull request closed without merging**
