### PR TITLE
8266743: Crash on macOS 10.11 due to ignored @available 10.12 check

### PR DESCRIPTION
**Pull request by kevinrushforth**
This fix restores the minimum macOS version needed to run JavaFX on x64 platforms to 10.10.

The fix for [JDK-8265031](https://bugs.openjdk.java.net/browse/JDK-8265031) bumped the minimum version for macOS on aarch64 to 11.0 and on x64 to 10.12. The change on aarch64 was necessary, since that is the minimum version that will run on Apple Silicon. The change on x64 was not necessary, but was done to match JDK 17. In connection with the fix for [JDK-8263169](https://bugs.openjdk.java.net/browse/JDK-8263169), this causes a crash on older macOS systems running 10.10 or 10.11. The long term solution is to detect and throw an exception at startup if the version of macOS is below the minimum, but for JavaFX 17 it was felt that restoring the minimum of macOS 10.10 for x64 platforms was safer.

See the discussion in JBS for more information.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8266743](https://bugs.openjdk.java.net/browse/JDK-8266743): Crash on macOS 10.11 due to ignored @available 10.12 check

### Reviewers
 * [Johan Vos](https://openjdk.java.net/census#jvos) (@johanvos - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/566/head:pull/566` \
`$ git checkout pull/566`

Update a local copy of the PR: \
`$ git checkout pull/566` \
`$ git pull https://git.openjdk.java.net/jfx pull/566/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 566`

View PR using the GUI difftool: \
`$ git pr show -t 566`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/566.diff">https://git.openjdk.java.net/jfx/pull/566.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
I filed two follow-on bugs that are targeted for JavaFX 18:

1. [JDK-8269967](https://bugs.openjdk.java.net/browse/JDK-8269967): JavaFX should fail fast on macOS below minimum version
2. [JDK-8269968](https://bugs.openjdk.java.net/browse/JDK-8269968): [REDO] Bump minimum version of macOS for x64 to 10.12

**Comment by kevinrushforth** [comment]
You can ignore the last pair of commits. The first is a "WIP" changes for the eventual fail-fast version detection, and the second reverts the first.

The only change being proposed for this PR is to change the minimum version of macOS for x64 from `"10.12"` to `"10.10" (that is, back to what it was in JavaFX 16 and earlier releases).

**Comment by kevinrushforth** [comment]
There were failing macOS pre-submit tests. It looks like some sort of intermittent test issue, and in any case is unrelated to this change since the initial commit, with 100% identical content passed. However, I pushed a dummy  commit to rerun the tests to remove any question.

**Review by johanvos — APPROVED** [review]

**Pull request closed without merging**
