### PR TITLE
CI: Update to JDK 15.0.2 as boot JDK

### PR DESCRIPTION
**Pull request by EwoutH**
Updates the JDK version used in the CI to 15.0.2 build 7.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Error
&nbsp;⚠️ OCA signatory status must be verified

### Download
To checkout this PR locally:
`$ git fetch https://git.openjdk.java.net/jfx pull/428/head:pull/428`
`$ git checkout pull/428`

To update a local copy of the PR:
`$ git checkout pull/428`
`$ git pull https://git.openjdk.java.net/jfx pull/428/head`

### CODE REVIEW

**Comment by EwoutH** [comment]
Draft for now, will have to review the OCA and Oracle's privacy policy.

**Comment by kevinrushforth** [comment]
If this turns out to be a problem, I can do it next week, since I did it for 15.0.1 (really, I should have done it back in January).

**Comment by kevinrushforth** [comment]
I filed the following bug to track this:

[JDK-8263759](https://bugs.openjdk.java.net/browse/JDK-8263759): Update boot JDK to 15.0.2

**Comment by EwoutH** [comment]
Thanks, feel free to take on this patch yourself, it’s very small anyway.

I noticed the Windows build failing btw, is there any issue with that build on master or is it a regression?

**Comment by kevinrushforth** [comment]
OK, I'll do the update later this week.

The Windows build started failing yesterday due to [JDK-8255713](https://bugs.openjdk.java.net/browse/JDK-8255713), and fixed earlier today by PR #427 

Thanks.

**Comment by kevinrushforth** [comment]
Submitted PR #431 to fix this.

**Pull request closed without merging**
