### PR TITLE
JDK-8259718  Remove the Marlin rasterizer (single-precision)

### PR DESCRIPTION
**Pull request by bourgesl**
Changes:
- Removed single-precision Marlin renderer
-  class name refactoring
- fix prism
- copyright year

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8259718](https://bugs.openjdk.java.net/browse/JDK-8259718): Remove the Marlin rasterizer (single-precision)

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jfx pull/379/head:pull/379`
`$ git checkout pull/379`

### CODE REVIEW

**Comment by bourgesl** [comment]
How to run tests again ? I tried pull commands but it does nothing.

**Comment by kevinrushforth** [comment]
If you have enabled GitHub actions for your personal fork of `jfx`, then the next time you push a commit to your branch it will run the tests. So you might try pushing an empty commit.

**Review by kevinrushforth — APPROVED** [review]
Looks good.

As a sanity check to make reviewing the renamed files easier, I split the patch locally into two commits -- one to remove the old single-precision classes and one with the rest of the changes, including the refactoring. This shows the diffs relative to the current double version, and I confirmed that all the refactoring was as expected.

**Pull request closed without merging**
