### PR TITLE
8282386: JavaFX media stubs rely on libav.org

### PR DESCRIPTION
**Pull request by johanvos**
Retrieve libav sources from github.
Fix JDK-8282386

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8282386](https://bugs.openjdk.org/browse/JDK-8282386): JavaFX media stubs rely on libav.org

### Reviewers
 * [John Neffenger](https://openjdk.org/census#jgneff) (@jgneff - Committer)
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Alexander Matveev](https://openjdk.org/census#almatvee) (@sashamatveev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx pull/989/head:pull/989` \
`$ git checkout pull/989`

Update a local copy of the PR: \
`$ git checkout pull/989` \
`$ git pull https://git.openjdk.org/jfx pull/989/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 989`

View PR using the GUI difftool: \
`$ git pr show -t 989`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/989.diff">https://git.openjdk.org/jfx/pull/989.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
I'll do a CI test build to validate this on our end. I'd also like @sashamatveev to review this.

/reviewers 2

**Comment by bae** [comment]
Probably the name pattern of libav artifacts needs to be updated from `libav-${versions}` to `v${version}` on line 3066, and etc:
```
if (f.name.startsWith("libav-${version}")) {
```

Thanks,
Andrew

**Comment by kevinrushforth** [comment]
> Probably the name pattern of libav artifacts needs to be updated from libav-${versions} to v${version} on line 3066, and etc:

Good catch! Making this change on lines 3066 and 3127 are necessary and sufficient. My local build passes after these two changes.

**Comment by kevinrushforth** [comment]
Here are the additional changes needed:

```
diff --git a/build.gradle b/build.gradle
--- a/build.gradle
+++ b/build.gradle
@@ -3063,7 +3063,7 @@ project(":media") {
                         libav.versions.each { version ->
                             def libavDir = "${libav.basedir}/libav-${version}"
                             for (File f : configurations.media.files) {
-                                if (f.name.startsWith("libav-${version}")) {
+                                if (f.name.startsWith("v${version}")) {
                                     File dir = file(libavDir)
                                     dir.mkdirs()
                                     def libavTar = "${libav.basedir}/libav-${version}.tar"
@@ -3124,7 +3124,7 @@ project(":media") {
                         libav.versions.each { version ->
                             def libavDir = "${libav.basedir}/libav-${version}"
                             for (File f : configurations.media.files) {
-                                if (f.name.startsWith("libav-${version}")) {
+                                if (f.name.startsWith("v${version}")) {
                                     File dir = file(libavDir)
                                     dir.mkdirs()
                                     def libavTar = "${libav.basedir}/libav-${version}.tar"
```

**Comment by kevinrushforth** [comment]
Since the .tar.gz source bundles on libav and github are not 100% identical (the checksums are different), I expanded and diffed them, and the sources themselves are identical; the only difference in the bundles is the absence of a `VERSION` file in the github bundles, and we don't use that.

**Comment by johanvos** [comment]
> Here are the additional changes needed:
> 
Right, it worked locally for me but failed on our CI as well. It worked locally as I have libavcodec.so in my standard library path, but indeed the new libav versions were not copied into the expected directories, hence CI failed.

**Comment by jgneff** [comment]
I ran the following commands on Ubuntu 20.04.5 LTS using the `8282386-libav` branch of `johanvos/jfx`, and both the build and unit tests were successful:

```console
$ unset SOURCE_DATE_EPOCH
$ bash gradlew --no-daemon -PCONF=Release -PPROMOTED_BUILD_NUMBER=11 \
    -PHUDSON_BUILD_NUMBER=101 -PHUDSON_JOB_NAME=jfx \
    -PCOMPILE_WEBKIT=true -PCOMPILE_MEDIA=true -PBUILD_LIBAV_STUBS=true \
    sdk jmods javadoc test
  ...
BUILD SUCCESSFUL in 1h 11m 58s
228 actionable tasks: 228 executed
```

The build environment was set up by sourcing the following file:

```bash
#!/bin/bash
# Sets up the environment for building JavaFX
syspath=/usr/sbin:/usr/bin:/sbin:/bin

export CMAKE_HOME=$HOME/opt/cmake-3.25.1-linux-x86_64
export JAVA_HOME=$HOME/opt/jdk-19.0.1
export ANT_HOME=$HOME/opt/apache-ant-1.10.12

SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
export SOURCE_DATE_EPOCH

# JDK_HOME and PATH are required by the build
export JDK_HOME=$JAVA_HOME
export PATH=$ANT_HOME/bin:$JAVA_HOME/bin:$CMAKE_HOME/bin:$syspath
```

**Review by jgneff — APPROVED** [review]
The *Release* build and unit tests are now successful for me on Linux.

**Review by kevinrushforth — APPROVED** [review]
A local build and a CI build both pass now. This looks good.

@sashamatveev Do you also want to take a look at this?

**Review by sashamatveev — APPROVED** [review]
Looks good.

**Pull request closed without merging**
