### PR TITLE
8338000: [macos] Remove GlassFullscreenWindow

### PR DESCRIPTION
**Pull request by beldenfox**
The GlassFullscreenWindow class hasn't been instantiated since applet support was removed (JDK-8201538). This PR removes the class and the one (unused) member variable of that type.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8338000](https://bugs.openjdk.org/browse/JDK-8338000): [macos] Remove GlassFullscreenWindow (**Bug** - P4)

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Michael Strauß](https://openjdk.org/census#mstrauss) (@mstr2 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1641/head:pull/1641` \
`$ git checkout pull/1641`

Update a local copy of the PR: \
`$ git checkout pull/1641` \
`$ git pull https://git.openjdk.org/jfx.git pull/1641/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1641`

View PR using the GUI difftool: \
`$ git pr show -t 1641`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1641.diff">https://git.openjdk.org/jfx/pull/1641.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1641#issuecomment-2481538110)
</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
Nice cleanup.

I reviewed all of the code changes, and this all looks good. In addition to reviewing it, I instrumented the code to verify that `fullScreenWindow` is always null (it is). After applying your patch, I see no more references to the dead classes and the unused (always null) `fullScreenWindow` and `fsWindow` fields.

I fired off a headful test build on our macOS platforms and will approve it once it passes.

@beldenfox You will need to change the title of this PR to match the JBS title (I modified it slightly for consistency, but the mismatch was there before I did that).

**Review by kevinrushforth — APPROVED** [review]

**Comment by kevinrushforth** [comment]
@andy-goryachev-oracle can you be the second reviewer?

**Review by mstr2 — APPROVED** [review]
The code changes look good. I built and tested the changes, everything works as expected.

**Pull request closed without merging**
