### PR TITLE
8314597: Deprecate for removal protected access methods in converters

### PR DESCRIPTION
**Pull request by nlisker**
Deprecating for removal `getDateFormat()` in `TimeStringConverter` and `DateStringConverter` after it was removed already in `DateTimeStringConverter`, and `getNumberFormat()` in `NumberStringConverter` (and subclasses).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))
- [x] Change requires CSR request [JDK-8320615](https://bugs.openjdk.org/browse/JDK-8320615) to be approved

### Issues
 * [JDK-8314597](https://bugs.openjdk.org/browse/JDK-8314597): Deprecate for removal protected access methods in converters (**Bug** - P4)
 * [JDK-8320615](https://bugs.openjdk.org/browse/JDK-8320615): Deprecate for removal protected access methods in converters (**CSR**)

### Reviewers
 * [Andy Goryachev](https://openjdk.org/census#angorya) (@andy-goryachev-oracle - **Reviewer**)
 * [John Hendrikx](https://openjdk.org/census#jhendrikx) (@hjohn - Committer)
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1294/head:pull/1294` \
`$ git checkout pull/1294`

Update a local copy of the PR: \
`$ git checkout pull/1294` \
`$ git pull https://git.openjdk.org/jfx.git pull/1294/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1294`

View PR using the GUI difftool: \
`$ git pr show -t 1294`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1294.diff">https://git.openjdk.org/jfx/pull/1294.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1294#issuecomment-1821715804)

### CODE REVIEW

**Comment by andy-goryachev-oracle** [comment]
Are we going to make all these private at some point?  
Including DateFormat.getDateFormat()?

**Comment by nlisker** [comment]
> Are we going to make all these private at some point?

They are going to be made package-private so that they are not public API while still can be read by subclasses. There's no "internal protected" visibility that would be ideal.

> Including DateFormat.getDateFormat()?

`DateFormat` is not in JavaFX.

**Comment by andy-goryachev-oracle** [comment]
Sorry, I meant DateTimeStringConverter.getDateFormat().  It's package-protected and gets overridden in DateStringConverter.
Should both be converted to private methods then?

**Comment by nlisker** [comment]
`DateTimeStringConverter.getDateFormat()` is already package-private and should remain that way. `DateStringConverter.getDateFormat()` will becomes package-private in version 23 (we need to give 1 version notice before removal).

There will be a refactoring patch at a later point anyway to do some internal rearrangement.

**Comment by andy-goryachev-oracle** [comment]
The question is, **should** they be private?

**Comment by nlisker** [comment]
No, they wouldn't be able to be read by subclasses or overriden if they are private.

**Comment by andy-goryachev-oracle** [comment]
so the app dev cannot extend standard classes to supply their own format implementation?

use case: MyDateTimeStringConverter extends DatetimeStringConverter which uses Klingon/Marsian date/time format?

**Comment by nlisker** [comment]
Is the constructor that takes `DateFormat` not good enough? Can you give an example of a class that would extend `DateTimeStringConverter`?

**Comment by andy-goryachev-oracle** [comment]
You are right, constructor that accepts the format is enough.
It's just weird - allowing core classes to override yet denying this freedom to the app dev.

On the other hand, they can always extend StringConverter.

**Review by andy-goryachev-oracle — APPROVED** [review]
CSR is needed (I see you already issued a / csr command).
LGTM

**Comment by nlisker** [comment]
> It's just weird - allowing core classes to override yet denying this freedom to the app dev.

I don't think these classes should have existed. They don't add any functionality and could have been specialized constant implementations.

Will wait for the changes to be approved here, then I'll file the CSR. Saves upkeeping 2 copies.

**Comment by andy-goryachev-oracle** [comment]
> Saves upkeeping 2 copies.

this should be a standard operating procedure, in my opinion.

**Review by hjohn — APPROVED** [review]

**Comment by kevinrushforth** [comment]
> > Will wait for the changes to be approved here, then I'll file the CSR. Saves upkeeping 2 copies.
> 
> this should be a standard operating procedure, in my opinion.

For simple CSRs, yes. For more complicated changes, there is value in getting CSR feedback in parallel, although even in that case it's usually best to wait until the review of the API changes are far enough along that big changes aren't expected.

**Comment by kevinrushforth** [comment]
The changes look like what I would expect. I'll take a closer look at the PR and CSR soon.

**Review by kevinrushforth — APPROVED** [review]

**Pull request closed without merging**
