### PR TITLE
[WIP] 8234920: Add SpotLight to the selection of 3D light types

### PR DESCRIPTION
**Pull request by nlisker**
---------
### Progress
- [ ] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Integration blocker
&nbsp;⚠️ The change requires a CSR request to be approved.

### Download
`$ git fetch https://git.openjdk.java.net/jfx pull/328/head:pull/328`
`$ git checkout pull/328`

### CODE REVIEW

**Comment by nlisker** [comment]
@kevinrushforth I got into a git mess. Any idea why the file comparison isn't made against the latest master commit? I see that `PointLight` doesn't have the attenuation patch, for example. This causes a lot of conflicts which are not really conflicts.

**Comment by kevinrushforth** [comment]
@nlisker it looks like you didn't merge in the latest upstream changes from master. You have several merge conflicts that you will need to resolve. When you have resolved them, you might want to rebase and squash all of this down to a single commit for the initial review.

**Comment by nlisker** [comment]
@kevinrushforth I couldn't get it sorted out - changes that I made with intent to commit were marked as conflicts. I created #334 instead as a WIP.

**Pull request closed without merging**
