### PR TITLE
8336938: Update libFFI to 3.4.6

### PR DESCRIPTION
**Pull request by sashamatveev**
- libFFI updated to 3.4.6.
- No additional changes are done.
- Tested on Windows, macOS and Linux with all supported formats.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8336938](https://bugs.openjdk.org/browse/JDK-8336938): Update libFFI to 3.4.6 (**Bug** - P3)

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Joeri Sykora](https://openjdk.org/census#sykora) (@tiainen - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1531/head:pull/1531` \
`$ git checkout pull/1531`

Update a local copy of the PR: \
`$ git checkout pull/1531` \
`$ git pull https://git.openjdk.org/jfx.git pull/1531/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1531`

View PR using the GUI difftool: \
`$ git pr show -t 1531`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1531.diff">https://git.openjdk.org/jfx/pull/1531.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1531#issuecomment-2272399007)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
@tiainen Do you want to be the second reviewer?

**Comment by kevinrushforth** [comment]
I see one minor difference between the upstream and your PR in a commented out line of code in `sysv_intel.S`. I don't know whether it is significant (I guess not, as long as it compiles with the current inline comment style).

```
diff -u -w -r ../../jfx-tmp/jfx/rt/modules/javafx.media/src/main/native/gstreamer/3rd_party/libffi/src/x86/sysv_intel.S ./src/x86/sysv_intel.S
--- ../../jfx-tmp/jfx/rt/modules/javafx.media/src/main/native/gstreamer/3rd_party/libffi/src/x86/sysv_intel.S   2024-08-12 15:59:14.597741100 -0700
+++ ./src/x86/sysv_intel.S      2024-08-12 16:05:42.708534300 -0700
@@ -102,7 +102,7 @@
         mov         ecx, [12+ebp]               /* load return type code */
         mov     [ebp+8], ebx            /* preserve %ebx */
 L(UW2):
-        // cfi_rel_offset(%ebx, 8)
+       /* cfi_rel_offset(%ebx, 8) */

         and     ecx, X86_RET_TYPE_MASK
         lea     ebx, [L(store_table) + ecx * 8]
```

**Comment by sashamatveev** [comment]
> I see one minor difference between the upstream and your PR in a commented out line of code in `sysv_intel.S`. I don't know whether it is significant (I guess not, as long as it compiles with the current inline comment style).
> 
> ```
> diff -u -w -r ../../jfx-tmp/jfx/rt/modules/javafx.media/src/main/native/gstreamer/3rd_party/libffi/src/x86/sysv_intel.S ./src/x86/sysv_intel.S
> --- ../../jfx-tmp/jfx/rt/modules/javafx.media/src/main/native/gstreamer/3rd_party/libffi/src/x86/sysv_intel.S   2024-08-12 15:59:14.597741100 -0700
> +++ ./src/x86/sysv_intel.S      2024-08-12 16:05:42.708534300 -0700
> @@ -102,7 +102,7 @@
>          mov         ecx, [12+ebp]               /* load return type code */
>          mov     [ebp+8], ebx            /* preserve %ebx */
>  L(UW2):
> -        // cfi_rel_offset(%ebx, 8)
> +       /* cfi_rel_offset(%ebx, 8) */
> 
>          and     ecx, X86_RET_TYPE_MASK
>          lea     ebx, [L(store_table) + ecx * 8]
> ```

Yes, it compiles fine. It was changed by libFFI itself in 3.4.6. I think to be inline with rest of comments in this file.

**Comment by kevinrushforth** [comment]
> Yes, it compiles fine. It was changed by libFFI itself in 3.4.6. I think to be inline with rest of comments in this file.

What I meant was that you missed making that change when you updated the file. The old line with the inline comment style is still in our copy of the file. So it no longer matches the upstream libffi 3.4.6. It seems best to apply that part of the patch so that we will match the upstream version of the file.

**Review by kevinrushforth — APPROVED** [review]
Code changes look good. Testing looks good.

**Review by tiainen — APPROVED** [review]
All builds ran fine.

**Pull request closed without merging**
