### PR TITLE
8223298: SVG patterns are drawn wrong

### PR DESCRIPTION
**Pull request by arun-Joseph**
Issue: Assuming the pixelScale is 2, the tile image size is doubled at the native side which is propagated to the java side as well. But, as transform initialization takes place after scaling, the transform is reset to default value.

Fix: Override scale() method in WCBufferedContext class to call init() before scaling.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8223298](https://bugs.openjdk.java.net/browse/JDK-8223298): SVG patterns are drawn wrong

### Reviewers
 * Guru Hb ([ghb](@guruhb) - **Reviewer**)
 * Kevin Rushforth ([kcr](@kevinrushforth) - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jfx pull/164/head:pull/164`
`$ git checkout pull/164`

### CODE REVIEW

**Comment by kevinrushforth** [comment]
As discussed offline, please add a test for this.

**Comment by nlisker** [comment]
@kevinrushforth Looks like the `sponsor` tag wasn't removed in this one long ago.

**Comment by kevinrushforth** [comment]
If I had to guess, there was some sort of bug or race condition in Skara around the time Arun became a committer. Looking at the history, I see that a second `/integrate` command succeeded without needing a sponsor.

**Comment by kevinrushforth** [comment]
We will manually remove the label to avoid confusion.

**Pull request closed without merging**
