### PR TITLE
8297554: Remove Scene.KeyHandler

### PR DESCRIPTION
**Pull request by mstr2**
The `Scene.KeyHandler` class doesn't seem to have a clear purpose, mixing focus handling with event propagation. Since #852, `KeyHandler.setFocusVisible` is also called from mouse and touch event handlers, which makes the purpose of the class even less pronounced.

Moving the focus-related functionality next to the other focus functions in the `Scene` class makes it easier to work with the code in the future.

With the focus-related functions gone, `KeyHandler` only contains a single, small method that is called from `Scene.processKeyEvent`. For simplicity, this code can be rolled into `Scene.processKeyEvent` and the now-empty `KeyHandler` class can be removed.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8297554](https://bugs.openjdk.org/browse/JDK-8297554): Remove Scene.KeyHandler

### Reviewers
 * [Ambarish Rapte](https://openjdk.org/census#arapte) (@arapte - **Reviewer**)
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx pull/962/head:pull/962` \
`$ git checkout pull/962`

Update a local copy of the PR: \
`$ git checkout pull/962` \
`$ git pull https://git.openjdk.org/jfx pull/962/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 962`

View PR using the GUI difftool: \
`$ git pr show -t 962`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/962.diff">https://git.openjdk.org/jfx/pull/962.diff</a>

</details>

### CODE REVIEW

**Comment by arapte** [comment]
It looks in a quick look, shall review in detail in couple days.

**Review by arapte — CHANGES_REQUESTED** [review]
The changes look equivalent to the code before. 
Suggesting minor changes.
Shall do some sanity testing with focus and update.

**Review by kevinrushforth — APPROVED** [review]
@mstr2 The fix looks fine to me. I presume you have done enough testing to ensure no regressions?

I left a comment on the question raised by Ambarish.

**Comment by mstr2** [comment]
> @mstr2 The fix looks fine to me. I presume you have done enough testing to ensure no regressions?
> 

I tested it by running it against SceneBuilder and playing around with focus, where I noticed no regressions.

**Review by arapte — APPROVED** [review]

**Pull request closed without merging**
