### PR TITLE
8336940: Update GStreamer to 1.24.6

### PR DESCRIPTION
**Pull request by sashamatveev**
- Updated GStreamer to 1.24.6 and Glib to 2.80.4.
- Testing done on all platforms with all supported formats.
- Removed gstpluginloader.c. This file contains additional plugin loading mechanism which we do not use. Latest GStreamer modified it heavily and it did not compile without pulling additional dependency from GLib, but since we do not use it anyway it was removed. Corresponding calls to gstpluginloader.c from gstregistry.c were disabled as well.
- Removed DSD support from Alsa audio sink. Latest GStreamer added support for Alsa DSD (Direct Stream Digital), but we do not use it so it was removed. Also, such support requires newer libasound2 (ALSA) which is not available on older Linux distributions.
- No other changes or bug fixes are done.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issues
 * [JDK-8336940](https://bugs.openjdk.org/browse/JDK-8336940): Update GStreamer to 1.24.6 (**Bug** - P3)
 * [JDK-8336939](https://bugs.openjdk.org/browse/JDK-8336939): Update Glib to 2.80.4 (**Bug** - P3)

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Joeri Sykora](https://openjdk.org/census#sykora) (@tiainen - Author)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1542/head:pull/1542` \
`$ git checkout pull/1542`

Update a local copy of the PR: \
`$ git checkout pull/1542` \
`$ git pull https://git.openjdk.org/jfx.git pull/1542/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1542`

View PR using the GUI difftool: \
`$ git pr show -t 1542`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1542.diff">https://git.openjdk.org/jfx/pull/1542.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1542#issuecomment-2303031075)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
Reviewers: @kevinrushforth and @tiainen or @johanvos 

/reviewers 2

**Comment by kevinrushforth** [comment]
I get a compilation error on my admittedly too-old Ubuntu 16.04 system. It might be worth adding the missing header file, in case other distros hit the same problem.

```
In file included from ../../../gstreamer-lite/gstreamer/gst/gstmeta.h:28,
                 from ../../../gstreamer-lite/gstreamer/gst/gstbuffer.h:43,
                 from ../../../gstreamer-lite/gstreamer/gst/gstpad.h:70,
                 from ../../../gstreamer-lite/gstreamer/gst/gstelement.h:223,
                 from ../../../gstreamer-lite/gstreamer/gst/gstbin.h:27,
                 from ../../../gstreamer-lite/gstreamer/gst/gst.h:35,
                 from ../../../gstreamer-lite/gstreamer/libs/gst/base/gstbitreader.h:24,
                 from ../../../gstreamer-lite/gstreamer/libs/gst/base/gstbitreader.c:26:
../../../gstreamer-lite/gstreamer/gst/gstbytearrayinterface.h: In function 'gst_byte_array_interface_init':
../../../gstreamer-lite/gstreamer/gst/gstbytearrayinterface.h:66:3: error: implicit declaration of function 'memset' [-Werror=implicit-function-declaration]
   66 |   memset (self, 0, sizeof (GstByteArrayInterface));
      |   ^~~~~~
../../../gstreamer-lite/gstreamer/gst/gstbytearrayinterface.h:1:1: note: include '<string.h>' or provide a declaration of 'memset'
  +++ |+#include <string.h>
    1 | /* Copyright (C) 2023 Netflix Inc.
../../../gstreamer-lite/gstreamer/gst/gstbytearrayinterface.h:66:3: warning: incompatible implicit declaration of built-in function 'memset' [-Wbuiltin-declaration-mismatch]
   66 |   memset (self, 0, sizeof (GstByteArrayInterface));
      |   ^~~~~~
../../../gstreamer-lite/gstreamer/gst/gstbytearrayinterface.h:66:3: note: include '<string.h>' or provide a declaration of 'memset'
../../../gstreamer-lite/gstreamer/gst/gstbytearrayinterface.h: In function 'gst_byte_array_interface_append_data':
../../../gstreamer-lite/gstreamer/gst/gstbytearrayinterface.h:125:3: error: implicit declaration of function 'memcpy' [-Werror=implicit-function-declaration]
  125 |   memcpy (ptr, data, size);
      |   ^~~~~~
../../../gstreamer-lite/gstreamer/gst/gstbytearrayinterface.h:125:3: note: include '<string.h>' or provide a declaration of 'memcpy'
../../../gstreamer-lite/gstreamer/gst/gstbytearrayinterface.h:125:3: warning: incompatible implicit declaration of built-in function 'memcpy' [-Wbuiltin-declaration-mismatch]
../../../gstreamer-lite/gstreamer/gst/gstbytearrayinterface.h:125:3: note: include '<string.h>' or provide a declaration of 'memcpy'
cc1: some warnings being treated as errors
Makefile:281: recipe for target 'modules/javafx.media/build/native/linux/Release/obj/gstreamer-lite/gstreamer/libs/gst/base/gstbitreader.o' failed
make: *** [modules/javafx.media/build/native/linux/Release/obj/gstreamer-lite/gstreamer/libs/gst/base/gstbitreader.o] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory 'modules/javafx.media/src/main/native/gstreamer/projects/linux/gstreamer-lite'

> Task :media:buildLinuxGStreamer FAILED
```

**Comment by sashamatveev** [comment]
8336940: Update GStreamer to 1.24.6 [v2]
 - Fixed whitespace.

8336940: Update GStreamer to 1.24.6 [v3]
- Added missing header file.

**Review by kevinrushforth — APPROVED** [review]
Looks good. Built and tested on all three platforms.

**Review by tiainen — APPROVED** [review]
Builds and tests ran fine.

**Pull request closed without merging**
