### PR TITLE
8337328: JavaFX build uses deprecated features that will be removed in gradle 9

### PR DESCRIPTION
**Pull request by arapte**
Following 2 warnings are observed with the JavaFX build.
These warnings need to be addressed for updating to Gradle 9.0 in future. 

1. The org.gradle.api.plugins.JavaPluginConvention type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.9/userguide/upgrading_version_8.html#java_convention_deprecation
`=>>` This warning gets fixed by the change on line number 2111 in build.gradle

2. The automatic loading of test framework implementation dependencies has been deprecated. This is scheduled to be removed in Gradle 9.0. Declare the desired test framework directly on the test suite or explicitly declare the test framework implementation dependencies on the test's runtime classpath. Consult the upgrading guide for further information: https://docs.gradle.org/8.9/userguide/upgrading_version_8.html#test_framework_implementation_dependencies
`=>>` This warning gets fixed by the change on line number 2128 in build.gradle. It also requires the verification metadata to be updated.

Verification:
1. Verify that build completes successfully
2. Above two warnings are not observed in build log.
3. This warning message is NOT observed in build log: Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8337328](https://bugs.openjdk.org/browse/JDK-8337328): JavaFX build uses deprecated features that will be removed in gradle 9 (**Bug** - P3)

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Andy Goryachev](https://openjdk.org/census#angorya) (@andy-goryachev-oracle - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1559/head:pull/1559` \
`$ git checkout pull/1559`

Update a local copy of the PR: \
`$ git checkout pull/1559` \
`$ git pull https://git.openjdk.org/jfx.git pull/1559/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1559`

View PR using the GUI difftool: \
`$ git pr show -t 1559`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1559.diff">https://git.openjdk.org/jfx/pull/1559.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1559#issuecomment-2338608965)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
Looking at the GHA logs, the warnings are gone on macOS and Linux, but there is still at least one warning on Windows:

```
2024-09-09T16:44:02.4582769Z Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
2024-09-09T16:44:02.4583540Z 
2024-09-09T16:44:02.4584686Z You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
2024-09-09T16:44:02.4585790Z 
2024-09-09T16:44:02.4586846Z For more on this, please refer to https://docs.gradle.org/8.9/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
2024-09-09T16:44:02.4588091Z 
2024-09-09T16:44:02.4588292Z BUILD SUCCESSFUL in 6m 51s
```

**Comment by andy-goryachev-oracle** [comment]
gradle 8.5 on macOS: no warning (this of a historical interest)
gradle 8.10 on macOS: no warning

**Comment by arapte** [comment]
Updated the PR with fix for windows warning: [commit](https://github.com/openjdk/jfx/pull/1559/commits/3c8cbc85ea8666574c43e3d6cb932b5ef32ffc1a)
Warnings are :

- Build file 'C:\ade\jfx\rt\build.gradle': line 4729 
The CopyProcessingSpec.setDirMode(Integer) method has been deprecated. This is scheduled to be removed in Gradle 9.0. Please use the dirPermissions(Action) method instead. Consult the upgrading guide for further information: https://docs.gradle.org/8.9/userguide/upgrading_version_8.html#unix_file_permissions_deprecated

- Build file 'C:\ade\jfx\rt\build.gradle': line 4730 
The CopyProcessingSpec.setFileMode(Integer) method has been deprecated. This is scheduled to be removed in Gradle 9.0. Please use the filePermissions(Action) method instead. Consult the upgrading guide for further information: https://docs.gradle.org
/8.9/userguide/upgrading_version_8.html#unix_file_permissions_deprecated

[CopyProcessingSpec.setDirMode(Integer)](https://docs.gradle.org/8.9/javadoc/org/gradle/api/file/CopyProcessingSpec.html#setDirMode(java.lang.Integer)) and [CopyProcessingSpec.setFileMode(Integer)](https://docs.gradle.org/8.9/javadoc/org/gradle/api/file/CopyProcessingSpec.html#setFileMode(java.lang.Integer)) are both deprecated and should be replaced with [dirPermissions(Action)](https://docs.gradle.org/8.9/javadoc/org/gradle/api/file/CopyProcessingSpec.html#dirPermissions(org.gradle.api.Action)) & [filePermissions(Action)](https://docs.gradle.org/8.9/javadoc/org/gradle/api/file/CopyProcessingSpec.html#filePermissions(org.gradle.api.Action)) respectively.
Using [unix](https://docs.gradle.org/8.9/javadoc/org/gradle/api/file/ConfigurableFilePermissions.html#unix(int)) method  to achieve this seems like a good way.

**Review by kevinrushforth — APPROVED** [review]
Looks good now. I get no warnings on Windows now.

**Comment by andy-goryachev-oracle** [comment]
was this PR tested on linux?

**Comment by kevinrushforth** [comment]
Yes. Both via GHA and via our CI system.

**Review by andy-goryachev-oracle — APPROVED** [review]

**Pull request closed without merging**
