### PR TITLE
8292609 : Cherry-pick WebKit 614.1 stabilization fixes

### PR DESCRIPTION
**Pull request by HimaBinduMeda**
Stabilization fixes from WebKitGTK 2.36.7.
Verified drt and unit tests on Mac, Windows and Linux platforms.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8292609](https://bugs.openjdk.org/browse/JDK-8292609): Cherry-pick WebKit 614.1 stabilization fixes

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Ambarish Rapte](https://openjdk.org/census#arapte) (@arapte - **Reviewer**)
 * [Johan Vos](https://openjdk.org/census#jvos) (@johanvos - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx pull/885/head:pull/885` \
`$ git checkout pull/885`

Update a local copy of the PR: \
`$ git checkout pull/885` \
`$ git pull https://git.openjdk.org/jfx pull/885/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 885`

View PR using the GUI difftool: \
`$ git pr show -t 885`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/885.diff">https://git.openjdk.org/jfx/pull/885.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
@johanvos or @tiainen do one of you also want to review? I don't think there are any changes that would affect your being able to build it, but since there are a few changes, you might want to to a test build.

**Review by kevinrushforth — APPROVED** [review]
All my testing looks good. The code changes look good.

**Review by arapte — APPROVED** [review]
Did a build, ATR, sanity check on MacOS. LGTM

**Comment by johanvos** [comment]
I'll do a test build.

**Review by johanvos — APPROVED** [review]

**Pull request closed without merging**
