### PR TITLE
8297362: EOS might not be delivered by progressbuffer in some cases

### PR DESCRIPTION
**Pull request by sashamatveev**
This is regression from [JDK-8043352](https://bugs.openjdk.org/browse/JDK-8043352). [JDK-8043352](https://bugs.openjdk.org/browse/JDK-8043352) moved clearing pending events in progress buffer when upstream sends EOS. We need to do this for any other events except EOS. If we clear pending EOS, then it will not be delivered and we will hang due to downstream waiting for data or EOS. We still need to clear any other events such as new segment and not deliver it once we receive EOS.

Added "plugins" folder to macOS project. For some reason it was missing and debugging plugins with xcode was not possible.

Tested on all platforms with all formats over FILE and HTTP protocol. EOS was delivered correctly in all cases.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8297362](https://bugs.openjdk.org/browse/JDK-8297362): EOS might not be delivered by progressbuffer in some cases

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Ambarish Rapte](https://openjdk.org/census#arapte) (@arapte - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx pull/961/head:pull/961` \
`$ git checkout pull/961`

Update a local copy of the PR: \
`$ git checkout pull/961` \
`$ git pull https://git.openjdk.org/jfx pull/961/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 961`

View PR using the GUI difftool: \
`$ git pr show -t 961`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/961.diff">https://git.openjdk.org/jfx/pull/961.diff</a>

</details>

### CODE REVIEW

**Review by kevinrushforth — APPROVED** [review]
Looks good.

**Review by arapte — APPROVED** [review]
Looks good to me too.

**Pull request closed without merging**
