### PR TITLE
8317508: Provide media support for libavcodec version 60

### PR DESCRIPTION
**Pull request by sashamatveev**
- Added support for libavcodec version 60.
- Tested on Ubuntu 23.10 with all possible media formats.
- Changed "--disable-yasm" to "--disable-asm". "--disable-asm" disables all assembler optimization and "--disable-yasm" only x86. Without "--disable-asm" I had issue building ffmpeg 6.0 on Ubuntu 23.10 most likely due to compiler version. Disabling assembler optimization fixed issue and we do not need this anyway for our stubs.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8317508](https://bugs.openjdk.org/browse/JDK-8317508): Provide media support for libavcodec version 60 (**Bug** - P3)

### Reviewers
 * [Joeri Sykora](https://openjdk.org/census#sykora) (@tiainen - Author)
 * [Ambarish Rapte](https://openjdk.org/census#arapte) (@arapte - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1259/head:pull/1259` \
`$ git checkout pull/1259`

Update a local copy of the PR: \
`$ git checkout pull/1259` \
`$ git pull https://git.openjdk.org/jfx.git pull/1259/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1259`

View PR using the GUI difftool: \
`$ git pr show -t 1259`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1259.diff">https://git.openjdk.org/jfx/pull/1259.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jfx/pull/1259#issuecomment-1760631871)

### CODE REVIEW

**Comment by victordyakov** [comment]
@arapte please review

**Review by tiainen — APPROVED** [review]
Builds and tests ran successfully.

**Review by arapte — APPROVED** [review]

**Pull request closed without merging**
