### PR TITLE
8238434: Ensemble: Update version of Lucene to 7.7.2

### PR DESCRIPTION
**Pull request by kevinrushforth**
Update the version of Lucene used by Ensemble to the latest release of Lucene 7 which is version 7.7.2.

Per the instructions in [`UPDATING-lucene.txt`](https://github.com/openjdk/jfx/blob/master/apps/samples/Ensemble8/UPDATING-lucene.txt), I made the following changes:

1. Bumped the version numbers from 7.7.1 to 7.7.2 in all needed places

I did not regenerate the index files, since only the `bugfix` number (the third digit) changed. It is the same `major.minor` release as before.

To test this: apply the patch, run `gradle apps`, launch Ensemble8, and search for a sample or JavaFX component in the upper-right search box.

## Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

## Issue
[JDK-8238434](https://bugs.openjdk.java.net/browse/JDK-8238434): Ensemble: Update version of Lucene to 7.7.2

## Approvers
 * Ajit Ghaisas ([aghaisas](@aghaisas) - **Reviewer**)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
@aghaisas can you review this?

**Comment by kevinrushforth** [comment]
I pushed a new commit that reverts the changes to the stored binary index files. There is no need to regenerate them when upgrade to a new version where only the `bugfix` number (the third digit) changes. This minimizes the churn and avoids modifying the binary index files needlessly. I added a note to this effect in the updated [`UPDATING-lucene.txt`](https://github.com/openjdk/jfx/blob/6facff5d7b7a9160939a5b4231a8355a617377a6/apps/samples/Ensemble8/UPDATING-lucene.txt) file.

**Comment by aghaisas** [comment]
I applied this patch, built the apps and verified with Ensemble8 app.
Also, verified that it downloads lucene 7.7.2 during build.

**Pull request closed without merging**
