### PR TITLE
8304734: Monocle: Stage no longer gets focus after fix for JDK-8296621

### PR DESCRIPTION
**Pull request by tsayao**
#940  Fixed focus stealing when scene is changed, but broke Monocle that relied on the `requestFocus` call.

This is a proposed fix that calls `requestFocus` when window is shown.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8304734](https://bugs.openjdk.org/browse/JDK-8304734): Monocle: Stage no longer gets focus after fix for JDK-8296621

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx.git pull/1066/head:pull/1066` \
`$ git checkout pull/1066`

Update a local copy of the PR: \
`$ git checkout pull/1066` \
`$ git pull https://git.openjdk.org/jfx.git pull/1066/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1066`

View PR using the GUI difftool: \
`$ git pr show -t 1066`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1066.diff">https://git.openjdk.org/jfx/pull/1066.diff</a>

</details>

### CODE REVIEW

**Comment by tsayao** [comment]
@jperedadnr Could you check if this is a valid approach to fix the bug?

**Comment by jperedadnr** [comment]
Sure, I'll have a look

**Comment by johanvos** [comment]
I think we need some clear (cross-platform) logic about when focus should be obtained.

**Comment by tsayao** [comment]
@johanvos It does make sense, but I don't think it's the correct solution.
`setScene()` is usually called before showing, so requesting focus on something that does not exists yet may be inconsistent.

For example:
https://bugs.openjdk.org/browse/JDK-8212060

**Comment by johanvos** [comment]
Maybe the request for focus doesn't need to be in `setScene`, but I think it really belongs in a non-platform specific class.

**Comment by tsayao** [comment]
Closing in favor of #1110

**Pull request closed without merging**
