### PR TITLE
8281723: Spinner with split horizontal arrows and a border places right arrow incorrectly

### PR DESCRIPTION
**Pull request by hjohn**
I added a test case for `SpinnerSkin` that checks the arrow positioning.

While adding the tests I discovered more problems with the positioning aside from the one mentioned in the JBS ticket.

1) Vertical split arrow placement also forgot to take the padding into account while placing the decrement arrow button -- I've taken the liberty to fix that problem as well in the same PR.

2) When arrows are placed next to each other either on the right or left, the arrow widths are not normalized to be the width of the widest arrow.  All other placements will normalize either the width or height, except for these two.  Specifically, when the arrows are **split** on the left and right they **are** normalized to the same width.  

For point 2, here is the problem illustrated with actual widths on left and layout result on right:

     [ <----- ] [ -> ] [ spinner ]       -->          [ <----- ] [ -> ] [ spinner ]
     [ spinner ] [ <----- ] [ -> ]       -->          [ spinner ] [ <----- ] [ -> ]

While for split horizontal it does normalize the width to that of the widest arrow, and so layout becomes:

     [ <----- ] [ spinner ] [ -> ]       -->          [ <----- ] [ spinner ] [   ->   ]

While I'm here I could fix this as well, and adjust the test case to match.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8281723](https://bugs.openjdk.java.net/browse/JDK-8281723): Spinner with split horizontal arrows and a border places right arrow incorrectly

### Reviewers
 * [Marius Hanl](https://openjdk.java.net/census#mhanl) (@Maran23 - Author)
 * [Ajit Ghaisas](https://openjdk.java.net/census#aghaisas) (@aghaisas - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jfx pull/748/head:pull/748` \
`$ git checkout pull/748`

Update a local copy of the PR: \
`$ git checkout pull/748` \
`$ git pull https://git.openjdk.java.net/jfx pull/748/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 748`

View PR using the GUI difftool: \
`$ git pr show -t 748`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jfx/pull/748.diff">https://git.openjdk.java.net/jfx/pull/748.diff</a>

</details>

### CODE REVIEW

**Review by Maran23 — APPROVED** [review]
Fix + Tests look good to me

**Review by aghaisas — APPROVED** [review]
The fix looks good to me.

**Pull request closed without merging**
