### PR TITLE
8259555: Webkit crashes on Apple Silicon

### PR DESCRIPTION
**Pull request by petermz**
I've ported relevant patches from Webkit trunk, and enabled the new `HAVE_PTHREAD_JIT_PERMISSIONS_API` flag in Source/WTF/wtf/PlatformHave.h . The flag is enabled only for the Java port when building on Big Sur or above.

Webkit changesets ported:
* https://trac.webkit.org/changeset/257812/webkit
* https://trac.webkit.org/changeset/259582/webkit
* https://trac.webkit.org/changeset/259711/webkit
* https://trac.webkit.org/changeset/262591//webkit
* https://trac.webkit.org/changeset/262670/webkit
* https://trac.webkit.org/changeset/263380/webkit
* https://trac.webkit.org/changeset/269396/webkit

Testing: `gradle :web:test` passed on both Mac-x64 and Mac-m1

JBS issue: https://bugs.openjdk.java.net/browse/JDK-8259555

---------
### Progress
- [ ] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8259555](https://bugs.openjdk.java.net/browse/JDK-8259555): Webkit crashes on Apple Silicon

### Download
`$ git fetch https://git.openjdk.java.net/jfx pull/374/head:pull/374`
`$ git checkout pull/374`

### CODE REVIEW

**Comment by kevinrushforth** [comment]
@petermz Thank you for identifying the commits from the WebKit trunk that are needed to address this. Since the WebKit code in question is third-party code, you can't contribute it under the terms of the OCA. Someone from Oracle will need to do this.

Also, we are in the process of updating WebKit to a new stable version, so your proposed source code changes would conflict. After that is integrated, we can take a look at this and work with you to get this fixed.

**Comment by kevinrushforth** [comment]
Question: Is this a native arm64 build or is it an x86_64 build running via Rosetta2?

**Comment by petermz** [comment]
This is for a native build.
I had to hack gradle scripts to produce one, but these hacks are not part of this PR

**Comment by kevinrushforth** [comment]
Thanks for the confirmation.

**Pull request closed without merging**
