### PR TITLE
8259635: Update to 610.2 version of WebKit 

### PR DESCRIPTION
**Pull request by arun-Joseph**
Update JavaFX WebKit to GTK WebKit 2.30 (610.2)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8259635](https://bugs.openjdk.java.net/browse/JDK-8259635): Update to 610.2 version of WebKit

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Guru Hb](https://openjdk.java.net/census#ghb) (@guruhb - **Reviewer**)
 * [Johan Vos](https://openjdk.java.net/census#jvos) (@johanvos - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jfx pull/382/head:pull/382`
`$ git checkout pull/382`

### CODE REVIEW

**Comment by kevinrushforth** [comment]
I reviewed all of the changes outside `modules/javafx.web/src/main/native/`. Most look related to the change to use the Prism Color object instead of an int. I did have a question about one of those changes:

```
modules/javafx.web/src/main/java/com/sun/webkit/plugin/DefaultPlugin.java
-        g.fillRect(x, y, w, h, 0x11aaffff);
+        g.fillRect(x, y, w, h, new Color(0.33f, 1.0f, 1.0f, 0.1f));
```

These are not equivalent colors. Is this intentional?

**Comment by arun-Joseph** [comment]
It should be `new Color(2 / 3.0f, 1.0f, 1.0f, 1 / 15.0f)`. I'll update the PR.

**Comment by johanvos** [comment]
Build and tests pass on windows/linux/mac in our CI.

**Review by kevinrushforth — APPROVED** [review]
Looks good. Build + automated tests passed on all three platforms. I ran into one manual test issue related to input events on Linux only. I'll file a follow-on bug for that.

**Comment by kevinrushforth** [comment]
I filed [JDK-8260257](https://bugs.openjdk.java.net/browse/JDK-8260257) to track the Linux input event issue.

**Review by guruhb — APPROVED** [review]
Changes looks good to me. Did a local build on all three Platform and sanity test by loading top 10 websites loaded without any deviation from old build.

**Review by johanvos — APPROVED** [review]

**Pull request closed without merging**
