### PR TITLE
8284662: [Win][Accessibility][ListCell] Screen reader fails to read ListView/ComboBox item count if > 100

### PR DESCRIPTION
**Pull request by arapte**
Accessibility client applications like Windows Narrator and JAWS read positions of the items in a ListView/ComboBox as "index of total-item-count".
For example, in an ComboBox with 10 items, first item "Item1" would be read as "Item one, one of ten". Similarly it appends the <index of item> of <total-number-of-item> for all items.

Currently this is not read correctly,
- by Narrator if total number of items is > 100
- by JAWS if total number of items is > 200

One main reason is that JavaFX is not serving request from A11Y client applications for UIA_PositionInSetPropertyId and UIA_SizeOfSetPropertyId properties.

Serving request for these properties fixes the issue.

Verification:
There are two test programs (for ComboBox and ListView) attached to [JDK-8284662](https://bugs.openjdk.org/browse/JDK-8284662)
Please run those and observe how Narrator reads them with and without fix.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8284662](https://bugs.openjdk.org/browse/JDK-8284662): [Win][Accessibility][ListCell] Screen reader fails to read ListView/ComboBox item count if &gt; 100

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Ajit Ghaisas](https://openjdk.org/census#aghaisas) (@aghaisas - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jfx pull/1036/head:pull/1036` \
`$ git checkout pull/1036`

Update a local copy of the PR: \
`$ git checkout pull/1036` \
`$ git pull https://git.openjdk.org/jfx pull/1036/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1036`

View PR using the GUI difftool: \
`$ git pr show -t 1036`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jfx/pull/1036.diff">https://git.openjdk.org/jfx/pull/1036.diff</a>

</details>

### CODE REVIEW

**Review by kevinrushforth — APPROVED** [review]
Looks good.

**Comment by kevinrushforth** [comment]
@aghaisas can you be the second reviewer?

**Review by aghaisas — APPROVED** [review]
Tested only with Narrator.
Fix looks good!

**Pull request closed without merging**
